/**
 * Flag Registry — every flag rule as a typed array.
 *
 * Pure data, no logic.
 */

import type { FlagRule } from "./types";

// ---------------------------------------------------------------------------
// Flag rules
// ---------------------------------------------------------------------------

export const FLAG_RULES: FlagRule[] = [
  // ── Ratio flags ──────────────────────────────────────────────────────────
  {
    trigger_type: "dscr_below_1x",
    category: "financial_irregularity",
    default_severity: "critical",
    description: "Debt Service Coverage Ratio below 1.0x — business cannot service its debt from cash flow",
    canonical_keys_involved: ["DSCR", "CASH_FLOW_AVAILABLE", "ANNUAL_DEBT_SERVICE"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "dscr_below_policy_minimum",
    category: "policy_proximity",
    default_severity: "elevated",
    description: "DSCR below bank policy minimum (typically 1.25x)",
    canonical_keys_involved: ["DSCR"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "dscr_two_year_decline",
    category: "financial_irregularity",
    default_severity: "elevated",
    description: "DSCR has declined in each of the last two years",
    canonical_keys_involved: ["DSCR"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "fccr_below_1x",
    category: "financial_irregularity",
    default_severity: "critical",
    description: "Fixed Charge Coverage Ratio below 1.0x",
    canonical_keys_involved: ["FCCR"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "debt_ebitda_above_5x",
    category: "financial_irregularity",
    default_severity: "critical",
    description: "Debt-to-EBITDA ratio exceeds 5.0x — highly leveraged",
    canonical_keys_involved: ["DEBT_TO_EBITDA", "TOTAL_LIABILITIES", "EBITDA"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "debt_ebitda_above_4x",
    category: "financial_irregularity",
    default_severity: "watch",
    description: "Debt-to-EBITDA ratio exceeds 4.0x",
    canonical_keys_involved: ["DEBT_TO_EBITDA"],
    generates_question: false,
    recipient_type: "borrower",
  },
  {
    trigger_type: "dso_above_90",
    category: "financial_irregularity",
    default_severity: "elevated",
    description: "Days Sales Outstanding exceeds 90 days — potential collection issues",
    canonical_keys_involved: ["DSO", "ACCOUNTS_RECEIVABLE", "TOTAL_REVENUE"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "dso_increasing_15_days",
    category: "financial_irregularity",
    default_severity: "watch",
    description: "DSO has increased by 15+ days year-over-year",
    canonical_keys_involved: ["DSO"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "current_ratio_below_1x",
    category: "financial_irregularity",
    default_severity: "critical",
    description: "Current ratio below 1.0x — current liabilities exceed current assets",
    canonical_keys_involved: ["CURRENT_RATIO", "TOTAL_CURRENT_ASSETS", "TOTAL_CURRENT_LIABILITIES"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "current_ratio_below_policy",
    category: "policy_proximity",
    default_severity: "watch",
    description: "Current ratio below bank policy minimum",
    canonical_keys_involved: ["CURRENT_RATIO"],
    generates_question: false,
    recipient_type: "borrower",
  },
  {
    trigger_type: "ltv_above_80",
    category: "financial_irregularity",
    default_severity: "critical",
    description: "Loan-to-Value ratio exceeds 80%",
    canonical_keys_involved: ["LTV"],
    generates_question: false,
    recipient_type: "borrower",
  },
  {
    trigger_type: "gross_margin_compressed_500bps",
    category: "financial_irregularity",
    default_severity: "elevated",
    description: "Gross margin has compressed by 500+ basis points year-over-year",
    canonical_keys_involved: ["GROSS_MARGIN"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "revenue_declining_10pct",
    category: "financial_irregularity",
    default_severity: "elevated",
    description: "Revenue declined more than 10% year-over-year",
    canonical_keys_involved: ["TOTAL_REVENUE"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "revenue_growing_margin_compressing",
    category: "qualitative_risk",
    default_severity: "watch",
    description: "Revenue is growing but profit margins are compressing",
    canonical_keys_involved: ["TOTAL_REVENUE", "GROSS_MARGIN"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "cash_conversion_cycle_above_90",
    category: "financial_irregularity",
    default_severity: "watch",
    description: "Cash conversion cycle exceeds 90 days",
    canonical_keys_involved: ["CCC", "DSO", "DIO", "DPO"],
    generates_question: true,
    recipient_type: "borrower",
  },

  // ── Reconciliation flags ─────────────────────────────────────────────────
  {
    trigger_type: "revenue_variance_3pct",
    category: "financial_irregularity",
    default_severity: "critical",
    description: "Revenue on tax return differs from financial statements by more than 3%",
    canonical_keys_involved: ["GROSS_RECEIPTS", "TOTAL_REVENUE"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "schedule_l_variance_3pct",
    category: "financial_irregularity",
    default_severity: "elevated",
    description: "Schedule L total assets differs from financial statement balance sheet by more than 3%",
    canonical_keys_involved: ["SL_TOTAL_ASSETS", "TOTAL_ASSETS"],
    generates_question: true,
    recipient_type: "accountant",
  },
  {
    trigger_type: "retained_earnings_rollforward_mismatch",
    category: "financial_irregularity",
    default_severity: "elevated",
    description: "Retained earnings rollforward does not reconcile",
    canonical_keys_involved: ["RETAINED_EARNINGS", "M2_RETAINED_EARNINGS_BEGIN", "M2_RETAINED_EARNINGS_END"],
    generates_question: true,
    recipient_type: "accountant",
  },
  {
    trigger_type: "k1_orphan_entity",
    category: "financial_irregularity",
    default_severity: "critical",
    description: "K-1 income from an entity not included in the deal analysis",
    canonical_keys_involved: ["K1_ORDINARY_INCOME", "K1_ENTITY_EIN"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "large_other_income_5pct",
    category: "financial_irregularity",
    default_severity: "elevated",
    description: "Other income exceeds 5% of total revenue",
    canonical_keys_involved: ["OTHER_DEDUCTIONS", "TOTAL_REVENUE"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "large_other_expense_5pct",
    category: "financial_irregularity",
    default_severity: "elevated",
    description: "Other deductions exceed 5% of total revenue",
    canonical_keys_involved: ["OTHER_DEDUCTIONS", "TOTAL_REVENUE"],
    generates_question: true,
    recipient_type: "borrower",
  },

  // ── QoE flags ────────────────────────────────────────────────────────────
  {
    trigger_type: "qoe_adjustment_low_confidence",
    category: "qualitative_risk",
    default_severity: "elevated",
    description: "Quality of earnings adjustment has low confidence classification",
    canonical_keys_involved: ["QOE_ADJUSTED_EBITDA", "QOE_CONFIDENCE"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "qoe_total_adjustments_exceed_20pct",
    category: "financial_irregularity",
    default_severity: "critical",
    description: "Total QoE adjustments exceed 20% of reported EBITDA",
    canonical_keys_involved: ["QOE_REPORTED_EBITDA", "QOE_ADJUSTMENT_TOTAL"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "nonrecurring_income_present",
    category: "qualitative_risk",
    default_severity: "watch",
    description: "Non-recurring income items detected in financials",
    canonical_keys_involved: ["NON_RECURRING_INCOME"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "erc_credit_excluded",
    category: "qualitative_risk",
    default_severity: "informational",
    description: "Employee Retention Credit excluded from adjusted EBITDA",
    canonical_keys_involved: ["NON_RECURRING_INCOME"],
    generates_question: false,
    recipient_type: "borrower",
  },

  // ── Trend flags ──────────────────────────────────────────────────────────
  {
    trigger_type: "ebitda_margin_declining_2yr",
    category: "financial_irregularity",
    default_severity: "elevated",
    description: "EBITDA margin has declined for 2+ consecutive years",
    canonical_keys_involved: ["EBITDA_MARGIN"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "revenue_declining_2yr",
    category: "financial_irregularity",
    default_severity: "elevated",
    description: "Revenue has declined for 2+ consecutive years",
    canonical_keys_involved: ["TOTAL_REVENUE"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "leverage_increasing_2yr",
    category: "financial_irregularity",
    default_severity: "watch",
    description: "Leverage (Debt/EBITDA) has increased for 2+ consecutive years",
    canonical_keys_involved: ["DEBT_TO_EBITDA"],
    generates_question: false,
    recipient_type: "borrower",
  },
  {
    trigger_type: "working_capital_deteriorating",
    category: "financial_irregularity",
    default_severity: "watch",
    description: "Working capital declining for 2+ consecutive years",
    canonical_keys_involved: ["TOTAL_CURRENT_ASSETS", "TOTAL_CURRENT_LIABILITIES"],
    generates_question: true,
    recipient_type: "borrower",
  },

  // ── Document / structural flags ──────────────────────────────────────────
  {
    trigger_type: "lease_expiring_within_loan_term",
    category: "qualitative_risk",
    default_severity: "elevated",
    description: "Primary lease expires before loan maturity",
    canonical_keys_involved: [],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "customer_concentration_25pct",
    category: "qualitative_risk",
    default_severity: "elevated",
    description: "Single customer represents more than 25% of revenue",
    canonical_keys_involved: [],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "provider_concentration_80pct",
    category: "qualitative_risk",
    default_severity: "critical",
    description: "Single provider/practitioner represents more than 80% of revenue",
    canonical_keys_involved: [],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "undisclosed_contingent_liability",
    category: "financial_irregularity",
    default_severity: "critical",
    description: "Contingent liabilities detected on personal financial statement but not discussed",
    canonical_keys_involved: [],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "entity_formed_within_12_months",
    category: "qualitative_risk",
    default_severity: "watch",
    description: "Entity was formed within the last 12 months",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "borrower",
  },
  {
    trigger_type: "ydt_financials_stale_90_days",
    category: "missing_data",
    default_severity: "elevated",
    description: "Year-to-date financials are more than 90 days old",
    canonical_keys_involved: [],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "schedule_e_missing",
    category: "missing_data",
    default_severity: "elevated",
    description: "Schedule E is missing but rental income is present on personal return",
    canonical_keys_involved: ["SCH_E_RENTS_RECEIVED"],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "personal_financial_statement_stale",
    category: "missing_data",
    default_severity: "elevated",
    description: "Personal financial statement is more than 90 days old",
    canonical_keys_involved: [],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "rent_roll_missing",
    category: "missing_data",
    default_severity: "elevated",
    description: "Rent roll is missing for a real estate collateral property",
    canonical_keys_involved: [],
    generates_question: true,
    recipient_type: "borrower",
  },
  {
    trigger_type: "construction_budget_missing",
    category: "missing_data",
    default_severity: "critical",
    description: "Construction budget is missing for a construction/renovation loan",
    canonical_keys_involved: [],
    generates_question: true,
    recipient_type: "borrower",
  },

  // ── Policy proximity flags (banker only) ─────────────────────────────────
  {
    trigger_type: "dscr_proximity_within_10pct",
    category: "policy_proximity",
    default_severity: "watch",
    description: "DSCR is within 10% of policy minimum",
    canonical_keys_involved: ["DSCR"],
    generates_question: false,
    recipient_type: "borrower",
  },
  {
    trigger_type: "current_ratio_proximity",
    category: "policy_proximity",
    default_severity: "watch",
    description: "Current ratio is within 10% of policy minimum",
    canonical_keys_involved: ["CURRENT_RATIO"],
    generates_question: false,
    recipient_type: "borrower",
  },
  {
    trigger_type: "ltv_proximity_within_5pct",
    category: "policy_proximity",
    default_severity: "watch",
    description: "LTV is within 5 percentage points of policy maximum",
    canonical_keys_involved: ["LTV"],
    generates_question: false,
    recipient_type: "borrower",
  },
  {
    trigger_type: "debt_ebitda_proximity",
    category: "policy_proximity",
    default_severity: "watch",
    description: "Debt/EBITDA is within 10% of policy maximum",
    canonical_keys_involved: ["DEBT_TO_EBITDA"],
    generates_question: false,
    recipient_type: "borrower",
  },
  {
    trigger_type: "tnw_thin_positive",
    category: "policy_proximity",
    default_severity: "watch",
    description: "Tangible net worth is positive but thin relative to total assets",
    canonical_keys_involved: ["TANGIBLE_NET_WORTH", "TOTAL_ASSETS"],
    generates_question: false,
    recipient_type: "borrower",
  },
  {
    trigger_type: "post_close_liquidity_thin",
    category: "policy_proximity",
    default_severity: "watch",
    description: "Post-close liquidity is thin — limited cushion after closing",
    canonical_keys_involved: ["CASH_AND_EQUIVALENTS"],
    generates_question: false,
    recipient_type: "borrower",
  },

  // ── Research-derived flags (banker-only, informational) ──────────────────
  {
    trigger_type: "research_adverse_event_risk",
    category: "qualitative_risk",
    default_severity: "critical",
    description: "Research found adverse events in principal/management backgrounds",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "banker",
  },
  {
    trigger_type: "research_execution_risk",
    category: "qualitative_risk",
    default_severity: "elevated",
    description: "Research identified elevated execution risk in management team",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "banker",
  },
  {
    trigger_type: "research_cyclicality_risk",
    category: "qualitative_risk",
    default_severity: "watch",
    description: "Research identifies high cyclicality in this industry",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "banker",
  },
  {
    trigger_type: "research_regulatory_burden",
    category: "qualitative_risk",
    default_severity: "watch",
    description: "Research identifies elevated regulatory burden or compliance requirements",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "banker",
  },
  {
    trigger_type: "research_headwind",
    category: "qualitative_risk",
    default_severity: "watch",
    description: "Research identified material industry headwinds",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "banker",
  },
  {
    trigger_type: "research_geographic_concentration",
    category: "qualitative_risk",
    default_severity: "watch",
    description: "Research identified elevated geographic market concentration risk",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "banker",
  },
  {
    trigger_type: "research_competitive_intensity",
    category: "qualitative_risk",
    default_severity: "watch",
    description: "Research found high competitive intensity in this market",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "banker",
  },
  {
    trigger_type: "research_regulatory_risk_level",
    category: "qualitative_risk",
    default_severity: "elevated",
    description: "Research found elevated regulatory risk level for this industry",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "banker",
  },
  {
    trigger_type: "research_expansion_constraint_risk",
    category: "qualitative_risk",
    default_severity: "watch",
    description: "Research identified regulatory constraints on business expansion",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "banker",
  },
  {
    trigger_type: "research_stress_resilience_low",
    category: "qualitative_risk",
    default_severity: "elevated",
    description: "Research found low stress resilience — limited downside cushion",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "banker",
  },
  {
    trigger_type: "research_downside_risk",
    category: "qualitative_risk",
    default_severity: "elevated",
    description: "Research identified material downside risk scenarios",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "banker",
  },
  {
    trigger_type: "research_lender_program_fit_low",
    category: "qualitative_risk",
    default_severity: "watch",
    description: "Research found this deal has low fit with available SBA/USDA programs",
    canonical_keys_involved: [],
    generates_question: false,
    recipient_type: "banker",
  },
];

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

const RULE_MAP = new Map(FLAG_RULES.map((r) => [r.trigger_type, r]));

export function getRule(triggerType: string): FlagRule | undefined {
  return RULE_MAP.get(triggerType);
}

export function getRulesByCategory(category: string): FlagRule[] {
  return FLAG_RULES.filter((r) => r.category === category);
}
