/**
 * Verbatim rows transcribed from 13 CFR §121.201 as rendered by eCFR
 * (retrieved 2026-08-17; Title 13 current as of 2026-08-13, §121.201 last
 * amended effective 2023-03-17).
 *
 * ─── Scope of this file ─────────────────────────────────────────────────
 * This is a TEST FIXTURE, not reference data. It exists so the pure parser
 * can be exercised against the real shapes SBA publishes — headings,
 * exception rows, footnote markers, comma-separated employee counts,
 * receipts with and without trailing zeros.
 *
 * It is deliberately small and MUST NOT grow into a hand-maintained copy of
 * the table. The production dataset is generated by
 * scripts/reference-data/build-sba-size-standards.ts from the official
 * source and validated against its manifest. guard-reference-dataset-
 * coverage.mjs fails CI if anything under src/ ever ships a partial
 * hand-written size-standard table again.
 * ────────────────────────────────────────────────────────────────────────
 */

import type { RawSizeStandardRow } from "../parseSizeStandardRow";

export const ECFR_FIXTURE_ROWS: ReadonlyArray<RawSizeStandardRow> = [
  // Sector heading
  {
    naicsCell: "Sector 11—Agriculture, Forestry, Fishing and Hunting",
    titleCell: "",
    receiptsCell: "",
    employeesCell: "",
  },
  // Subsector heading
  {
    naicsCell: "Subsector 111—Crop Production",
    titleCell: "",
    receiptsCell: "",
    employeesCell: "",
  },
  // Receipts, lowest standard in the table
  {
    naicsCell: "111110",
    titleCell: "Soybean Farming",
    receiptsCell: "$2.25",
    employeesCell: "",
  },
  // Receipts, single decimal place as published
  {
    naicsCell: "111310",
    titleCell: "Orange Groves",
    receiptsCell: "$4.0",
    employeesCell: "",
  },
  // Employees, bare value (must NOT be read as a footnote marker)
  {
    naicsCell: "113310",
    titleCell: "Logging",
    receiptsCell: "",
    employeesCell: "500",
  },
  // Exception rows sharing base code 115310, both footnoted
  {
    naicsCell: "115310",
    titleCell: "Support Activities for Forestry",
    receiptsCell: "$11.5",
    employeesCell: "",
  },
  {
    naicsCell: "115310 (Exception 1)",
    titleCell: "Forest Fire Suppression 1",
    receiptsCell: "$34.0 1",
    employeesCell: "",
  },
  {
    naicsCell: "115310 (Exception 2)",
    titleCell: "Fuels Management Services 1",
    receiptsCell: "$34.0 1",
    employeesCell: "",
  },
  // Employees with thousands separator — the row the legacy importer
  // recorded as "$1.25 billion of revenue".
  {
    naicsCell: "211120",
    titleCell: "Crude Petroleum Extraction",
    receiptsCell: "",
    employeesCell: "1,250",
  },
  // Unnumbered exception
  {
    naicsCell: "237900 (Exception)",
    titleCell: "Dredging and Surface Cleanup Activities 2",
    receiptsCell: "$37.0 2",
    employeesCell: "",
  },
  // Employee standard with footnote on both title and value
  {
    naicsCell: "324110",
    titleCell: "Petroleum Refineries 4",
    receiptsCell: "",
    employeesCell: "1,500 4",
  },
  // Highest receipts standard in the table
  {
    naicsCell: "213112",
    titleCell: "Support Activities for Oil and Gas Operations",
    receiptsCell: "$47.0",
    employeesCell: "",
  },
  // Construction — common SBA-lending industry
  {
    naicsCell: "236220",
    titleCell: "Commercial and Institutional Building Construction",
    receiptsCell: "$45.0",
    employeesCell: "",
  },
];

/** Rows that must be rejected rather than silently coerced. */
export const MALFORMED_FIXTURE_ROWS: ReadonlyArray<RawSizeStandardRow> = [
  {
    naicsCell: "1234",
    titleCell: "Truncated code",
    receiptsCell: "$5.0",
    employeesCell: "",
  },
  {
    naicsCell: "722511",
    titleCell: "Both columns populated",
    receiptsCell: "$12.0",
    employeesCell: "500",
  },
  {
    naicsCell: "722513",
    titleCell: "Unparseable value",
    receiptsCell: "see footnote",
    employeesCell: "",
  },
];
