import { isAutoGeneratedDealName } from "./isAutoGeneratedDealName";

export type DealHeaderInput = {
  display_name?: string | null;
  name?: string | null;
};

export type DealHeaderResult = {
  title: string;
  needsName: boolean;
};

/**
 * Derive the cockpit header title and "needs name" state from deal metadata.
 *
 * Resolution: display_name → name → fallback "Deal {id.slice(0,8)}"
 * needsName: true only when BOTH display_name and name are empty/blank.
 */
export function deriveDealHeader(
  dealId: string,
  meta: DealHeaderInput | null | undefined,
): DealHeaderResult {
  const fallback = `Deal ${dealId.slice(0, 8)}`;

  if (!meta) {
    return { title: fallback, needsName: true };
  }

  const displayName = (meta.display_name ?? "").trim();
  const name = (meta.name ?? "").trim();
  const hasName = Boolean(displayName || name);

  // Try display_name first, then name — skip auto-generated values
  for (const candidate of [displayName, name]) {
    if (candidate && !isAutoGeneratedDealName(candidate)) {
      return { title: candidate, needsName: !hasName };
    }
  }

  return { title: fallback, needsName: !hasName };
}
