/**
 * Detect auto-generated / garbage deal names that should be overwritten
 * by AI-extracted names from document classification.
 */

const UUID_RE = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;
const HEX_PREFIX_RE = /^Deal\s+[0-9a-f]{6,}/i;
const DATE_SUFFIX_RE = /^Deal\s*-\s*\d{1,2}\/\d{1,2}\/\d{2,4}$/i;

export function isAutoGeneratedDealName(name: string | null | undefined): boolean {
  if (!name || !name.trim()) return true;
  const trimmed = name.trim();

  // "Pending Autofill"
  if (trimmed.toLowerCase() === "pending autofill") return true;

  // "Deal - 1/28/2026" or similar date pattern
  if (DATE_SUFFIX_RE.test(trimmed)) return true;

  // "Deal 1433a5c7..." (hex ID prefix)
  if (HEX_PREFIX_RE.test(trimmed)) return true;

  // Contains a full UUID anywhere
  if (UUID_RE.test(trimmed)) return true;

  // "Untitled deal" (our own placeholder)
  if (trimmed.toLowerCase() === "untitled deal") return true;

  // "New Deal" placeholder
  if (trimmed.toLowerCase() === "new deal") return true;

  return false;
}
