import { Deal } from "./types";

export const sampleDeals: Deal[] = [
  {
    id: "apex-logistics",
    name: "Apex Logistics Center - Phase II",
    subtitle: "Austin, TX • Industrial",
    address: "14502 Innovation Blvd, Austin, TX 78744",
    amount: 18500000,
    stage: "Underwriting",
    riskRating: "B-",
    approvalProb: 72,
    leadInitials: "JS",
    leadName: "J. Smith",
    updatedLabel: "2m ago",
    updatedNote: "Status Change",
    blocker: "warning",
    docCompleteness: { done: 9, total: 12 },
    dscr: "1.28x",
    ltv: "68%",
    debtYield: "10.2%",
    primaryRiskDriver: "Tenant concentration: Single tenant represents 42% of NOI. Lease expires in 18 months with no renewal commitment.",
    nextAction: "Request tenant financials and lease renewal intent letter",
    nextActionCta: "Send Request Link",
    documents: [
      { name: "Rent Roll", status: "complete" },
      { name: "Operating Statement (TTM)", status: "complete" },
      { name: "Tax Returns (2023)", status: "pending" },
      { name: "Environmental Phase I", status: "complete" },
      { name: "Property Appraisal", status: "missing" },
    ],
  },
  {
    id: "harbor-view",
    name: "Harbor View Multi-Family",
    subtitle: "Seattle, WA • Multifamily",
    address: "2250 Harbor Ave, Seattle, WA 98101",
    amount: 24000000,
    stage: "Underwriting",
    riskRating: "A",
    approvalProb: 89,
    leadInitials: "MK",
    leadName: "M. Kim",
    updatedLabel: "15m ago",
    updatedNote: undefined,
    blocker: null,
    docCompleteness: { done: 12, total: 12 },
    dscr: "1.42x",
    ltv: "65%",
    debtYield: "11.8%",
  },
  {
    id: "techpark-austin",
    name: "TechPark Austin Refi",
    subtitle: "Austin, TX • Office",
    address: "9800 Research Blvd, Austin, TX 78759",
    amount: 12300000,
    stage: "Credit",
    riskRating: "B+",
    approvalProb: 81,
    leadInitials: "TR",
    leadName: "T. Rodriguez",
    updatedLabel: "1h ago",
    updatedNote: "Committee Review",
    blocker: null,
    docCompleteness: { done: 11, total: 11 },
    dscr: "1.35x",
    ltv: "70%",
    debtYield: "9.8%",
  },
  {
    id: "midtown-mixed",
    name: "Midtown Mixed-Use Construction",
    subtitle: "Denver, CO • Mixed-Use",
    address: "1500 Larimer St, Denver, CO 80202",
    amount: 32000000,
    stage: "New",
    riskRating: "C+",
    approvalProb: 58,
    leadInitials: "AL",
    leadName: "A. Lopez",
    updatedLabel: "Today 09:42 AM",
    updatedNote: undefined,
    blocker: "critical",
    docCompleteness: { done: 4, total: 15 },
    dscr: "1.15x",
    ltv: "75%",
    debtYield: "8.2%",
  },
  {
    id: "sierra-industrial",
    name: "Sierra Industrial Park",
    subtitle: "Phoenix, AZ • Industrial",
    address: "5600 W Buckeye Rd, Phoenix, AZ 85043",
    amount: 15800000,
    stage: "Approved",
    riskRating: "A-",
    approvalProb: 95,
    leadInitials: "BC",
    leadName: "B. Chen",
    updatedLabel: "Yesterday 4:22 PM",
    updatedNote: "Conditions Met",
    blocker: null,
    docCompleteness: { done: 13, total: 13 },
    dscr: "1.52x",
    ltv: "60%",
    debtYield: "12.5%",
  },
  {
    id: "lakeside-retail",
    name: "Lakeside Retail Promenade",
    subtitle: "Atlanta, GA • Retail",
    address: "3400 Peachtree Rd NE, Atlanta, GA 30326",
    amount: 9200000,
    stage: "Underwriting",
    riskRating: "B",
    approvalProb: 68,
    leadInitials: "DW",
    leadName: "D. White",
    updatedLabel: "2 days ago",
    updatedNote: undefined,
    blocker: "warning",
    docCompleteness: { done: 7, total: 10 },
    dscr: "1.22x",
    ltv: "72%",
    debtYield: "9.1%",
  },
  {
    id: "ironwood-medical",
    name: "Ironwood Medical Office",
    subtitle: "Portland, OR • Medical Office",
    address: "10200 SW Eastridge St, Portland, OR 97225",
    amount: 11500000,
    stage: "Closed",
    riskRating: "A",
    approvalProb: 100,
    leadInitials: "PG",
    leadName: "P. Garcia",
    updatedLabel: "Last week",
    updatedNote: "Funded",
    blocker: null,
    docCompleteness: { done: 14, total: 14 },
    dscr: "1.48x",
    ltv: "62%",
    debtYield: "11.2%",
  },
];
