export type StarterTemplateDefinition = {
  key: string;
  label: string;
  explanation: string;
  emailSubject: string;
  emailBody: string;
  smsBody: string;
};

export const STARTER_MESSAGE_TEMPLATES: StarterTemplateDefinition[] = [
  { key: "initial_lead_response", label: "New inquiry response", explanation: "Acknowledge a new borrower or referral quickly.", emailSubject: "We received your SBA financing inquiry", emailBody: "Hi {{first_name}},\n\nThank you for reaching out to Buddy SBA. I received your financing inquiry and will review the details before our first conversation. You can reply here with any context you would like me to know.\n\nBest,\n{{owner_name}}", smsBody: "Hi {{first_name}}, this is {{owner_name}} with Buddy SBA. I received your financing inquiry and will be in touch to discuss the next step." },
  { key: "discovery_scheduling", label: "Schedule discovery call", explanation: "Invite the prospect to the first structured conversation.", emailSubject: "Choose a time for your SBA discovery call", emailBody: "Hi {{first_name}},\n\nThe next step is a short discovery call to understand the business, financing request, timing, and goals. Please choose a convenient time here: {{scheduling_link}}.\n\nBest,\n{{owner_name}}", smsBody: "Hi {{first_name}}, ready for the next step? Choose a time for our SBA discovery call: {{scheduling_link}}" },
  { key: "document_request", label: "Request documents", explanation: "Explain exactly what is needed and why.", emailSubject: "Documents needed for {{business_name}}", emailBody: "Hi {{first_name}},\n\nTo keep your financing review moving, please upload the items listed in your secure Buddy checklist: {{portal_link}}. If any item is unavailable, reply and tell me what you have instead.\n\nBest,\n{{owner_name}}", smsBody: "Hi {{first_name}}, your secure document checklist is ready: {{portal_link}}. Reply if you need help with any item." },
  { key: "engagement_follow_up", label: "Engagement follow-up", explanation: "Reconnect after an early conversation without sounding automated.", emailSubject: "Following up on {{business_name}}", emailBody: "Hi {{first_name}},\n\nI wanted to follow up on our conversation about {{business_name}}. Your next step is {{next_action}}. Please reply if your timing or priorities have changed.\n\nBest,\n{{owner_name}}", smsBody: "Hi {{first_name}}, following up on {{business_name}}. Your next step is {{next_action}}. Can I help unblock anything?" },
  { key: "incomplete_application", label: "Incomplete application", explanation: "Help the borrower finish an application already in progress.", emailSubject: "Finish your Buddy SBA application", emailBody: "Hi {{first_name}},\n\nYour application for {{business_name}} is saved, but a few items are still incomplete. Continue securely here: {{portal_link}}. Your progress will be waiting for you.\n\nBest,\n{{owner_name}}", smsBody: "Hi {{first_name}}, your Buddy SBA application is saved. Continue where you left off: {{portal_link}}" },
  { key: "lender_introduction", label: "Lender introduction", explanation: "Introduce the borrower and lender with clear expectations.", emailSubject: "Introduction: {{business_name}} and {{lender_name}}", emailBody: "Hello {{first_name}},\n\nI am introducing you to {{lender_name}} regarding the financing request for {{business_name}}. I will remain involved and help coordinate next steps. Please keep everyone on this thread so the process stays clear.\n\nBest,\n{{owner_name}}", smsBody: "Hi {{first_name}}, I have introduced {{business_name}} to {{lender_name}} by email. I will stay involved as next steps are confirmed." },
  { key: "lender_submission", label: "Submit to lender", explanation: "Tell the lender what is being submitted and the requested response.", emailSubject: "SBA opportunity: {{business_name}}", emailBody: "Hi {{lender_contact_name}},\n\nBuddy SBA is submitting {{business_name}} for your review. The requested financing is {{loan_amount}} for {{loan_purpose}}. The secure package is available here: {{package_link}}. Please confirm receipt and your initial fit assessment.\n\nBest,\n{{owner_name}}", smsBody: "Hi {{lender_contact_name}}, Buddy SBA sent the {{business_name}} opportunity to your email. Please confirm receipt when convenient." },
  { key: "submission_follow_up", label: "Lender follow-up", explanation: "Request a placement update without losing context.", emailSubject: "Status check: {{business_name}}", emailBody: "Hi {{lender_contact_name}},\n\nI am checking on your review of {{business_name}}. Could you share the current status, outstanding questions, and expected next decision date?\n\nThank you,\n{{owner_name}}", smsBody: "Hi {{lender_contact_name}}, checking on the {{business_name}} review. What is the current status and next decision date?" },
  { key: "underwriting_condition_request", label: "Underwriting condition", explanation: "Request a condition while keeping the reason and deadline clear.", emailSubject: "Action needed for {{business_name}}", emailBody: "Hi {{first_name}},\n\nThe lender needs the following item to continue underwriting: {{condition}}. Please upload it securely by {{due_date}} using {{portal_link}}. Contact me if the request is unclear.\n\nBest,\n{{owner_name}}", smsBody: "Hi {{first_name}}, the lender needs {{condition}} by {{due_date}}. Upload securely here: {{portal_link}}" },
  { key: "closing_coordination", label: "Closing coordination", explanation: "Keep borrower, lender, and team aligned before closing.", emailSubject: "Closing plan for {{business_name}}", emailBody: "Hi {{first_name}},\n\nYour current target closing date is {{closing_date}}. The remaining items are {{remaining_items}}. I will coordinate updates with the lender and let you know immediately if anything changes.\n\nBest,\n{{owner_name}}", smsBody: "Hi {{first_name}}, {{business_name}} is targeting {{closing_date}}. Remaining items: {{remaining_items}}. I will keep you updated." },
  { key: "referral_acknowledgment", label: "Thank a referral partner", explanation: "Confirm a referral and reinforce the relationship.", emailSubject: "Thank you for introducing {{first_name}}", emailBody: "Hi {{referral_partner_name}},\n\nThank you for introducing {{first_name}} at {{business_name}}. We have received the opportunity and will handle the relationship thoughtfully. I will keep you informed at the appropriate milestones.\n\nBest,\n{{owner_name}}", smsBody: "Thank you for introducing {{first_name}} at {{business_name}}. We received the opportunity and will take good care of the relationship." },
  { key: "funding_notification", label: "Funding announcement", explanation: "Celebrate funding and clarify the immediate next step.", emailSubject: "{{business_name}} has funded", emailBody: "Hi {{first_name}},\n\nCongratulations—{{business_name}} has funded. Thank you for trusting Buddy SBA to help guide the process. Your immediate next step is {{next_action}}.\n\nBest,\n{{owner_name}}", smsBody: "Congratulations, {{first_name}}—{{business_name}} has funded. Thank you for trusting Buddy SBA." },
  { key: "referral_thank_you", label: "Close the referral loop", explanation: "Thank the referral source after a successful outcome.", emailSubject: "{{business_name}} funded—thank you", emailBody: "Hi {{referral_partner_name}},\n\nI am pleased to share that {{business_name}} has funded. Thank you for making the introduction and trusting Buddy SBA with the relationship.\n\nBest,\n{{owner_name}}", smsBody: "Great news: {{business_name}} funded. Thank you for the introduction and for trusting Buddy SBA." },
];
