-- SPEC-SYSTEM-DEBLOAT-1 Phase C3 — pre-drop DDL export for email_situations.
-- Schema-only reconstruction (columns, defaults, PK/unique/check constraints,
-- non-PK indexes) via information_schema/pg_catalog, generated 2026-07-29 —
-- see scripts/audit/export-table-ddl.sh for methodology and caveats.
-- Restore: psql "$BUDDY_DB_URL" -f email_situations.sql
-- (table was empty at drop time — this recreates structure only, no data)

CREATE TABLE public.email_situations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  source_thread_id text NOT NULL,
  source_thread_ids text[] DEFAULT '{}'::text[],
  situation_class text NOT NULL,
  significance_tier text NOT NULL DEFAULT 'normal'::text,
  significance_drivers text[] DEFAULT '{}'::text[],
  non_obvious_reason text,
  handling_mode text NOT NULL,
  handling_rationale text,
  executive_brief text NOT NULL,
  prepared_reply text,
  prepared_reply_subject text,
  dossier text,
  obligation_summary text,
  suppressed_count integer DEFAULT 0,
  auto_handled boolean DEFAULT false,
  auto_handled_note text,
  task_id uuid,
  user_confirmed boolean,
  user_override_class text,
  gemini_model text DEFAULT 'gemini-3.1-flash-lite'::text,
  synthesis_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  brief_what_is_this text,
  brief_why_it_matters text,
  brief_best_next_move text,
  synthesis_version integer DEFAULT 1,
  queue_why_surfaced text,
  audience_scope text,
  primary_implication text,
  action_truth_status text DEFAULT 'recommended'::text,
  sender_intelligence_summary text,
  situation_narrative text,
  primary_consequence text,
  dependency_chain text,
  user_bottleneck_status text,
  timing_risk text,
  trust_risk text,
  why_now_narrative text,
  canonical_truth_packet_json jsonb,
  live_moment_json jsonb,
  next_move_hint_json jsonb,
  cortex_envelope_json jsonb,
  omega_envelope_json jsonb,
  execution_package_json jsonb,
  draft_plan_json jsonb,
  fulfillment_plan_json jsonb,
  execution_continuity_json jsonb,
  organ_convergence_json jsonb,
  sub_envelope_versions jsonb DEFAULT '{}'::jsonb,
  sub_envelope_completed_at timestamp with time zone,
  CONSTRAINT email_situations_action_truth_status_check CHECK (((action_truth_status IS NULL) OR (action_truth_status = ANY (ARRAY['recommended'::text, 'ready'::text, 'completed'::text, 'waiting'::text])))),
  CONSTRAINT email_situations_audience_scope_check CHECK (((audience_scope IS NULL) OR (audience_scope = ANY (ARRAY['direct'::text, 'small_group'::text, 'team_wide'::text, 'company_wide'::text])))),
  CONSTRAINT email_situations_pkey PRIMARY KEY (id),
  CONSTRAINT email_situations_timing_risk_check CHECK (((timing_risk IS NULL) OR (timing_risk = ANY (ARRAY['none'::text, 'low'::text, 'moderate'::text, 'high'::text, 'deadline_bound'::text])))),
  CONSTRAINT email_situations_trust_risk_check CHECK (((trust_risk IS NULL) OR (trust_risk = ANY (ARRAY['none'::text, 'low'::text, 'moderate'::text, 'high'::text])))),
  CONSTRAINT email_situations_user_bottleneck_status_check CHECK (((user_bottleneck_status IS NULL) OR (user_bottleneck_status = ANY (ARRAY['user_is_blocker'::text, 'user_is_participant'::text, 'waiting_on_others'::text, 'user_not_required'::text])))),
  CONSTRAINT email_situations_user_thread UNIQUE (user_id, source_thread_id)
);
