/**
 * SPEC-BUDDY-FINANCIAL-ENGINE-ELITE-1 — PR 7: Product Intelligence Framework.
 *
 * Recommended covenant packages per product (covenant type keys). Pure data.
 * Advisory input to the covenant recommendation engine (PR 16), which reconciles
 * these with the industry covenant guidance (PR 6).
 */

import type { ProductKey } from "@/lib/finengine/registry/productMetricRegistry";

export const RECOMMENDED_COVENANTS_BY_PRODUCT: Record<ProductKey, readonly string[]> = {
  CI_TERM: ["DSCR", "LEVERAGE", "DISTRIBUTION_LIMITATION", "TAX_RETURN_DELIVERY"],
  WORKING_CAPITAL_LINE: ["CURRENT_RATIO", "WORKING_CAPITAL", "ANNUAL_CLEANUP", "AR_AGING_DELIVERY"],
  AR_REVOLVER: ["BORROWING_BASE", "AR_AGING_DELIVERY", "DILUTION_LIMIT", "DSCR"],
  ABL_REVOLVER: ["BORROWING_BASE", "AR_AGING_DELIVERY", "INVENTORY_REPORTING", "FIELD_EXAM", "FCCR"],
  EQUIPMENT: ["DSCR", "FCCR", "INSURANCE_MAINTENANCE", "NO_FURTHER_LIENS"],
  CRE_OWNER_OCCUPIED: ["DSCR", "LTV", "OCCUPANCY_MAINTENANCE", "PROPERTY_TAX_DELIVERY"],
  CRE_INVESTOR: ["DSCR", "DEBT_YIELD", "LTV", "OCCUPANCY_REPORTING", "RESERVE_MAINTENANCE"],
  CONSTRUCTION: ["LTC", "LTV", "IN_BALANCE_REQUIREMENT", "COMPLETION_GUARANTY", "INSPECTION_DRAW"],
  SBA_7A: ["DSCR", "LIFE_INSURANCE", "STANDBY_DEBT", "TAX_RETURN_DELIVERY", "DISTRIBUTION_LIMITATION"],
  SBA_504: ["DSCR", "LTV", "STANDBY_DEBT", "OCCUPANCY_MAINTENANCE"],
  BUSINESS_ACQUISITION: ["DSCR", "SELLER_NOTE_STANDBY", "LEVERAGE", "DISTRIBUTION_LIMITATION"],
  FRANCHISE: ["DSCR", "FCCR", "FRANCHISE_COMPLIANCE", "DISTRIBUTION_LIMITATION"],
  GUIDANCE_LINE: ["CURRENT_RATIO", "LEVERAGE", "AGGREGATE_EXPOSURE_LIMIT"],
  RENEWAL_MODIFICATION: ["DSCR", "LEVERAGE", "PAYMENT_PERFORMANCE", "UPDATED_FINANCIALS_DELIVERY"],
};

export function recommendedCovenantsForProduct(product: ProductKey): readonly string[] {
  return RECOMMENDED_COVENANTS_BY_PRODUCT[product] ?? [];
}
