/**
 * SPEC-BUDDY-FINANCIAL-ENGINE-ELITE-1 — PR 7: Product Intelligence Framework.
 *
 * Required document type keys per product. Pure data. Consumed by the
 * missing-data blocker system. Document keys are stable identifiers (not
 * canonical-type strings) the blocker system matches case-insensitively.
 */

import type { ProductKey } from "@/lib/finengine/registry/productMetricRegistry";

const COMMON_BUSINESS = ["BUSINESS_TAX_RETURN", "INTERIM_FINANCIAL_STATEMENT", "DEBT_SCHEDULE"];
const COMMON_GUARANTOR = ["PERSONAL_TAX_RETURN", "PERSONAL_FINANCIAL_STATEMENT"];

export const REQUIRED_DOCUMENTS_BY_PRODUCT: Record<ProductKey, readonly string[]> = {
  CI_TERM: [...COMMON_BUSINESS, ...COMMON_GUARANTOR],
  WORKING_CAPITAL_LINE: [...COMMON_BUSINESS, ...COMMON_GUARANTOR, "AR_AGING", "AP_AGING"],
  AR_REVOLVER: [...COMMON_BUSINESS, ...COMMON_GUARANTOR, "AR_AGING", "BORROWING_BASE_CERTIFICATE"],
  ABL_REVOLVER: [...COMMON_BUSINESS, ...COMMON_GUARANTOR, "AR_AGING", "INVENTORY_REPORT", "BORROWING_BASE_CERTIFICATE"],
  EQUIPMENT: [...COMMON_BUSINESS, ...COMMON_GUARANTOR, "EQUIPMENT_QUOTE_INVOICE"],
  CRE_OWNER_OCCUPIED: [...COMMON_BUSINESS, ...COMMON_GUARANTOR, "APPRAISAL", "RENT_ROLL", "ENVIRONMENTAL_REPORT"],
  CRE_INVESTOR: [...COMMON_GUARANTOR, "APPRAISAL", "RENT_ROLL", "OPERATING_STATEMENT", "LEASE_ABSTRACTS", "ENVIRONMENTAL_REPORT"],
  CONSTRUCTION: [...COMMON_BUSINESS, ...COMMON_GUARANTOR, "APPRAISAL", "SOURCES_AND_USES", "CONSTRUCTION_BUDGET", "PLANS_AND_SPECS", "CONTRACTOR_AGREEMENT"],
  SBA_7A: [...COMMON_BUSINESS, ...COMMON_GUARANTOR, "SBA_1919", "SBA_912", "USE_OF_PROCEEDS", "BUSINESS_PLAN"],
  SBA_504: [...COMMON_BUSINESS, ...COMMON_GUARANTOR, "APPRAISAL", "SOURCES_AND_USES", "USE_OF_PROCEEDS"],
  BUSINESS_ACQUISITION: [...COMMON_BUSINESS, ...COMMON_GUARANTOR, "PURCHASE_AGREEMENT", "TARGET_FINANCIALS", "BUSINESS_VALUATION"],
  FRANCHISE: [...COMMON_BUSINESS, ...COMMON_GUARANTOR, "FRANCHISE_DISCLOSURE_DOCUMENT", "FRANCHISE_AGREEMENT"],
  GUIDANCE_LINE: [...COMMON_BUSINESS, ...COMMON_GUARANTOR],
  RENEWAL_MODIFICATION: [...COMMON_BUSINESS, ...COMMON_GUARANTOR, "EXISTING_NOTE", "PAYMENT_HISTORY"],
};

export function requiredDocumentsForProduct(product: ProductKey): readonly string[] {
  return REQUIRED_DOCUMENTS_BY_PRODUCT[product] ?? [];
}
