import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mockServerOnly } from "../../../../test/utils/mockServerOnly";
mockServerOnly();
const require = createRequire(import.meta.url);
const m = require("../alerting") as typeof import("../alerting");
type Row = Record<string, any>;
class S { tables:Record<string,Row[]>; constructor(i?:Partial<Record<string,Row[]>>){this.tables={brokerage_alerts:[],brokerage_alert_events:[],...i};} from(t:string){return new Q(this,t);} }
class Q { db:S;table:string;filters:Array<{t:string;k:string;v:any}>;_u:Row|null;_i:Row[]|null;_l:number|null;_ord:{key:string;asc:boolean}|null; constructor(db:S,t:string){this.db=db;this.table=t;this.filters=[];this._u=null;this._i=null;this._l=null;this._ord=null;} select(_?:string){return this;} order(k:string,o?:{ascending?:boolean}){this._ord={key:k,asc:o?.ascending!==false};return this;} limit(n:number){this._l=n;return this;} eq(k:string,v:any){this.filters.push({t:"eq",k,v});return this;} in(k:string,v:any[]){this.filters.push({t:"in",k,v});return this;} insert(p:Row|Row[]){const rows=Array.isArray(p)?p:[p];const wi=rows.map(r=>({id:r.id??`id-${Math.random().toString(36).slice(2,8)}`,...r}));this.db.tables[this.table]??=[];this.db.tables[this.table].push(...wi);this._i=wi;return this;} update(u:Row){this._u=u;return this;} single():Promise<{data:any;error:any}>{if(this._i)return Promise.resolve({data:this._i[0],error:null});return Promise.resolve({data:this.rows()[0]??null,error:null});} maybeSingle():Promise<{data:any;error:any}>{if(this._u){for(const r of this.rows())Object.assign(r,this._u);return Promise.resolve({data:this.rows()[0],error:null});}return Promise.resolve({data:this.rows()[0]??null,error:null});} then(f:any,r?:any){if(this._u){for(const row of this.rows())Object.assign(row,this._u);return Promise.resolve({data:this.rows(),error:null}).then(f,r);}if(this._i)return Promise.resolve({data:this._i,error:null}).then(f,r);return Promise.resolve({data:this.rows(),error:null}).then(f,r);} private rows(){let rows=[...(this.db.tables[this.table]??[])];for(const f of this.filters){if(f.t==="eq")rows=rows.filter(r=>r[f.k]===f.v);else if(f.t==="in")rows=rows.filter(r=>(f.v as any[]).includes(r[f.k]));}if(this._ord){const{key,asc}=this._ord;rows.sort((a,b)=>a[key]===b[key]?0:a[key]>b[key]?(asc?1:-1):asc?-1:1);}if(this._l!=null)rows=rows.slice(0,this._l);return rows;} }
test("upsert creates",async()=>{const db=new S();const r=await m.upsertAlert({alertKey:"k1",source:"t",severity:"critical",title:"T",message:"M",action:"A"},db as any);assert.equal(r.created,true);assert.equal(db.tables.brokerage_alerts.length,1);});
test("upsert deduplicates",async()=>{const db=new S();const r1=await m.upsertAlert({alertKey:"k1",source:"t",severity:"warning",title:"T",message:"M",action:"A"},db as any);const r2=await m.upsertAlert({alertKey:"k1",source:"t",severity:"warning",title:"T",message:"M2",action:"A"},db as any);assert.equal(r1.id,r2.id);assert.equal(r2.created,false);assert.equal(db.tables.brokerage_alerts[0].occurrence_count,2);});
test("resolve",async()=>{const db=new S();const{id}=await m.upsertAlert({alertKey:"k1",source:"t",severity:"critical",title:"T",message:"M",action:"A"},db as any);await m.resolveAlert(id,{scope:"ops"},db as any);assert.equal(db.tables.brokerage_alerts[0].status,"resolved");});
test("suppress",async()=>{const db=new S();const{id}=await m.upsertAlert({alertKey:"k1",source:"t",severity:"warning",title:"T",message:"M",action:"A"},db as any);await m.suppressAlert(id,24,{scope:"ops"},db as any);assert.equal(db.tables.brokerage_alerts[0].status,"suppressed");});
test("list active only",async()=>{const db=new S({brokerage_alerts:[{id:"a1",alert_key:"k1",source:"s",severity:"critical",status:"active",title:"T",message:"M",action:"A",first_seen_at:new Date().toISOString(),last_seen_at:new Date().toISOString(),occurrence_count:1},{id:"a2",alert_key:"k2",source:"s",severity:"warning",status:"resolved",title:"T2",message:"M2",action:"A2",first_seen_at:new Date().toISOString(),last_seen_at:new Date().toISOString(),occurrence_count:1}]});assert.equal((await m.listActiveAlerts(db as any)).length,1);});
test("generate from report",async()=>{const db=new S();const r=await m.generateBrokerageAlerts({status:"RED",date:"2026-07-15",criticalActions:[{severity:"critical",category:"intake",message:"2 score failures",action:"Retry"}],followups:[{severity:"followup",category:"marketplace",message:"1 zero-claim",action:"Contact"}],borrower:{} as any,marketplace:{} as any,closing:{} as any,revenue:{} as any,compliance:{} as any,launchGateSummary:null,elapsed:1},db as any);assert.equal(r.created,2);});
test("auto-resolve stale",async()=>{const db=new S({brokerage_alerts:[{id:"stale",alert_key:"stale:old",source:"t",severity:"warning",status:"active",title:"Old",message:"Gone",action:"None",first_seen_at:new Date().toISOString(),last_seen_at:new Date().toISOString(),occurrence_count:3}]});await m.generateBrokerageAlerts({status:"GREEN",date:"2026-07-15",criticalActions:[],followups:[],borrower:{} as any,marketplace:{} as any,closing:{} as any,revenue:{} as any,compliance:{} as any,launchGateSummary:null,elapsed:1},db as any);assert.equal(db.tables.brokerage_alerts[0].status,"resolved");});
test("digest",async()=>{const db=new S({brokerage_alerts:[{id:"a1",alert_key:"k1",source:"s",severity:"critical",status:"active",title:"Crit",message:"Bad",action:"Fix",first_seen_at:new Date().toISOString(),last_seen_at:new Date().toISOString(),occurrence_count:1}]});const d=await m.buildAlertDigest(db as any);assert.equal(d.activeCritical.length,1);assert.ok(d.digestText.includes("CRITICAL"));});
