import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const m = require("../borrowerComms") as typeof import("../borrowerComms");
type Row = Record<string, any>;
class S { tables:Record<string,Row[]>; constructor(i?:Partial<Record<string,Row[]>>){this.tables={brokerage_borrower_message_templates:[],brokerage_borrower_message_outbox:[],deals:[],borrower_concierge_sessions:[],...i};} from(t:string){return new Q(this,t);} }
class Q { db:S;table:string;filters:Array<{t:string;k:string;v:any}>;_u:Row|null;_i:Row[]|null;_l:number|null;_ord:{key:string;asc:boolean}|null; constructor(db:S,t:string){this.db=db;this.table=t;this.filters=[];this._u=null;this._i=null;this._l=null;this._ord=null;} select(_?:string){return this;} order(k:string,o?:{ascending?:boolean}){this._ord={key:k,asc:o?.ascending!==false};return this;} limit(n:number){this._l=n;return this;} eq(k:string,v:any){this.filters.push({t:"eq",k,v});return this;} in(k:string,v:any[]){this.filters.push({t:"in",k,v});return this;} insert(p:Row|Row[]){const rows=Array.isArray(p)?p:[p];const wi=rows.map(r=>({id:r.id??`id-${Math.random().toString(36).slice(2,8)}`,...r}));this.db.tables[this.table]??=[];this.db.tables[this.table].push(...wi);this._i=wi;return this;} update(u:Row){this._u=u;return this;} single():Promise<{data:any;error:any}>{if(this._i)return Promise.resolve({data:this._i[0],error:null});return Promise.resolve({data:this.rows()[0]??null,error:null});} maybeSingle():Promise<{data:any;error:any}>{if(this._u){for(const r of this.rows())Object.assign(r,this._u);return Promise.resolve({data:this.rows()[0],error:null});}return Promise.resolve({data:this.rows()[0]??null,error:null});} then(f:any,r?:any){if(this._u){for(const row of this.rows())Object.assign(row,this._u);return Promise.resolve({data:this.rows(),error:null}).then(f,r);}if(this._i)return Promise.resolve({data:this._i,error:null}).then(f,r);return Promise.resolve({data:this.rows(),error:null}).then(f,r);} private rows(){let rows=[...(this.db.tables[this.table]??[])];for(const f of this.filters){if(f.t==="eq")rows=rows.filter(r=>r[f.k]===f.v);else if(f.t==="in")rows=rows.filter(r=>(f.v as any[]).includes(r[f.k]));}if(this._ord){const{key,asc}=this._ord;rows.sort((a,b)=>a[key]===b[key]?0:a[key]>b[key]?(asc?1:-1):asc?-1:1);}if(this._l!=null)rows=rows.slice(0,this._l);return rows;} }
function db(email?:string){return new S({deals:[{id:"d1",borrower_email:email??"b@t.com"}],borrower_concierge_sessions:[{deal_id:"d1",extracted_facts:{borrower:{phone:null}}}]});}
test("welcome queued",async()=>{const d=db();const r=await m.queueBorrowerMessage("session_started","d1","in_portal",d as any);assert.equal(r.ok,true);if(r.ok)assert.equal(r.suppressed,false);assert.ok(d.tables.brokerage_borrower_message_outbox[0].body.includes("Welcome"));});
test("uploads msg",async()=>{const msg=await m.buildBorrowerMessage("uploads_needed","d1",db() as any);assert.ok(msg.body.toLowerCase().includes("document"));});
test("disclosure no guarantee",async()=>{const msg=await m.buildBorrowerMessage("disclosure_ack_needed","d1",db() as any);assert.ok(msg.body.toLowerCase().includes("does not guarantee")||msg.body.toLowerCase().includes("disclosure"));});
test("claim no internals",async()=>{const msg=await m.buildBorrowerMessage("lender_claim_received","d1",db() as any);assert.ok(!msg.body.includes("bank_id"));});
test("pick cta",async()=>{const msg=await m.buildBorrowerMessage("borrower_pick_needed","d1",db() as any);assert.ok(msg.body.toLowerCase().includes("portal")||msg.body.toLowerCase().includes("select")||msg.body.toLowerCase().includes("visit"));});
test("condition msg",async()=>{const msg=await m.buildBorrowerMessage("condition_opened","d1",db() as any);assert.ok(msg.body.toLowerCase().includes("condition"));});
test("funded msg",async()=>{const msg=await m.buildBorrowerMessage("funded","d1",db() as any);assert.ok(msg.body.toLowerCase().includes("funded")||msg.body.toLowerCase().includes("congratulations"));});
test("sms no opt-in",async()=>{const r=await m.queueBorrowerMessage("package_sealed","d1","sms",db() as any);assert.equal(r.ok,true);if(r.ok)assert.equal(r.suppressed,true);});
test("cooldown dedup",async()=>{const d=db();const r1=await m.queueBorrowerMessage("upload_received","d1","in_portal",d as any);const r2=await m.queueBorrowerMessage("upload_received","d1","in_portal",d as any);if(r1.ok)assert.equal(r1.suppressed,false);if(r2.ok)assert.equal(r2.suppressed,true);assert.equal(d.tables.brokerage_borrower_message_outbox.length,1);});
test("strip secrets",async()=>{const d=new S({brokerage_borrower_message_templates:[{trigger_key:"test_s",channel:"email",active:true,body_md:"token_hash rawToken password"}],deals:[{id:"d1",borrower_email:"t@t.com"}],borrower_concierge_sessions:[]});const msg=await m.buildBorrowerMessage("test_s","d1",d as any);assert.ok(!msg.body.includes("token_hash"));assert.ok(msg.body.includes("[REDACTED]"));});
test("in_portal always",async()=>{const d=new S({deals:[{id:"d1",borrower_email:null}],borrower_concierge_sessions:[]});const r=await m.queueBorrowerMessage("session_started","d1","in_portal",d as any);assert.equal(r.ok,true);if(r.ok)assert.equal(r.suppressed,false);assert.equal(d.tables.brokerage_borrower_message_outbox[0].status,"sent");});
test("adapter failure",async()=>{const d=db();await m.queueBorrowerMessage("package_sealed","d1","email",d as any);const oid=d.tables.brokerage_borrower_message_outbox[0].id;const r=await m.sendBorrowerMessage(oid,async()=>({ok:false,error:"smtp"}),d as any);assert.equal(r.ok,false);assert.equal(d.tables.brokerage_borrower_message_outbox[0].status,"failed");});
test("triggers complete",()=>{assert.ok(m.TRIGGER_KEYS.includes("session_started"));assert.ok(m.TRIGGER_KEYS.includes("funded"));assert.ok(m.TRIGGER_KEYS.length>=15);});
test("portal notification",()=>{const n=m.buildPortalNotification("lender_selected","d1");assert.ok(n.message.length>0);assert.ok(n.portalHref.startsWith("/portal"));});
