import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mockServerOnly } from "../../../../test/utils/mockServerOnly";
mockServerOnly();
const require = createRequire(import.meta.url);
const m = require("../businessReadinessGate") as typeof import("../businessReadinessGate");
test("golden run category", () => { assert.equal(m.checkGoldenRunStructure().category,"transaction_flow"); });
test("integrity category", () => { assert.equal(m.checkIntegritySweepStructure().category,"transaction_flow"); });
test("race category", () => { assert.equal(m.checkRaceHarnessStructure().category,"transaction_flow"); });
test("security pass", () => { const r=m.runSecurityGate(); assert.equal(r.category,"security"); assert.equal(r.critical,0); });
test("security detects PII", () => { const r=m.runSecurityGate({listings:[{id:"l1",deal_id:"d1",status:"claiming",kfs:{borrowerName:"J"}}],deals:[{id:"d1",borrower_name:"J"}]}); assert.ok(r.critical>0); });
test("build skip", () => { assert.equal(m.checkBuildStatus({skip:true}).status,"skip"); });
test("build run", () => { assert.ok(["pass","warn"].includes(m.checkBuildStatus().status)); });
test("migrations", () => { assert.ok(["pass","warn"].includes(m.checkMigrationPresence().status)); });
test("env vars", () => { assert.ok(["pass","warn","fail"].includes(m.checkEnvVars().status)); });
test("scripts", () => { assert.equal(m.checkRequiredScripts().category,"operations"); });
test("ops cockpit", () => { assert.equal(m.checkOpsCockpitStructure().category,"operations"); });
test("schema skip", async () => { assert.equal((await m.checkSchemaPresence()).status,"skip"); });
test("schema mock", async () => { const sb={from:()=>({select:()=>({limit:()=>Promise.resolve({error:null})})})}; assert.equal((await m.checkSchemaPresence({sb})).status,"pass"); });
test("legal both", () => { assert.equal(m.checkLegalTemplates({legalDocuments:[{document_type:"borrower_engagement_letter",status:"active"},{document_type:"lender_marketplace_agreement",status:"active"}]}).warning,0); });
test("legal missing", () => { assert.equal(m.checkLegalTemplates({legalDocuments:[{document_type:"lender_marketplace_agreement",status:"active"}]}).warning,1); });
test("legal draft", () => { assert.equal(m.checkLegalTemplates({legalDocuments:[{document_type:"borrower_engagement_letter",status:"draft"},{document_type:"lender_marketplace_agreement",status:"draft"}]}).warning,2); });
test("form159 template", () => { assert.equal(m.checkForm159({legalDocuments:[{document_type:"form_159",status:"active"}]}).status,"pass"); });
test("form159 missing", () => { assert.ok(["pass","fail"].includes(m.checkForm159({legalDocuments:[]}).status)); });
test("fee bps all", () => { assert.equal(m.checkReferralFeeBps({agreements:[{lender_bank_id:"b1",status:"active",referral_fee_bps:100}]}).warning,0); });
test("fee bps null", () => { assert.equal(m.checkReferralFeeBps({agreements:[{lender_bank_id:"b1",status:"active",referral_fee_bps:null}]}).warning,1); });
test("fee bps zero", () => { assert.equal(m.checkReferralFeeBps({agreements:[{lender_bank_id:"b1",status:"active",referral_fee_bps:0}]}).warning,1); });
test("fee bps none", () => { assert.equal(m.checkReferralFeeBps({agreements:[]}).warning,1); });
test("access traced", () => { assert.equal(m.checkPackageAccessTraceability({accesses:[{id:"a1",claim_id:"c1"}],picks:[{id:"p1",claim_id:"c1",status:"picked"}]}).critical,0); });
test("access untraceable", () => { assert.equal(m.checkPackageAccessTraceability({accesses:[{id:"a1",claim_id:"cX"}],picks:[{id:"p1",claim_id:"c1",status:"picked"}]}).critical,1); });
test("packaging fee", () => { assert.ok(["pass","warn"].includes(m.checkPackagingFeeConfig().status)); });
test("referral disclosure", () => { assert.ok(["pass","warn"].includes(m.checkReferralFeeDisclosure().status)); });
test("full runner", async () => { const r=await m.runBusinessReadinessGate({skipBuild:true,skipGolden:true}); assert.ok(["READY","NOT_READY"].includes(r.overall)); assert.ok(r.gates.length>=18); for (const g of r.gates) { assert.ok(g.name); assert.ok(g.category); assert.ok(["pass","fail","skip","warn"].includes(g.status)); } });
test("strict mode", async () => { const r=await m.runBusinessReadinessGate({skipBuild:true,skipGolden:true,strict:true}); if (r.warning>0) assert.equal(r.overall,"NOT_READY"); });
test("skip flags", async () => { const r=await m.runBusinessReadinessGate({skipBuild:true,skipGolden:true}); assert.equal(r.gates.find(g=>g.name==="build_typecheck")?.status,"skip"); assert.equal(r.gates.find(g=>g.name==="golden_run_structure")?.status,"skip"); });
test("backward compat", async () => { const { runReadinessGate } = require("../readinessGate") as typeof import("../readinessGate"); const r=await runReadinessGate({skipBuild:true,skipGolden:true}); assert.ok(["READY","NOT_READY"].includes(r.overall)); });
