import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const m = require("../closingCoordination") as typeof import("../closingCoordination");
type Row = Record<string, any>;
class S { tables:Record<string,Row[]>; constructor(i?:Partial<Record<string,Row[]>>){this.tables={marketplace_picks:[],brokerage_closing_workflows:[],brokerage_closing_conditions:[],brokerage_condition_evidence:[],brokerage_closing_events:[],brokerage_fee_ledger:[],deal_documents:[],...i};} from(t:string){return new Q(this,t);} }
class Q { db:S;table:string;filters:Array<{t:string;k:string;v:any}>;_u:Row|null;_i:Row[]|null;_l:number|null; constructor(db:S,t:string){this.db=db;this.table=t;this.filters=[];this._u=null;this._i=null;this._l=null;} select(_?:string){return this;} order(_k:string,_o?:any){return this;} limit(n:number){this._l=n;return this;} eq(k:string,v:any){this.filters.push({t:"eq",k,v});return this;} in(k:string,v:any[]){this.filters.push({t:"in",k,v});return this;} is(k:string,v:any){this.filters.push({t:"is",k,v});return this;} insert(p:Row|Row[]){const rows=Array.isArray(p)?p:[p];const wi=rows.map(r=>({id:r.id??`id-${Math.random().toString(36).slice(2,8)}`,...r}));this.db.tables[this.table]??=[];this.db.tables[this.table].push(...wi);this._i=wi;return this;} update(u:Row){this._u=u;return this;} single():Promise<{data:any;error:any}>{if(this._i)return Promise.resolve({data:this._i[0],error:null});return Promise.resolve({data:this.rows()[0]??null,error:null});} maybeSingle():Promise<{data:any;error:any}>{if(this._u){for(const r of this.rows())Object.assign(r,this._u);return Promise.resolve({data:this.rows()[0],error:null});}return Promise.resolve({data:this.rows()[0]??null,error:null});} then(f:any,r?:any){if(this._u){for(const row of this.rows())Object.assign(row,this._u);return Promise.resolve({data:this.rows(),error:null}).then(f,r);}if(this._i)return Promise.resolve({data:this._i,error:null}).then(f,r);return Promise.resolve({data:this.rows(),error:null}).then(f,r);} private rows(){let rows=[...(this.db.tables[this.table]??[])];for(const f of this.filters){if(f.t==="eq")rows=rows.filter(r=>r[f.k]===f.v);else if(f.t==="in")rows=rows.filter(r=>(f.v as any[]).includes(r[f.k]));else if(f.t==="is")rows=rows.filter(r=>{const v=r[f.k];return f.v===null?v==null:v===f.v;});}if(this._l!=null)rows=rows.slice(0,this._l);return rows;} }
function pdb(){return new S({marketplace_picks:[{deal_id:"d1",claim_id:"c1",listing_id:"l1",picked_lender_bank_id:"b1",status:"picked"}]});}
test("open workflow idempotent",async()=>{const db=pdb();const r1=await m.openClosingWorkflowForPickedLender("d1","c1",db as any);assert.equal(r1.ok,true);if(r1.ok)assert.equal(r1.created,true);const r2=await m.openClosingWorkflowForPickedLender("d1","c1",db as any);if(r2.ok)assert.equal(r2.created,false);assert.equal(db.tables.brokerage_closing_workflows.length,1);});
test("seed conditions once",async()=>{const db=pdb();const{workflowId}=(await m.openClosingWorkflowForPickedLender("d1","c1",db as any)) as any;const s1=await m.seedDefaultClosingConditions(workflowId,"d1",db as any);assert.ok(s1.seeded>=8);const s2=await m.seedDefaultClosingConditions(workflowId,"d1",db as any);assert.equal(s2.seeded,0);});
test("lender adds condition",async()=>{const db=pdb();const{workflowId}=(await m.openClosingWorkflowForPickedLender("d1","c1",db as any)) as any;const r=await m.addLenderCondition(workflowId,"b1",{title:"Rent roll"},db as any);assert.equal(r.ok,true);assert.equal(db.tables.brokerage_closing_conditions.filter(c=>c.source==="lender").length,1);});
test("wrong lender blocked",async()=>{const db=pdb();const{workflowId}=(await m.openClosingWorkflowForPickedLender("d1","c1",db as any)) as any;const r=await m.addLenderCondition(workflowId,"bX",{title:"X"},db as any);assert.equal(r.ok,false);});
test("submit evidence",async()=>{const db=pdb();db.tables.deal_documents=[{id:"doc1",deal_id:"d1"}];const{workflowId}=(await m.openClosingWorkflowForPickedLender("d1","c1",db as any)) as any;await m.seedDefaultClosingConditions(workflowId,"d1",db as any);const cid=db.tables.brokerage_closing_conditions[0].id;const r=await m.submitConditionEvidence(cid,"doc1",{scope:"borrower"},db as any);assert.equal(r.ok,true);assert.equal(db.tables.brokerage_closing_conditions[0].status,"submitted");});
test("wrong deal doc rejected",async()=>{const db=pdb();db.tables.deal_documents=[{id:"doc1",deal_id:"dX"}];const{workflowId}=(await m.openClosingWorkflowForPickedLender("d1","c1",db as any)) as any;await m.seedDefaultClosingConditions(workflowId,"d1",db as any);const r=await m.submitConditionEvidence(db.tables.brokerage_closing_conditions[0].id,"doc1",{scope:"borrower"},db as any);assert.equal(r.ok,false);});
test("condition satisfied",async()=>{const db=pdb();const{workflowId}=(await m.openClosingWorkflowForPickedLender("d1","c1",db as any)) as any;await m.seedDefaultClosingConditions(workflowId,"d1",db as any);const r=await m.markConditionSatisfied(db.tables.brokerage_closing_conditions[0].id,{scope:"brokerage_ops"},db as any);assert.equal(r.ok,true);assert.equal(db.tables.brokerage_closing_conditions[0].status,"satisfied");});
test("condition waived",async()=>{const db=pdb();const{workflowId}=(await m.openClosingWorkflowForPickedLender("d1","c1",db as any)) as any;await m.seedDefaultClosingConditions(workflowId,"d1",db as any);await m.waiveCondition(db.tables.brokerage_closing_conditions[1].id,{scope:"lender"},db as any);assert.equal(db.tables.brokerage_closing_conditions[1].status,"waived");});
test("readiness false open",async()=>{const db=pdb();const{workflowId}=(await m.openClosingWorkflowForPickedLender("d1","c1",db as any)) as any;await m.seedDefaultClosingConditions(workflowId,"d1",db as any);const rd=await m.computeClosingReadiness(workflowId,db as any);assert.equal(rd.ready,false);assert.ok(rd.openConditions>0);});
test("readiness true all satisfied",async()=>{const db=pdb();const{workflowId}=(await m.openClosingWorkflowForPickedLender("d1","c1",db as any)) as any;await m.seedDefaultClosingConditions(workflowId,"d1",db as any);for(const c of db.tables.brokerage_closing_conditions) await m.markConditionSatisfied(c.id,{scope:"ops"},db as any);const rd=await m.computeClosingReadiness(workflowId,db as any);assert.equal(rd.ready,true);});
test("clear to close blocked",async()=>{const db=pdb();const{workflowId}=(await m.openClosingWorkflowForPickedLender("d1","c1",db as any)) as any;await m.seedDefaultClosingConditions(workflowId,"d1",db as any);const r1=await m.markClearToClose(workflowId,db as any);assert.equal(r1.ok,false);for(const c of db.tables.brokerage_closing_conditions) await m.markConditionSatisfied(c.id,{scope:"ops"},db as any);const r2=await m.markClearToClose(workflowId,db as any);assert.equal(r2.ok,true);});
test("funded updates fees",async()=>{const db=pdb();db.tables.brokerage_fee_ledger=[{deal_id:"d1",fee_type:"borrower_packaging",status:"disclosed"},{deal_id:"d1",fee_type:"lender_referral",status:"estimated"}];const{workflowId}=(await m.openClosingWorkflowForPickedLender("d1","c1",db as any)) as any;await m.seedDefaultClosingConditions(workflowId,"d1",db as any);for(const c of db.tables.brokerage_closing_conditions) await m.markConditionSatisfied(c.id,{scope:"ops"},db as any);await m.markClearToClose(workflowId,db as any);await m.markFunded(workflowId,{date:"2026-07-01"},db as any);assert.equal(db.tables.brokerage_closing_workflows[0].status,"funded");for(const f of db.tables.brokerage_fee_ledger)assert.equal(f.status,"funded");});
test("events audited",async()=>{const db=pdb();const{workflowId}=(await m.openClosingWorkflowForPickedLender("d1","c1",db as any)) as any;await m.seedDefaultClosingConditions(workflowId,"d1",db as any);const cid=db.tables.brokerage_closing_conditions[0].id;await m.submitConditionEvidence(cid,null,{scope:"borrower"},db as any);await m.markConditionSatisfied(cid,{scope:"ops"},db as any);const types=db.tables.brokerage_closing_events.map(e=>e.event_type);assert.ok(types.includes("workflow_opened"));assert.ok(types.includes("conditions_seeded"));assert.ok(types.includes("evidence_submitted"));assert.ok(types.includes("condition_satisfied"));});
