import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const m = require("../complianceEnforcement") as typeof import("../complianceEnforcement");
type Row = Record<string, any>;
class S { tables:Record<string,Row[]>; constructor(i?:Partial<Record<string,Row[]>>){this.tables={brokerage_disclosures:[],brokerage_fee_ledger:[],sba_form_159_records:[],buddy_sealed_packages:[],marketplace_claims:[],lender_marketplace_agreements:[],...i};} from(t:string){return new Q(this,t);} }
class Q { db:S;table:string;filters:Array<{t:string;k:string;v:any}>;_u:Row|null;_i:Row[]|null;_l:number|null; constructor(db:S,t:string){this.db=db;this.table=t;this.filters=[];this._u=null;this._i=null;this._l=null;} select(_?:string){return this;} order(_k:string,_o?:any){return this;} limit(n:number){this._l=n;return this;} eq(k:string,v:any){this.filters.push({t:"eq",k,v});return this;} in(k:string,v:any[]){this.filters.push({t:"in",k,v});return this;} is(k:string,v:any){this.filters.push({t:"is",k,v});return this;} insert(p:Row|Row[]){const rows=Array.isArray(p)?p:[p];const wi=rows.map(r=>({id:r.id??`id-${Math.random().toString(36).slice(2,8)}`,...r}));this.db.tables[this.table]??=[];this.db.tables[this.table].push(...wi);this._i=wi;return this;} update(u:Row){this._u=u;return this;} single():Promise<{data:any;error:any}>{if(this._i)return Promise.resolve({data:this._i[0],error:null});return Promise.resolve({data:this.rows()[0]??null,error:null});} maybeSingle():Promise<{data:any;error:any}>{if(this._u){for(const r of this.rows())Object.assign(r,this._u);return Promise.resolve({data:this.rows()[0],error:null});}return Promise.resolve({data:this.rows()[0]??null,error:null});} then(f:any,r?:any){if(this._u){for(const row of this.rows())Object.assign(row,this._u);return Promise.resolve({data:this.rows(),error:null}).then(f,r);}if(this._i)return Promise.resolve({data:this._i,error:null}).then(f,r);return Promise.resolve({data:this.rows(),error:null}).then(f,r);} private rows(){let rows=[...(this.db.tables[this.table]??[])];for(const f of this.filters){if(f.t==="eq")rows=rows.filter(r=>r[f.k]===f.v);else if(f.t==="in")rows=rows.filter(r=>(f.v as any[]).includes(r[f.k]));else if(f.t==="is")rows=rows.filter(r=>{const v=r[f.k];return f.v===null?v==null:v===f.v;});}if(this._l!=null)rows=rows.slice(0,this._l);return rows;} }
function sealReady(){return new S({brokerage_disclosures:[{deal_id:"d1",disclosure_type:"borrower_engagement_letter",status:"acknowledged"},{deal_id:"d1",disclosure_type:"fee_disclosure",status:"acknowledged"}],brokerage_fee_ledger:[{deal_id:"d1",fee_type:"borrower_packaging",status:"disclosed"}],sba_form_159_records:[{id:"f1",deal_id:"d1",status:"generated"}]});}
test("seal no engagement",async()=>{const r=await m.assertCanSealBrokeragePackage("d1",new S({brokerage_disclosures:[{deal_id:"d1",disclosure_type:"fee_disclosure",status:"acknowledged"}],brokerage_fee_ledger:[{deal_id:"d1",fee_type:"borrower_packaging",status:"disclosed"}],sba_form_159_records:[{deal_id:"d1",status:"generated"}]}) as any); assert.equal(r.ok,false); assert.ok((r as any).blockers.some((b:any)=>b.code==="missing_engagement_ack"));});
test("seal no fee disc",async()=>{const r=await m.assertCanSealBrokeragePackage("d1",new S({brokerage_disclosures:[{deal_id:"d1",disclosure_type:"borrower_engagement_letter",status:"acknowledged"}],brokerage_fee_ledger:[{deal_id:"d1",fee_type:"borrower_packaging",status:"disclosed"}],sba_form_159_records:[{deal_id:"d1",status:"generated"}]}) as any); assert.equal(r.ok,false); assert.ok((r as any).blockers.some((b:any)=>b.code==="missing_fee_disclosure_ack"));});
test("seal no 159",async()=>{const r=await m.assertCanSealBrokeragePackage("d1",new S({brokerage_disclosures:[{deal_id:"d1",disclosure_type:"borrower_engagement_letter",status:"acknowledged"},{deal_id:"d1",disclosure_type:"fee_disclosure",status:"acknowledged"}],brokerage_fee_ledger:[{deal_id:"d1",fee_type:"borrower_packaging",status:"disclosed"}]}) as any); assert.ok((r as any).blockers?.some((b:any)=>b.code==="missing_form_159"));});
test("seal passes",async()=>{const r=await m.assertCanSealBrokeragePackage("d1",sealReady() as any); assert.equal(r.ok,true);});
test("two-masters required",async()=>{const r=await m.assertCanSealBrokeragePackage("d1",new S({brokerage_disclosures:[{deal_id:"d1",disclosure_type:"borrower_engagement_letter",status:"acknowledged"},{deal_id:"d1",disclosure_type:"fee_disclosure",status:"acknowledged"}],brokerage_fee_ledger:[{deal_id:"d1",fee_type:"borrower_packaging",status:"disclosed"},{deal_id:"d1",fee_type:"lender_referral",status:"estimated"}],sba_form_159_records:[{deal_id:"d1",status:"generated"}]}) as any); assert.ok((r as any).blockers?.some((b:any)=>b.code==="missing_two_masters_consent"));});
test("unlock no agreement",async()=>{const r=await m.assertCanUnlockBrokeragePackage("d1","b1","c1",new S({buddy_sealed_packages:[{id:"sp1",deal_id:"d1",unsealed_at:null}],marketplace_claims:[{id:"c1",status:"picked"}],brokerage_fee_ledger:[{deal_id:"d1",fee_type:"lender_referral",status:"disclosed",disclosed_on_form_159:true}],sba_form_159_records:[{deal_id:"d1",status:"borrower_acknowledged"}]}) as any); assert.ok((r as any).blockers?.some((b:any)=>b.code==="no_active_lender_agreement"));});
test("unlock no fee ledger",async()=>{const r=await m.assertCanUnlockBrokeragePackage("d1","b1","c1",new S({buddy_sealed_packages:[{id:"sp1",deal_id:"d1",unsealed_at:null}],marketplace_claims:[{id:"c1",status:"picked"}],lender_marketplace_agreements:[{lender_bank_id:"b1",status:"active"}],sba_form_159_records:[{deal_id:"d1",status:"borrower_acknowledged"}]}) as any); assert.ok((r as any).blockers?.some((b:any)=>b.code==="missing_lender_fee_ledger"));});
test("unlock fee not disclosed",async()=>{const r=await m.assertCanUnlockBrokeragePackage("d1","b1","c1",new S({buddy_sealed_packages:[{id:"sp1",deal_id:"d1",unsealed_at:null}],marketplace_claims:[{id:"c1",status:"picked"}],lender_marketplace_agreements:[{lender_bank_id:"b1",status:"active"}],brokerage_fee_ledger:[{deal_id:"d1",fee_type:"lender_referral",status:"estimated",disclosed_on_form_159:false}],sba_form_159_records:[{deal_id:"d1",status:"borrower_acknowledged"}]}) as any); assert.ok((r as any).blockers?.some((b:any)=>b.code==="lender_fee_not_disclosed"));});
test("waived not blocks",async()=>{const r=await m.assertCanUnlockBrokeragePackage("d1","b1","c1",new S({buddy_sealed_packages:[{id:"sp1",deal_id:"d1",unsealed_at:null}],marketplace_claims:[{id:"c1",status:"picked"}],lender_marketplace_agreements:[{lender_bank_id:"b1",status:"active"}],brokerage_fee_ledger:[{deal_id:"d1",fee_type:"lender_referral",status:"waived"}],sba_form_159_records:[{deal_id:"d1",status:"borrower_acknowledged"}]}) as any); assert.equal(r.ok,true);});
test("blockers no secrets",async()=>{const bl=await m.buildComplianceBlockers("d1",new S({brokerage_disclosures:[{deal_id:"d1",disclosure_type:"borrower_engagement_letter",status:"presented",borrower_session_token_hash:"secret"}]}) as any); assert.ok(!JSON.stringify(bl).includes("secret")); assert.ok(!JSON.stringify(bl).includes("token_hash"));});
test("ensure f159 lender",async()=>{const db=new S({sba_form_159_records:[{id:"f1",deal_id:"d1",status:"generated",lender_bank_id:null}]}); const r=await m.ensureForm159ForPickedLender("d1","b1",db as any); assert.equal(r.ok,true); assert.equal(db.tables.sba_form_159_records[0].lender_bank_id,"b1");});
test("mark fee disclosed",async()=>{const db=new S({brokerage_fee_ledger:[{deal_id:"d1",fee_type:"lender_referral",status:"estimated",disclosed_on_form_159:false}]}); await m.markLenderFeeDisclosedForUnlock("d1","b1",db as any); assert.equal(db.tables.brokerage_fee_ledger[0].disclosed_on_form_159,true);});
