import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const m = require("../compliancePackage") as typeof import("../compliancePackage");
type Row = Record<string, any>;
class S { tables: Record<string,Row[]>; constructor(i?: Partial<Record<string,Row[]>>) { this.tables = { brokerage_fee_config:[], legal_documents:[], brokerage_disclosures:[], brokerage_fee_ledger:[], sba_form_159_records:[], lender_marketplace_agreements:[], marketplace_picks:[], deals:[], borrower_concierge_sessions:[], ...i }; } from(t: string) { return new Q(this,t); } }
class Q { db:S; table:string; filters:Array<{t:string;k:string;v:any}>; _u:Row|null; _i:Row[]|null; _l:number|null; constructor(db:S,t:string){this.db=db;this.table=t;this.filters=[];this._u=null;this._i=null;this._l=null;} select(_?:string){return this;} order(_k:string,_o?:any){return this;} limit(n:number){this._l=n;return this;} eq(k:string,v:any){this.filters.push({t:"eq",k,v});return this;} in(k:string,v:any[]){this.filters.push({t:"in",k,v});return this;} is(k:string,v:any){this.filters.push({t:"is",k,v});return this;} insert(p:Row|Row[]){const rows=Array.isArray(p)?p:[p];const wi=rows.map(r=>({id:r.id??`id-${Math.random().toString(36).slice(2,8)}`,...r}));this.db.tables[this.table]??=[];this.db.tables[this.table].push(...wi);this._i=wi;return this;} update(u:Row){this._u=u;return this;} single():Promise<{data:any;error:any}>{if(this._i)return Promise.resolve({data:this._i[0],error:null});return Promise.resolve({data:this.rows()[0]??null,error:null});} maybeSingle():Promise<{data:any;error:any}>{if(this._u){this.doU();return Promise.resolve({data:this.rows()[0],error:null});}return Promise.resolve({data:this.rows()[0]??null,error:null});} then(f:any,r?:any){if(this._u){this.doU();return Promise.resolve({data:this.rows(),error:null}).then(f,r);}if(this._i)return Promise.resolve({data:this._i,error:null}).then(f,r);return Promise.resolve({data:this.rows(),error:null}).then(f,r);} private doU(){for(const r of this.rows())Object.assign(r,this._u);} private rows(){let rows=[...(this.db.tables[this.table]??[])];for(const f of this.filters){if(f.t==="eq")rows=rows.filter(r=>r[f.k]===f.v);else if(f.t==="in")rows=rows.filter(r=>(f.v as any[]).includes(r[f.k]));else if(f.t==="is")rows=rows.filter(r=>{const v=r[f.k];return f.v===null?v==null:v===f.v;});}if(this._l!=null)rows=rows.slice(0,this._l);return rows;} }
test("default fee $1000", async () => { const r=await m.getActiveFeeConfig(new S() as any); assert.equal(r.borrowerPackagingFeeCents,100000); });
test("db fee overrides", async () => { const r=await m.getActiveFeeConfig(new S({brokerage_fee_config:[{id:"c1",version:"v2",status:"active",borrower_packaging_fee_cents:200000,borrower_packaging_fee_label:"Premium",lender_referral_fee_min_bps:150,lender_referral_fee_max_bps:250,financed_into_loan_default:false}]}) as any); assert.equal(r.borrowerPackagingFeeCents,200000); });
test("engagement disclosure", async () => { const r=await m.buildBorrowerEngagementDisclosure("d1",new S({legal_documents:[{document_type:"borrower_engagement_letter",status:"active",version:"v1",body_md:"Fee is $1,000."}]}) as any); assert.ok(r.bodyMd.includes("$1,000")); });
test("ack records signer", async () => { const db=new S(); const {id}=await m.presentDisclosure({dealId:"d1",disclosureType:"fee_disclosure",bodyMd:"Fee.",version:"v1",sb:db as any}); await m.acknowledgeDisclosure({disclosureId:id,name:"Jane",email:"j@t.com",sb:db as any}); assert.equal(db.tables.brokerage_disclosures[0].status,"acknowledged"); assert.equal(db.tables.brokerage_disclosures[0].acknowledged_by_name,"Jane"); });
test("fee ledger created", async () => { const {borrowerEntry}=await m.createOrUpdateFeeLedgerForDeal("d1",new S({deals:[{id:"d1",loan_amount:500000}]}) as any); assert.ok(borrowerEntry); assert.equal(borrowerEntry.amount_cents,100000); });
test("lender referral fee", async () => { const r=await m.estimateLenderReferralFee("d1","b1",new S({lender_marketplace_agreements:[{lender_bank_id:"b1",status:"active",referral_fee_bps:150}],deals:[{id:"d1",loan_amount:800000}]}) as any); assert.equal(r.bps,150); assert.equal(r.estimatedCents,1200000); });
test("form 159 preview", async () => { const r=await m.generateForm159Preview("d1",new S({deals:[{id:"d1",loan_amount:500000}],marketplace_picks:[{deal_id:"d1",picked_lender_bank_id:"b1",status:"picked"}],lender_marketplace_agreements:[{lender_bank_id:"b1",status:"active",referral_fee_bps:100}]}) as any); assert.equal(r.borrowerFeeCents,100000); assert.equal(r.status,"generated"); });
test("two-masters required", async () => { const r=await m.assertDealComplianceReady("d1",new S({brokerage_disclosures:[{deal_id:"d1",disclosure_type:"borrower_engagement_letter",status:"acknowledged"},{deal_id:"d1",disclosure_type:"fee_disclosure",status:"acknowledged"}],sba_form_159_records:[{deal_id:"d1",status:"generated"}],brokerage_fee_ledger:[{deal_id:"d1",fee_type:"borrower_packaging",status:"estimated"},{deal_id:"d1",fee_type:"lender_referral",status:"estimated"}]}) as any); assert.equal(r.twoMastersConsentRequired,true); assert.equal(r.complianceReadyToSeal,false); });
test("compliance fails before ack", async () => { const r=await m.assertDealComplianceReady("d1",new S() as any); assert.equal(r.complianceReadyToSeal,false); assert.ok(r.issues.length>=2); });
test("compliance passes", async () => { const r=await m.assertDealComplianceReady("d1",new S({brokerage_disclosures:[{deal_id:"d1",disclosure_type:"borrower_engagement_letter",status:"acknowledged"},{deal_id:"d1",disclosure_type:"fee_disclosure",status:"acknowledged"},{deal_id:"d1",disclosure_type:"two_masters_consent",status:"acknowledged"}],sba_form_159_records:[{deal_id:"d1",status:"generated"}],brokerage_fee_ledger:[{deal_id:"d1",fee_type:"borrower_packaging",status:"disclosed"},{deal_id:"d1",fee_type:"lender_referral",status:"disclosed"}]}) as any); assert.equal(r.complianceReadyToSeal,true); });
test("lock form 159", async () => { const db=new S({sba_form_159_records:[{id:"f1",deal_id:"d1",status:"generated"}]}); const r=await m.lockForm159Record("f1",db as any); assert.equal(r.ok,true); assert.equal(db.tables.sba_form_159_records[0].status,"locked"); });
test("waived not blocks", async () => { const r=await m.assertDealComplianceReady("d1",new S({brokerage_disclosures:[{deal_id:"d1",disclosure_type:"borrower_engagement_letter",status:"acknowledged"},{deal_id:"d1",disclosure_type:"fee_disclosure",status:"acknowledged"}],sba_form_159_records:[{deal_id:"d1",status:"generated"}],brokerage_fee_ledger:[{deal_id:"d1",fee_type:"borrower_packaging",status:"waived"}]}) as any); assert.equal(r.complianceReadyToSeal,true); });
test("no token_hash", async () => { const r=await m.assertDealComplianceReady("d1",new S({brokerage_disclosures:[{deal_id:"d1",disclosure_type:"borrower_engagement_letter",status:"acknowledged",borrower_session_token_hash:"secret"}]}) as any); assert.ok(!JSON.stringify(r).includes("secret")); assert.ok(!JSON.stringify(r).includes("token_hash")); });
