import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const m = require("../conversionFunnel") as typeof import("../conversionFunnel");
type Row = Record<string, any>;
class S { tables:Record<string,Row[]>; constructor(i?:Partial<Record<string,Row[]>>){this.tables={brokerage_leads:[],brokerage_conversion_events:[],deals:[],borrower_session_tokens:[],...i};} from(t:string){return new Q(this,t);} }
class Q { db:S;table:string;filters:Array<{t:string;k:string;v:any}>;_u:Row|null;_i:Row[]|null;_l:number|null;_ord:{key:string;asc:boolean}|null; constructor(db:S,t:string){this.db=db;this.table=t;this.filters=[];this._u=null;this._i=null;this._l=null;this._ord=null;} select(_?:string){return this;} order(k:string,o?:{ascending?:boolean}){this._ord={key:k,asc:o?.ascending!==false};return this;} limit(n:number){this._l=n;return this;} eq(k:string,v:any){this.filters.push({t:"eq",k,v});return this;} insert(p:Row|Row[]){const rows=Array.isArray(p)?p:[p];const wi=rows.map(r=>({id:r.id??`id-${Math.random().toString(36).slice(2,8)}`,...r}));this.db.tables[this.table]??=[];this.db.tables[this.table].push(...wi);this._i=wi;return this;} update(u:Row){this._u=u;return this;} single():Promise<{data:any;error:any}>{if(this._i)return Promise.resolve({data:this._i[0],error:null});return Promise.resolve({data:this.rows()[0]??null,error:null});} maybeSingle():Promise<{data:any;error:any}>{if(this._u){for(const r of this.rows())Object.assign(r,this._u);return Promise.resolve({data:this.rows()[0],error:null});}return Promise.resolve({data:this.rows()[0]??null,error:null});} then(f:any,r?:any){if(this._u){for(const row of this.rows())Object.assign(row,this._u);return Promise.resolve({data:this.rows(),error:null}).then(f,r);}if(this._i)return Promise.resolve({data:this._i,error:null}).then(f,r);return Promise.resolve({data:this.rows(),error:null}).then(f,r);} private rows(){let rows=[...(this.db.tables[this.table]??[])];for(const f of this.filters){if(f.t==="eq")rows=rows.filter(r=>r[f.k]===f.v);}if(this._ord){const{key,asc}=this._ord;rows.sort((a,b)=>a[key]===b[key]?0:a[key]>b[key]?(asc?1:-1):asc?-1:1);}if(this._l!=null)rows=rows.slice(0,this._l);return rows;} }
test("start session",async()=>{const db=new S();const r=await m.startBrokerageSession({brokerageBankId:"brk"},db as any);assert.equal(r.ok,true);if(r.ok){assert.ok(r.dealId);assert.equal(r.tokenHash.length,64);}assert.equal(db.tables.deals.length,1);});
test("token hash only",async()=>{const db=new S();const r=await m.startBrokerageSession({brokerageBankId:"brk"},db as any);if(r.ok){const t=db.tables.borrower_session_tokens[0];assert.ok(t.token_hash);assert.ok(!("raw_token" in t));assert.ok(!("rawToken" in t));}});
test("lead capture",async()=>{const db=new S();const r=await m.captureLead({email:"j@t.com",source:"test"},db as any);assert.equal(r.ok,true);if(r.ok)assert.equal(r.existing,false);assert.equal(db.tables.brokerage_leads.length,1);});
test("lead dedup",async()=>{const db=new S();const r1=await m.captureLead({email:"d@t.com",source:"test"},db as any);const r2=await m.captureLead({email:"d@t.com",source:"test"},db as any);if(r1.ok&&r2.ok){assert.equal(r1.leadId,r2.leadId);assert.equal(r2.existing,true);}assert.equal(db.tables.brokerage_leads.length,1);});
test("lead converts",async()=>{const db=new S();const lr=await m.captureLead({email:"c@t.com",source:"test"},db as any);const sr=await m.startBrokerageSession({brokerageBankId:"brk",leadId:(lr as any).leadId},db as any);assert.equal(db.tables.brokerage_leads[0].status,"converted");assert.equal(db.tables.brokerage_leads[0].converted_deal_id,(sr as any).dealId);});
test("no guarantee language",()=>{const r=m.validatePublicContent();assert.equal(r.ok,true);assert.ok(!m.PUBLIC_COPY.headline.toLowerCase().includes("guaranteed"));});
test("fee $1000",()=>{assert.ok(m.FEE_DISCLOSURE_TEXT.includes("$1,000"));});
test("events logged",async()=>{const db=new S();await m.captureLead({email:"e@t.com",source:"test"},db as any);await m.startBrokerageSession({brokerageBankId:"brk"},db as any);const types=db.tables.brokerage_conversion_events.map(e=>e.event_type);assert.ok(types.includes("lead_captured"));assert.ok(types.includes("session_started"));assert.ok(types.includes("deal_created"));});
test("invalid email rejected",async()=>{const r=await m.captureLead({email:"bad",source:"test"},new S() as any);assert.equal(r.ok,false);});
test("anonymous start ok",async()=>{const db=new S();const r=await m.startBrokerageSession({brokerageBankId:"brk"},db as any);assert.equal(r.ok,true);});
