import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const m = require("../integritySweep") as typeof import("../integritySweep");
test("clean listing no token_hash", () => { assert.equal(m.checkNoTokenHashInPayloads([{id:"l1",kfs:{state:"TX"}}],[]).length, 0); });
test("listing with token_hash", () => { assert.equal(m.checkNoTokenHashInPayloads([{id:"l1",kfs:{token_hash:"x"}}],[]).length, 1); });
test("portal with rawToken", () => { assert.equal(m.checkNoTokenHashInPayloads([],[{deal_id:"d1",rawToken:"x"}]).length, 1); });
test("aligned claim passes", () => { assert.equal(m.checkClaimAlignment([{id:"c1",listing_id:"l1",deal_id:"d1"}],[{id:"l1",deal_id:"d1"}]).length, 0); });
test("misaligned claim", () => { assert.equal(m.checkClaimAlignment([{id:"c1",listing_id:"l1",deal_id:"d2"}],[{id:"l1",deal_id:"d1"}]).length, 1); });
test("orphan claim", () => { assert.ok(m.checkClaimAlignment([{id:"c1",listing_id:"l9",deal_id:"d1"}],[{id:"l1",deal_id:"d1"}])[0].message.includes("non-existent")); });
test("pick alignment pass", () => { assert.equal(m.checkPickAlignment([{id:"p1",listing_id:"l1",deal_id:"d1",claim_id:"c1",picked_lender_bank_id:"b1"}],[{id:"c1",listing_id:"l1",deal_id:"d1",lender_bank_id:"b1"}],[]).length, 0); });
test("pick wrong lender", () => { assert.ok(m.checkPickAlignment([{id:"p1",listing_id:"l1",deal_id:"d1",claim_id:"c1",picked_lender_bank_id:"b2"}],[{id:"c1",listing_id:"l1",deal_id:"d1",lender_bank_id:"b1"}],[]).length > 0); });
test("access picked passes", () => { assert.equal(m.checkAccessAlignment([{id:"a1",claim_id:"c1",deal_id:"d1"}],[{id:"c1",deal_id:"d1",status:"picked"}]).length, 0); });
test("access non-picked", () => { assert.equal(m.checkAccessAlignment([{id:"a1",claim_id:"c1",deal_id:"d1"}],[{id:"c1",deal_id:"d1",status:"active"}]).length, 1); });
test("non-picked no access pass", () => { assert.equal(m.checkNonPickedNoAccess([{id:"a1",claim_id:"c1"}],[{id:"p1",claim_id:"c1",status:"picked"}]).length, 0); });
test("non-picked access", () => { assert.equal(m.checkNonPickedNoAccess([{id:"a1",claim_id:"c2"}],[{id:"p1",claim_id:"c1",status:"picked"}]).length, 1); });
test("clean KFS", () => { assert.equal(m.checkListingKfsRedacted([{id:"l1",status:"claiming",kfs:{state:"TX"}}]).length, 0); });
test("KFS borrowerName", () => { assert.ok(m.checkListingKfsRedacted([{id:"l1",status:"claiming",kfs:{borrowerName:"John"}}]).length > 0); });
test("KFS storage_path", () => { assert.ok(m.checkListingKfsRedacted([{id:"l1",status:"claiming",kfs:{storage_path:"/x"}}]).length > 0); });
test("sealed 1 listing", () => { assert.equal(m.checkSealedListingUniqueness([{id:"sp1",deal_id:"d1"}],[{id:"l1",deal_id:"d1",status:"claiming"}]).length, 0); });
test("sealed 2 listings", () => { assert.equal(m.checkSealedListingUniqueness([{id:"sp1",deal_id:"d1"}],[{id:"l1",deal_id:"d1",status:"claiming"},{id:"l2",deal_id:"d1",status:"previewing"}]).length, 1); });
test("picked 1 access", () => { assert.equal(m.checkPickedListingAccessCount([{id:"l1",status:"picked"}],[{id:"a1",listing_id:"l1"}]).length, 0); });
test("picked 0 access", () => { assert.ok(m.checkPickedListingAccessCount([{id:"l1",status:"picked"}],[]).some(i=>i.severity==="critical")); });
test("picked 2 access", () => { assert.ok(m.checkPickedListingAccessCount([{id:"l1",status:"picked"}],[{id:"a1",listing_id:"l1"},{id:"a2",listing_id:"l1"}]).some(i=>i.severity==="warning")); });
test("deal has app", () => { assert.equal(m.checkDealHasApplication([{id:"d1"}],[{deal_id:"d1"}],[{deal_id:"d1"}]).length, 0); });
test("deal no app", () => { assert.equal(m.checkDealHasApplication([{id:"d1"}],[{deal_id:"d1"}],[]).length, 1); });
test("score complete", () => { assert.equal(m.checkScoreCompleteness([{id:"s1",score:78,band:"strong_fit",score_status:"locked",input_snapshot:{}}]).length, 0); });
test("score null", () => { assert.ok(m.checkScoreCompleteness([{id:"s1",score:null,band:"x"}]).some(i=>i.severity==="critical")); });
test("band null", () => { assert.ok(m.checkScoreCompleteness([{id:"s1",score:78,band:null}]).some(i=>i.severity==="critical")); });
test("locked null snapshot", () => { assert.ok(m.checkScoreCompleteness([{id:"s1",score:78,band:"x",score_status:"locked",input_snapshot:null}]).some(i=>i.severity==="warning")); });
test("trident bank match", () => { assert.equal(m.checkTridentSealAlignment([{id:"t1",deal_id:"d1",bank_id:"b1",status:"succeeded"}],[{id:"sp1",deal_id:"d1",bank_id:"b1"}]).length, 0); });
test("trident bank mismatch", () => { assert.equal(m.checkTridentSealAlignment([{id:"t1",deal_id:"d1",bank_id:"b1",status:"succeeded"}],[{id:"sp1",deal_id:"d1",bank_id:"b2"}]).length, 1); });
test("doc slot match", () => { assert.equal(m.checkUploadDealOwnership([{id:"d1",deal_id:"d1",slot_id:"s1"}],[{id:"s1",deal_id:"d1"}]).length, 0); });
test("doc slot mismatch", () => { assert.equal(m.checkUploadDealOwnership([{id:"d1",deal_id:"d1",slot_id:"s1"}],[{id:"s1",deal_id:"d2"}]).length, 1); });
test("no storage in listings", () => { assert.equal(m.checkNoStoragePathInListings([{id:"l1",status:"claiming",kfs:{state:"TX"}}]).length, 0); });
test("storage in listings", () => { assert.ok(m.checkNoStoragePathInListings([{id:"l1",status:"claiming",kfs:{ref:"storage_path:/x"}}]).length > 0); });
test("no PII clean", () => { assert.equal(m.checkNoPiiInListingPreview([{id:"l1",deal_id:"d1",status:"claiming",kfs:{state:"TX"}}],[{id:"d1",borrower_name:"Secret",borrower_email:"s@s.com"}]).length, 0); });
test("PII name leak", () => { assert.ok(m.checkNoPiiInListingPreview([{id:"l1",deal_id:"d1",status:"claiming",kfs:{note:"secret runs shop"}}],[{id:"d1",borrower_name:"Secret"}]).length > 0); });
test("PII email leak", () => { assert.ok(m.checkNoPiiInListingPreview([{id:"l1",deal_id:"d1",status:"claiming",kfs:{contact:"s@s.com"}}],[{id:"d1",borrower_email:"s@s.com"}]).length > 0); });
test("golden complete", () => { assert.equal(m.checkGoldenRunDiagnostics({id:"g1"},{hasStory:true,hasScore:true,hasTrident:true,sealed:true,conciergeProgressPct:100}).length, 0); });
test("golden sealed no score", () => { assert.ok(m.checkGoldenRunDiagnostics({id:"g1"},{hasStory:true,hasScore:false,hasTrident:true,sealed:true,conciergeProgressPct:100}).length > 0); });
