import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mockServerOnly } from "../../../../test/utils/mockServerOnly";
mockServerOnly();
const require = createRequire(import.meta.url);
const m = require("../lenderComms") as typeof import("../lenderComms");
type Row = Record<string, any>;
class S { tables:Record<string,Row[]>; constructor(i?:Partial<Record<string,Row[]>>){this.tables={brokerage_lender_message_templates:[],brokerage_lender_message_outbox:[],marketplace_listings:[],lender_marketplace_agreements:[],...i};} from(t:string){return new Q(this,t);} }
class Q { db:S;table:string;filters:Array<{t:string;k:string;v:any}>;_u:Row|null;_i:Row[]|null;_l:number|null;_ord:{key:string;asc:boolean}|null; constructor(db:S,t:string){this.db=db;this.table=t;this.filters=[];this._u=null;this._i=null;this._l=null;this._ord=null;} select(_?:string){return this;} order(k:string,o?:{ascending?:boolean}){this._ord={key:k,asc:o?.ascending!==false};return this;} limit(n:number){this._l=n;return this;} eq(k:string,v:any){this.filters.push({t:"eq",k,v});return this;} in(k:string,v:any[]){this.filters.push({t:"in",k,v});return this;} insert(p:Row|Row[]){const rows=Array.isArray(p)?p:[p];const wi=rows.map(r=>({id:r.id??`id-${Math.random().toString(36).slice(2,8)}`,...r}));this.db.tables[this.table]??=[];this.db.tables[this.table].push(...wi);this._i=wi;return this;} update(u:Row){this._u=u;return this;} single():Promise<{data:any;error:any}>{if(this._i)return Promise.resolve({data:this._i[0],error:null});return Promise.resolve({data:this.rows()[0]??null,error:null});} maybeSingle():Promise<{data:any;error:any}>{if(this._u){for(const r of this.rows())Object.assign(r,this._u);return Promise.resolve({data:this.rows()[0],error:null});}return Promise.resolve({data:this.rows()[0]??null,error:null});} then(f:any,r?:any){if(this._u){for(const row of this.rows())Object.assign(row,this._u);return Promise.resolve({data:this.rows(),error:null}).then(f,r);}if(this._i)return Promise.resolve({data:this._i,error:null}).then(f,r);return Promise.resolve({data:this.rows(),error:null}).then(f,r);} private rows(){let rows=[...(this.db.tables[this.table]??[])];for(const f of this.filters){if(f.t==="eq")rows=rows.filter(r=>r[f.k]===f.v);else if(f.t==="in")rows=rows.filter(r=>(f.v as any[]).includes(r[f.k]));}if(this._ord){const{key,asc}=this._ord;rows.sort((a,b)=>a[key]===b[key]?0:a[key]>b[key]?(asc?1:-1):asc?-1:1);}if(this._l!=null)rows=rows.slice(0,this._l);return rows;} }
function mdb(){return new S({marketplace_listings:[{id:"l1",matched_lender_bank_ids:["b1","b2"]}],lender_marketplace_agreements:[{lender_bank_id:"b1",status:"active",signed_by_email:"l@b.com"}]});}
test("preview redacted",async()=>{const msg=await m.buildLenderMessage("marketplace_preview_open",{lenderBankId:"b1",stage:"preview"},mdb() as any);const r=m.assertLenderMessageSafe(msg,"preview");assert.equal(r.safe,true);});
test("matched only",async()=>{const r1=await m.queueLenderMessage("claim_window_open",{lenderBankId:"b1",listingId:"l1",stage:"claim"},"email",mdb() as any);assert.equal(r1.ok,true);const r2=await m.queueLenderMessage("claim_window_open",{lenderBankId:"bX",listingId:"l1",stage:"claim"},"email",mdb() as any);assert.equal(r2.ok,false);if(!r2.ok)assert.equal(r2.error,"lender_not_matched");});
test("claim no package link",async()=>{const msg=await m.buildLenderMessage("claim_confirmed",{lenderBankId:"b1",stage:"claim"},mdb() as any);assert.ok(!msg.body.includes("/package/"));});
test("picked only",async()=>{const r=await m.queueLenderMessage("borrower_selected_lender",{lenderBankId:"b1",stage:"picked",dealId:"d1"},"email",mdb() as any);assert.equal(r.ok,true);});
test("non-picked blocked",async()=>{const r=await m.queueLenderMessage("package_access_granted",{lenderBankId:"b1",stage:"claim"},"email",mdb() as any);assert.equal(r.ok,false);if(!r.ok)assert.equal(r.error,"trigger_requires_picked_stage");});
test("package safe URL",async()=>{const msg=await m.buildLenderMessage("package_access_granted",{lenderBankId:"b1",accessId:"acc1",stage:"picked"},mdb() as any);assert.ok(msg.body.includes("/lender/marketplace/package/acc1"));assert.ok(!msg.body.includes("/gcs/"));});
test("condition to lender",async()=>{const r=await m.queueLenderMessage("condition_requested",{lenderBankId:"b1",stage:"closing",dealId:"d1"},"dashboard",mdb() as any);assert.equal(r.ok,true);assert.equal(mdb().tables.brokerage_lender_message_outbox.length,0);});
test("funding notice",async()=>{const db=mdb();const r=await m.queueLenderMessage("funding_verified",{lenderBankId:"b1",stage:"funded",dealId:"d1"},"email",db as any);assert.equal(r.ok,true);});
test("cooldown",async()=>{const db=mdb();const r1=await m.queueLenderMessage("claim_window_open",{lenderBankId:"b1",listingId:"l1",stage:"claim"},"email",db as any);const r2=await m.queueLenderMessage("claim_window_open",{lenderBankId:"b1",listingId:"l1",stage:"claim"},"email",db as any);if(r1.ok)assert.equal(r1.suppressed,false);if(r2.ok)assert.equal(r2.suppressed,true);});
test("adapter fail",async()=>{const db=mdb();await m.queueLenderMessage("claim_window_open",{lenderBankId:"b1",listingId:"l1",stage:"claim"},"email",db as any);const oid=db.tables.brokerage_lender_message_outbox[0].id;const r=await m.sendLenderMessage(oid,async()=>({ok:false,error:"smtp"}),db as any);assert.equal(r.ok,false);assert.equal(db.tables.brokerage_lender_message_outbox[0].attempts,1);});
test("strip secrets",async()=>{const db=new S({brokerage_lender_message_templates:[{trigger_key:"test_s",channel:"email",status:"active",body_md:"token_hash rawToken password"}],lender_marketplace_agreements:[{lender_bank_id:"b1",status:"active",signed_by_email:"x@y.com"}]});const msg=await m.buildLenderMessage("test_s",{lenderBankId:"b1"},db as any);assert.ok(!msg.body.includes("token_hash"));assert.ok(msg.body.includes("[REDACTED]"));});
test("safety catches PII",()=>{const r=m.assertLenderMessageSafe({body:"borrower_email here"},"preview");assert.equal(r.safe,false);assert.ok(r.issues.some(i=>i.includes("PII")));const r2=m.assertLenderMessageSafe({body:"A deal is available"},"preview");assert.equal(r2.safe,true);});
test("triggers complete",()=>{assert.ok(m.LENDER_TRIGGER_KEYS.includes("marketplace_preview_open"));assert.ok(m.LENDER_TRIGGER_KEYS.includes("funding_verified"));assert.ok(m.LENDER_TRIGGER_KEYS.length>=14);});
test("portal link",()=>{assert.equal(m.buildLenderPortalLink({lenderBankId:"b1",accessId:"a1"}),"/lender/marketplace/package/a1");assert.equal(m.buildLenderPortalLink({lenderBankId:"b1"}),"/lender/listings");});
test("recipient from agreement",async()=>{const r=await m.getLenderCommsRecipients("b1",mdb() as any);assert.equal(r[0],"l@b.com");});
