import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mockServerOnly } from "../../../../test/utils/mockServerOnly";
mockServerOnly();
const require = createRequire(import.meta.url);
const m = require("../notificationDelivery") as typeof import("../notificationDelivery");
type Row = Record<string, any>;
class S { tables:Record<string,Row[]>; constructor(i?:Partial<Record<string,Row[]>>){this.tables={brokerage_alerts:[],brokerage_alert_subscriptions:[],brokerage_notification_outbox:[],brokerage_alert_events:[],...i};} from(t:string){return new Q(this,t);} }
class Q { db:S;table:string;filters:Array<{t:string;k:string;v:any}>;_u:Row|null;_i:Row[]|null;_l:number|null; constructor(db:S,t:string){this.db=db;this.table=t;this.filters=[];this._u=null;this._i=null;this._l=null;} select(_?:string){return this;} order(_k:string,_o?:any){return this;} limit(n:number){this._l=n;return this;} eq(k:string,v:any){this.filters.push({t:"eq",k,v});return this;} in(k:string,v:any[]){this.filters.push({t:"in",k,v});return this;} insert(p:Row|Row[]){const rows=Array.isArray(p)?p:[p];const wi=rows.map(r=>({id:r.id??`id-${Math.random().toString(36).slice(2,8)}`,...r}));this.db.tables[this.table]??=[];this.db.tables[this.table].push(...wi);this._i=wi;return this;} update(u:Row){this._u=u;return this;} single():Promise<{data:any;error:any}>{if(this._i)return Promise.resolve({data:this._i[0],error:null});return Promise.resolve({data:this.rows()[0]??null,error:null});} maybeSingle():Promise<{data:any;error:any}>{if(this._u){for(const r of this.rows())Object.assign(r,this._u);return Promise.resolve({data:this.rows()[0],error:null});}return Promise.resolve({data:this.rows()[0]??null,error:null});} then(f:any,r?:any){if(this._u){for(const row of this.rows())Object.assign(row,this._u);return Promise.resolve({data:this.rows(),error:null}).then(f,r);}if(this._i)return Promise.resolve({data:this._i,error:null}).then(f,r);return Promise.resolve({data:this.rows(),error:null}).then(f,r);} private rows(){let rows=[...(this.db.tables[this.table]??[])];for(const f of this.filters){if(f.t==="eq")rows=rows.filter(r=>r[f.k]===f.v);else if(f.t==="in")rows=rows.filter(r=>(f.v as any[]).includes(r[f.k]));}if(this._l!=null)rows=rows.slice(0,this._l);return rows;} }
function makeAlert(ov?: Partial<Row>): any { return { id:"a1",alertKey:"k1",source:"t",severity:"critical",status:"active",dealId:null,title:"Crit",message:"Bad",action:"Fix",firstSeenAt:new Date().toISOString(),lastSeenAt:new Date().toISOString(),occurrenceCount:1,...ov }; }
test("critical creates outbox",async()=>{const db=new S({brokerage_alerts:[{id:"a1",alert_key:"k1",source:"t",severity:"critical",status:"active",title:"C",message:"B",action:"F",first_seen_at:new Date().toISOString(),last_seen_at:new Date().toISOString(),occurrence_count:1}],brokerage_alert_subscriptions:[{id:"s1",subscriber_email:"o@t.com",severity_filter:"critical",channel:"email",active:true}]});const{queued}=await m.buildNotificationOutbox(db as any);assert.ok(queued>=1);});
test("suppressed no notify",()=>{assert.equal(m.shouldNotifySubscription(makeAlert({status:"suppressed"}),{severity_filter:"critical",active:true,channel:"email"},[]),false);});
test("warning digest",()=>{const{subject,body}=m.buildEmailDigest([makeAlert({severity:"warning",title:"W1"}),makeAlert({severity:"warning",title:"W2",id:"a2"})]);assert.ok(subject.includes("warning"));assert.ok(body.includes("W1"));});
test("cooldown blocks",()=>{assert.equal(m.shouldNotifySubscription(makeAlert(),{severity_filter:"critical",active:true,channel:"email"},[{alert_id:"a1",status:"sent",created_at:new Date().toISOString()}]),false);});
test("dashboard immediate",async()=>{const db=new S({brokerage_alerts:[{id:"a1",alert_key:"k1",source:"t",severity:"critical",status:"active",title:"C",message:"B",action:"F",first_seen_at:new Date().toISOString(),last_seen_at:new Date().toISOString(),occurrence_count:1}],brokerage_alert_subscriptions:[{id:"s1",subscriber_email:"o@t.com",severity_filter:"critical",channel:"dashboard",active:true}]});await m.buildNotificationOutbox(db as any);assert.equal(db.tables.brokerage_notification_outbox[0]?.status,"sent");});
test("failed adapter",async()=>{const db=new S({brokerage_notification_outbox:[{id:"n1",channel:"email",recipient:"o@t.com",subject:"T",body:"B",status:"pending",attempts:0}]});const{failed}=await m.sendPendingNotifications(db as any,{email:async()=>({ok:false,error:"smtp"})});assert.equal(failed,1);assert.equal(db.tables.brokerage_notification_outbox[0].status,"failed");});
test("retry increments",async()=>{const db=new S({brokerage_notification_outbox:[{id:"n1",channel:"email",recipient:"x",body:"B",status:"pending",attempts:2}]});await m.markNotificationFailed("n1","err",db as any);assert.equal(db.tables.brokerage_notification_outbox[0].attempts,3);});
test("email digest subject",()=>{const{subject,body}=m.buildEmailDigest([makeAlert()]);assert.ok(subject.includes("CRITICAL"));assert.ok(body.includes("Fix"));});
test("slack concise",()=>{const{body}=m.buildSlackDigest([makeAlert()]);assert.ok(body.includes("Critical"));assert.ok(body.length<500);});
test("body strips secrets",()=>{const{body}=m.buildEmailDigest([makeAlert({title:"token_hash leak rawToken password"})]);assert.ok(!body.includes("token_hash"));assert.ok(!body.includes("rawToken"));});
test("full cycle",async()=>{const db=new S({brokerage_alerts:[{id:"a1",alert_key:"k1",source:"t",severity:"critical",status:"active",title:"C",message:"B",action:"F",first_seen_at:new Date().toISOString(),last_seen_at:new Date().toISOString(),occurrence_count:1}],brokerage_alert_subscriptions:[{id:"s1",subscriber_email:"o@t.com",severity_filter:"critical",channel:"email",active:true}]});const r=await m.runBrokerageNotificationCycle(db as any,{email:async()=>({ok:true})});assert.ok(r.queued>=1);assert.ok(r.sent>=1);});
