import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const m = require("../revenueOps") as typeof import("../revenueOps");
type Row = Record<string, any>;
class S { tables:Record<string,Row[]>; constructor(i?:Partial<Record<string,Row[]>>){this.tables={brokerage_funding_verifications:[],brokerage_revenue_events:[],brokerage_fee_ledger:[],brokerage_closing_workflows:[],marketplace_claims:[],lender_marketplace_agreements:[],...i};} from(t:string){return new Q(this,t);} }
class Q { db:S;table:string;filters:Array<{t:string;k:string;v:any}>;_u:Row|null;_i:Row[]|null;_l:number|null; constructor(db:S,t:string){this.db=db;this.table=t;this.filters=[];this._u=null;this._i=null;this._l=null;} select(_?:string){return this;} order(_k:string,_o?:any){return this;} limit(n:number){this._l=n;return this;} eq(k:string,v:any){this.filters.push({t:"eq",k,v});return this;} in(k:string,v:any[]){this.filters.push({t:"in",k,v});return this;} is(k:string,v:any){this.filters.push({t:"is",k,v});return this;} insert(p:Row|Row[]){const rows=Array.isArray(p)?p:[p];const wi=rows.map(r=>({id:r.id??`id-${Math.random().toString(36).slice(2,8)}`,...r}));this.db.tables[this.table]??=[];this.db.tables[this.table].push(...wi);this._i=wi;return this;} update(u:Row){this._u=u;return this;} single():Promise<{data:any;error:any}>{if(this._i)return Promise.resolve({data:this._i[0],error:null});return Promise.resolve({data:this.rows()[0]??null,error:null});} maybeSingle():Promise<{data:any;error:any}>{if(this._u){for(const r of this.rows())Object.assign(r,this._u);return Promise.resolve({data:this.rows()[0],error:null});}return Promise.resolve({data:this.rows()[0]??null,error:null});} then(f:any,r?:any){if(this._u){for(const row of this.rows())Object.assign(row,this._u);return Promise.resolve({data:this.rows(),error:null}).then(f,r);}if(this._i)return Promise.resolve({data:this._i,error:null}).then(f,r);return Promise.resolve({data:this.rows(),error:null}).then(f,r);} private rows(){let rows=[...(this.db.tables[this.table]??[])];for(const f of this.filters){if(f.t==="eq")rows=rows.filter(r=>r[f.k]===f.v);else if(f.t==="in")rows=rows.filter(r=>(f.v as any[]).includes(r[f.k]));else if(f.t==="is")rows=rows.filter(r=>{const v=r[f.k];return f.v===null?v==null:v===f.v;});}if(this._l!=null)rows=rows.slice(0,this._l);return rows;} }
const FI={fundedAmountCents:85000000,fundedAt:"2026-07-01",verificationSource:"lender_confirmation" as const,verifiedByScope:"lender" as const};
function fdb(){return new S({brokerage_closing_workflows:[{id:"wf1",deal_id:"d1",lender_bank_id:"b1",status:"clear_to_close"}],brokerage_fee_ledger:[{id:"fl1",deal_id:"d1",fee_type:"borrower_packaging",amount_cents:100000,status:"disclosed"},{id:"fl2",deal_id:"d1",fee_type:"lender_referral",amount_cents:850000,bps:100,status:"disclosed"}],marketplace_claims:[{deal_id:"d1",lender_bank_id:"b1",status:"picked",committed_rate_bps:100}],lender_marketplace_agreements:[{lender_bank_id:"b1",status:"active",referral_fee_bps:100}]});}
test("verify funding",async()=>{const db=fdb();const r=await m.verifyDealFunding("d1",FI,db as any);assert.equal(r.ok,true);if(r.ok)assert.equal(r.idempotent,false);assert.equal(db.tables.brokerage_funding_verifications.length,1);});
test("verify idempotent",async()=>{const db=fdb();const r1=await m.verifyDealFunding("d1",FI,db as any);const r2=await m.verifyDealFunding("d1",FI,db as any);if(r1.ok&&r2.ok){assert.equal(r1.verificationId,r2.verificationId);assert.equal(r2.idempotent,true);}assert.equal(db.tables.brokerage_funding_verifications.length,1);});
test("borrower fee $1000",async()=>{const r=await m.calculateFinalBorrowerPackagingFee("d1",fdb() as any);assert.equal(r.amountCents,100000);assert.equal(r.waived,false);});
test("waived fee $0",async()=>{const r=await m.calculateFinalBorrowerPackagingFee("d1",new S({brokerage_fee_ledger:[{deal_id:"d1",fee_type:"borrower_packaging",amount_cents:100000,status:"waived"}]}) as any);assert.equal(r.amountCents,0);assert.equal(r.waived,true);});
test("lender fee calc",async()=>{const r=await m.calculateFinalLenderReferralFee("d1","b1",85000000,fdb() as any);assert.equal(r.bps,100);assert.equal(r.amountCents,850000);});
test("mark earned",async()=>{const db=fdb();const{updated}=await m.markFeesEarned("d1","vf1",db as any);assert.equal(updated,2);for(const f of db.tables.brokerage_fee_ledger)assert.equal(f.status,"earned");});
test("mark funded",async()=>{const db=fdb();await m.markFeesEarned("d1","vf1",db as any);const{updated}=await m.markFeesFunded("d1","vf1",db as any);assert.equal(updated,2);for(const f of db.tables.brokerage_fee_ledger){assert.equal(f.status,"funded");assert.ok(f.funding_verified_at);}});
test("waived stays",async()=>{const db=new S({brokerage_fee_ledger:[{id:"fl1",deal_id:"d1",fee_type:"borrower_packaging",amount_cents:100000,status:"waived"},{id:"fl2",deal_id:"d1",fee_type:"lender_referral",amount_cents:850000,status:"disclosed"}]});await m.markFeesEarned("d1","vf1",db as any);assert.equal(db.tables.brokerage_fee_ledger.find(f=>f.fee_type==="borrower_packaging")?.status,"waived");assert.equal(db.tables.brokerage_fee_ledger.find(f=>f.fee_type==="lender_referral")?.status,"earned");});
test("events written",async()=>{const db=fdb();await m.verifyDealFunding("d1",FI,db as any);await m.createRevenueEventsForFunding("d1","vf1",85000000,"b1",db as any);const types=db.tables.brokerage_revenue_events.map(e=>e.event_type);assert.ok(types.includes("funding_verified"));assert.ok(types.includes("fee_earned"));assert.ok(types.includes("fee_funded"));});
test("reconciliation missing",async()=>{const r=await m.runRevenueReconciliation(new S({brokerage_closing_workflows:[{deal_id:"d1",status:"funded"}]}) as any);assert.equal(r.fundedDeals,1);assert.equal(r.missingVerification,1);assert.ok(r.criticalIssues.length>0);});
test("reconciliation mismatch",async()=>{const r=await m.runRevenueReconciliation(new S({brokerage_closing_workflows:[{deal_id:"d1",status:"funded"}],brokerage_funding_verifications:[{deal_id:"d1",status:"verified"}],brokerage_fee_ledger:[{deal_id:"d1",fee_type:"borrower_packaging",amount_cents:100000,status:"disclosed"}]}) as any);assert.equal(r.feeLedgerMismatches,1);});
test("revenue summary",async()=>{const db=fdb();db.tables.brokerage_funding_verifications=[{deal_id:"d1",funded_amount_cents:85000000,status:"verified"}];for(const f of db.tables.brokerage_fee_ledger)f.status="funded";const r=await m.getRevenueSummary("d1",db as any);assert.equal(r.funded,true);assert.equal(r.totalRevenueCents,950000);assert.equal(r.issues.length,0);});
