/**
 * Surface Wiring Ledger — Phase 64
 *
 * Canonical source of truth for every Stitch surface's integration status.
 *
 * Status model (Phase 64 canonical):
 * - recovery_optional          — optional recovery route, not production-critical
 * - visual_static              — static Stitch HTML only, no Buddy activation
 * - partial_readonly           — some real data injected, no write actions
 * - partial_interactive        — some real data + some write actions
 * - wired_readonly             — fully bound to real Buddy data, no writes
 * - wired_interactive          — fully bound to real Buddy data + real write actions
 * - blocked_auth               — route exists but auth/permission blocks activation
 * - blocked_missing_backend    — no backend APIs exist for this surface's domain
 * - blocked_missing_data_contract — backend exists but no data contract defined
 * - retired                    — surface removed or replaced
 */

export type WiringStatus =
  | "recovery_optional"
  | "visual_static"
  | "partial_readonly"
  | "partial_interactive"
  | "wired_readonly"
  | "wired_interactive"
  | "blocked_auth"
  | "blocked_missing_backend"
  | "blocked_missing_data_contract"
  | "retired";

export type ActivationMode = "none" | "overlay" | "replace";

export type IntegrationType =
  | "read_only"
  | "read_nav"
  | "read_write"
  | "token_activated"
  | "visual_only";

export type InteractiveType = "direct" | "routed" | "readonly" | "none";

export type SurfaceWiringEntry = {
  key: string;
  route: string;
  slug: string;
  owner: "banker" | "borrower" | "admin";
  required: boolean;
  integrationType: IntegrationType;
  activationMode: ActivationMode;
  interactiveType: InteractiveType;
  routeParamsNeeded: string[];
  dataDependencies: string[];
  apiCallsExpected: string[];
  writeActionsExpected: string[];
  permissionModel: string;
  hasActivationScript: boolean;
  hasHistoryPanel: boolean;
  hasReflectionMap: boolean;
  status: WiringStatus;
  notes: string;
};

export const SURFACE_WIRING_LEDGER: SurfaceWiringEntry[] = [
  // ══════════════════════════════════════════════════════════════
  // WIRED — Live data activation scripts, real Buddy data
  // ══════════════════════════════════════════════════════════════
  {
    key: "portfolio",
    route: "/portfolio",
    slug: "portfolio-command-bridge",
    owner: "banker",
    required: true,
    integrationType: "read_nav",
    activationMode: "overlay",
    routeParamsNeeded: [],
    dataDependencies: ["deals"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: true,
    hasHistoryPanel: false,
    hasReflectionMap: true,
    interactiveType: "readonly",
    status: "wired_readonly",
    notes: "Server-side activation injects real deal rows + KPIs. Row click navigates to deal.",
  },
  {
    key: "deal_intake",
    route: "/intake",
    slug: "deal-intake-console",
    owner: "banker",
    required: true,
    integrationType: "read_nav",
    activationMode: "overlay",
    routeParamsNeeded: [],
    dataDependencies: ["deals"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: true,
    hasHistoryPanel: false,
    hasReflectionMap: true,
    interactiveType: "readonly",
    status: "wired_readonly",
    notes: "Server-side activation injects real intake-stage deals. Create Deal button wired.",
  },
  {
    key: "borrower_portal",
    route: "/borrower/portal",
    slug: "borrower-document-upload-review",
    owner: "borrower",
    required: true,
    integrationType: "token_activated",
    activationMode: "overlay",
    routeParamsNeeded: ["token"],
    dataDependencies: ["borrower_upload_inbox", "deal_checklist"],
    apiCallsExpected: [],
    writeActionsExpected: ["upload_document"],
    permissionModel: "valid_invite_token",
    hasActivationScript: true,
    hasHistoryPanel: true,
    hasReflectionMap: true,
    interactiveType: "direct",
    status: "wired_interactive",
    notes: "Token-gated. Real uploads, checklist, drag-drop upload wired.",
  },
  {
    key: "deals_command_bridge",
    route: "/deals/[dealId]/underwriter",
    slug: "deals-command-bridge",
    owner: "banker",
    required: true,
    integrationType: "read_write",
    activationMode: "overlay",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "documents", "checklist", "audit_ledger"],
    apiCallsExpected: [],
    writeActionsExpected: ["name_deal", "request_borrower_docs", "generate_upload_link"],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: true,
    hasHistoryPanel: true,
    hasReflectionMap: true,
    interactiveType: "direct",
    status: "wired_interactive",
    notes: "Legacy Stitch surface formerly at /deals/[dealId]/underwriter (route retired). Now embedded only inside canonical /deals/[dealId]/underwrite as transitional backward-compat layer beneath AnalystWorkbench. Not a primary route.",
  },

  // ══════════════════════════════════════════════════════════════
  // P0 — Activated in Phase 62C with real Buddy data
  // ══════════════════════════════════════════════════════════════
  {
    key: "credit_committee_view",
    route: "/credit/committee",
    slug: "credit-committee-view",
    owner: "banker",
    required: true,
    integrationType: "read_write",
    activationMode: "overlay",
    routeParamsNeeded: [],
    dataDependencies: ["deals"],
    apiCallsExpected: [],
    writeActionsExpected: ["navigate_to_committee_review"],
    permissionModel: "bank_member",
    hasActivationScript: true,
    hasHistoryPanel: true,
    hasReflectionMap: true,
    interactiveType: "routed",
    status: "wired_interactive",
    notes: "Phase 64. Real committee-eligible deals. Review button navigates to deal committee for voting. Voting uses existing CommitteePanel.",
  },
  {
    key: "exceptions_change_review",
    route: "/exceptions",
    slug: "exceptions-change-review",
    owner: "banker",
    required: true,
    integrationType: "read_write",
    activationMode: "overlay",
    routeParamsNeeded: [],
    dataDependencies: ["deals", "deal_policy_exceptions"],
    apiCallsExpected: ["/api/exceptions/decide"],
    writeActionsExpected: ["approve_exception", "reject_exception", "escalate_exception"],
    permissionModel: "bank_member",
    hasActivationScript: true,
    hasHistoryPanel: true,
    hasReflectionMap: true,
    interactiveType: "direct",
    status: "wired_interactive",
    notes: "Phase 63. Real exception queue. Approve/reject/escalate buttons call /api/exceptions/decide → writes deal_policy_exceptions + deal_events ledger.",
  },
  {
    key: "borrower_task_inbox",
    route: "/deals/[dealId]/portal-inbox",
    slug: "borrower-task-inbox",
    owner: "banker",
    required: true,
    integrationType: "read_write",
    activationMode: "overlay",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal_checklist", "borrower_upload_inbox"],
    apiCallsExpected: ["/api/deals/[dealId]/checklist/set-status"],
    writeActionsExpected: ["mark_received"],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: true,
    hasHistoryPanel: true,
    hasReflectionMap: true,
    interactiveType: "direct",
    status: "wired_interactive",
    notes: "Phase 63. Real checklist items. Mark Received button calls checklist/set-status → writes deal_checklist_items + deal_events ledger.",
  },
  {
    key: "borrower_control_record",
    route: "/borrowers/control-record",
    slug: "borrower-control-record",
    owner: "banker",
    required: true,
    integrationType: "read_nav",
    activationMode: "overlay",
    routeParamsNeeded: [],
    dataDependencies: ["borrowers", "deals"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: true,
    hasHistoryPanel: false,
    hasReflectionMap: true,
    interactiveType: "readonly",
    status: "wired_readonly",
    notes: "Phase 62C. Injects real borrower entities from deals. Row click navigates to deal borrower view.",
  },
  {
    key: "pricing_memo_command_center",
    route: "/deals/[dealId]/pricing-memo",
    slug: "pricing-memo-command-center",
    owner: "banker",
    required: true,
    integrationType: "read_write",
    activationMode: "overlay",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "pricing_scenarios", "pricing_decisions"],
    apiCallsExpected: ["/api/deals/[dealId]/pricing/decide"],
    writeActionsExpected: ["commit_pricing"],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: true,
    hasHistoryPanel: true,
    hasReflectionMap: true,
    interactiveType: "direct",
    status: "wired_interactive",
    notes: "Phase 63. Real pricing scenarios + decision. Commit Pricing button calls pricing/decide → writes pricing_decisions + pricing_terms + deal_events ledger.",
  },

  // ══════════════════════════════════════════════════════════════
  // HONESTLY CLASSIFIED — Backend limited or missing
  // ══════════════════════════════════════════════════════════════
  {
    key: "loan_servicing_command_center",
    route: "/servicing",
    slug: "loan-servicing-command-center",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: ["sba_loans", "sba_milestones"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "blocked_missing_backend",
    notes: "SBA milestone tracking exists but no banker-facing servicing UI/API. Needs full servicing backend.",
  },
  {
    key: "workout_command_center",
    route: "/workout",
    slug: "workout-command-center",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: [],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "blocked_missing_backend",
    notes: "No workout backend exists. Entire domain (case management, REO, legal, chargeoff) needs backend build.",
  },
  {
    key: "workout_case_file",
    route: "/workout/case-file",
    slug: "workout-case-file",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: [],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "blocked_missing_backend",
    notes: "No workout case file backend.",
  },
  {
    key: "workout_committee_packet",
    route: "/workout/committee-packet",
    slug: "workout-committee-packet",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: [],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "blocked_missing_backend",
    notes: "No workout committee packet backend.",
  },
  {
    key: "workout_legal_execution_tracker",
    route: "/workout/legal",
    slug: "workout-legal-execution-tracker",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: [],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "blocked_missing_backend",
    notes: "No workout legal tracker backend.",
  },
  {
    key: "reo_command_center",
    route: "/workout/reo",
    slug: "reo-command-center",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: [],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "blocked_missing_backend",
    notes: "No REO management backend.",
  },
  {
    key: "chargeoff_recovery_command_center",
    route: "/workout/chargeoff",
    slug: "chargeoff-recovery-command-center",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: [],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "blocked_missing_backend",
    notes: "No chargeoff recovery backend.",
  },

  // ══════════════════════════════════════════════════════════════
  // P1/P2 — Visual static, awaiting future activation
  // ══════════════════════════════════════════════════════════════
  {
    key: "deal_command",
    route: "/deals/[dealId]/command",
    slug: "command-center-latest",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "lifecycle"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "Panel mode. Uses deals_command_bridge activation at /underwriter for deal context.",
  },
  {
    key: "underwrite",
    route: "/deals/[dealId]/underwrite",
    slug: "underwrite",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "financial_snapshot"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "Canonical underwriting route. Native lifecycle-gated page with AnalystWorkbench as primary. Legacy Stitch content is transitional and embedded via deals_command_bridge. No standalone stitch_exports/underwrite/code.html.",
  },
  {
    key: "credit_committee",
    route: "/deals/[dealId]/committee",
    slug: "deal-summary",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "committee_votes"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + committee_role",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "No stitch_exports/deal-summary/code.html. Native CommitteeView wrapper.",
  },
  {
    key: "pipeline_analytics_command_center",
    route: "/analytics",
    slug: "pipeline-analytics-command-center",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: ["deals_aggregate"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "Contains mock chart areas. Awaiting analytics backend for live data.",
  },
  {
    key: "audit_compliance_ledger",
    route: "/compliance/audit-ledger",
    slug: "audit-compliance-ledger",
    owner: "admin",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: ["audit_events"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "super_admin",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "Awaiting activation. deal_events / deal_pipeline_ledger available as data source.",
  },
  {
    key: "document_template_vault",
    route: "/templates/vault",
    slug: "document-template-vault",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: ["templates"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "Static Stitch design with 'Test with Sample' button.",
  },
  {
    key: "ocr_review_data_validation",
    route: "/ocr/review",
    slug: "ocr-review-data-validation",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: ["ocr_results"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "Static Stitch design.",
  },
  {
    key: "roles_permissions_control",
    route: "/admin/roles",
    slug: "roles-permissions-control",
    owner: "admin",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: ["roles"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "super_admin",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "Static Stitch design.",
  },
  {
    key: "merge_field_registry",
    route: "/admin/merge-fields",
    slug: "merge-field-registry",
    owner: "admin",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: ["merge_fields"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "super_admin",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "Static Stitch design. Contains hard-coded DL-2023-8492.",
  },
  {
    key: "borrower_document_upload_inbox",
    route: "/deals/[dealId]/borrower-inbox",
    slug: "borrower-document-upload-review",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["borrower_uploads"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "Shares slug with borrower_portal. Different route, no activation.",
  },
  {
    key: "borrower_profile",
    route: "/deals/[dealId]/borrower",
    slug: "borrower-profile",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["borrower"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "Static Stitch design.",
  },
  {
    key: "credit_memo_pdf_template",
    route: "/deals/[dealId]/memo-template",
    slug: "credit-memo-pdf-template",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "credit_memo"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "Contains demo Beacon Capital data. Awaiting activation.",
  },
  {
    key: "deal_output_credit_memo_spreads",
    route: "/deals/[dealId]/memos/new",
    slug: "deal-output-credit-memo-spreads",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "spreads"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "visual_static",
    notes: "Contains demo Project Atlas data. Awaiting activation.",
  },

  // ══════════════════════════════════════════════════════════════
  // OPTIONAL — Recovery routes
  // ══════════════════════════════════════════════════════════════
  {
    key: "deals_pipeline_recovery",
    route: "/stitch-recovery/deals",
    slug: "deals-pipeline-command-center",
    owner: "banker",
    required: false,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: [],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "recovery_optional",
    notes: "Recovery route for comparison with native /deals.",
  },
  {
    key: "deal_intake_recovery",
    route: "/stitch-recovery/deals-new",
    slug: "deal-intake-console",
    owner: "banker",
    required: false,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: [],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "recovery_optional",
    notes: "Recovery route for comparison with native /deals/new.",
  },
  {
    key: "stitch_login",
    route: "/stitch-login",
    slug: "stitch_buddy_login_page",
    owner: "borrower",
    required: false,
    integrationType: "visual_only",
    activationMode: "none",
    routeParamsNeeded: [],
    dataDependencies: [],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "public",
    hasActivationScript: false,
    hasHistoryPanel: false,
    hasReflectionMap: false,
    interactiveType: "none",
    status: "recovery_optional",
    notes: "Branded login shell. Does not replace Clerk auth.",
  },
];

/** Lookup by surface key */
export function getWiringEntry(key: string): SurfaceWiringEntry | undefined {
  return SURFACE_WIRING_LEDGER.find((e) => e.key === key);
}

/** Summary counts */
export function getWiringSummary() {
  const total = SURFACE_WIRING_LEDGER.length;
  const counts: Record<WiringStatus, number> = {
    recovery_optional: 0,
    visual_static: 0,
    partial_readonly: 0,
    partial_interactive: 0,
    wired_readonly: 0,
    wired_interactive: 0,
    blocked_auth: 0,
    blocked_missing_backend: 0,
    blocked_missing_data_contract: 0,
    retired: 0,
  };

  for (const entry of SURFACE_WIRING_LEDGER) {
    counts[entry.status]++;
  }

  const required = SURFACE_WIRING_LEDGER.filter((e) => e.required).length;
  const withActivation = SURFACE_WIRING_LEDGER.filter((e) => e.hasActivationScript).length;

  return { total, required, withActivation, ...counts };
}
