/**
 * Surface Wiring Ledger — Phase 62B
 *
 * Canonical source of truth for every Stitch surface's integration status.
 * Each entry describes what the surface needs to be fully wired to Buddy.
 *
 * Status values:
 * - "wired"      — loads real Buddy data via activation script
 * - "visual"     — renders saved Stitch design, no live data injection yet
 * - "partial"    — has activation script but missing some data bindings
 * - "broken"     — route exists but rendering or data flow fails
 * - "unverified" — not yet inspected
 */

export type WiringStatus = "wired" | "visual" | "partial" | "broken" | "unverified";

export type IntegrationType =
  | "read_only"       // displays data, no user actions
  | "read_nav"        // displays data + navigates to other routes
  | "read_write"      // displays data + performs write actions
  | "token_activated" // externalized view activated by borrower token
  | "visual_only";    // static Stitch design, no data integration

export type SurfaceWiringEntry = {
  key: string;
  route: string;
  slug: string;
  owner: "banker" | "borrower" | "admin";
  required: boolean;
  integrationType: IntegrationType;
  routeParamsNeeded: string[];
  dataDependencies: string[];
  apiCallsExpected: string[];
  writeActionsExpected: string[];
  permissionModel: string;
  hasActivationScript: boolean;
  emptyStateExpected: string;
  errorStateExpected: string;
  successCriteria: string;
  status: WiringStatus;
  notes: string;
};

export const SURFACE_WIRING_LEDGER: SurfaceWiringEntry[] = [
  // ══════════════════════════════════════════════════════════════
  // WIRED — Live data activation scripts exist
  // ══════════════════════════════════════════════════════════════
  {
    key: "portfolio",
    route: "/portfolio",
    slug: "portfolio-command-bridge",
    owner: "banker",
    required: true,
    integrationType: "read_nav",
    routeParamsNeeded: [],
    dataDependencies: ["deals", "financial_snapshots"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: true,
    emptyStateExpected: "No active loans found.",
    errorStateExpected: "Activation data missing — empty table",
    successCriteria: "Table rows populated with real deal data, KPI totals reflect bank exposure, row click navigates to deal",
    status: "wired",
    notes: "Server-side activation via portfolioCommandBridgeActivation.ts. Injects deal rows + KPIs into static table.",
  },
  {
    key: "deal_intake",
    route: "/intake",
    slug: "deal-intake-console",
    owner: "banker",
    required: true,
    integrationType: "read_nav",
    routeParamsNeeded: [],
    dataDependencies: ["deals"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: true,
    emptyStateExpected: "No recent deals",
    errorStateExpected: "Activation data missing — empty list",
    successCriteria: "Recent deals listed with real names and stages",
    status: "wired",
    notes: "Server-side activation via dealIntakeConsoleActivation.ts.",
  },
  {
    key: "borrower_portal",
    route: "/borrower/portal",
    slug: "borrower-document-upload-review",
    owner: "borrower",
    required: true,
    integrationType: "token_activated",
    routeParamsNeeded: ["token"],
    dataDependencies: ["borrower_upload_inbox", "deal_checklist"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "valid_invite_token",
    hasActivationScript: true,
    emptyStateExpected: "No uploads yet",
    errorStateExpected: "Invalid or expired token — null render",
    successCriteria: "Borrower sees their uploads and checklist items for the deal",
    status: "wired",
    notes: "Server-side activation via borrowerPortalActivation.ts. Token-gated.",
  },
  {
    key: "deals_command_bridge",
    route: "/deals/[dealId]/underwriter",
    slug: "deals-command-bridge",
    owner: "banker",
    required: true,
    integrationType: "read_nav",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "documents", "checklist"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: true,
    emptyStateExpected: "Deal context loading",
    errorStateExpected: "Activation data missing — static export shown",
    successCriteria: "Deal-specific data populates the command bridge UI",
    status: "wired",
    notes: "Server-side activation via underwriteCommandBridgeActivation.ts.",
  },

  // ══════════════════════════════════════════════════════════════
  // VISUAL — Static Stitch design, no live data injection yet
  // These render the saved Stitch export but show demo/sample content.
  // ══════════════════════════════════════════════════════════════
  {
    key: "deal_command",
    route: "/deals/[dealId]/command",
    slug: "command-center-latest",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "lifecycle", "documents"],
    apiCallsExpected: [],
    writeActionsExpected: ["navigate_to_workflow"],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    emptyStateExpected: "Static command center layout",
    errorStateExpected: "Panel mode fallback card",
    successCriteria: "Visual command center renders; future: live deal data injection",
    status: "visual",
    notes: "Panel mode. Static Stitch design. Needs activation script for live deal context.",
  },
  {
    key: "underwrite",
    route: "/deals/[dealId]/underwrite",
    slug: "underwrite",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "financial_snapshot", "pricing"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    emptyStateExpected: "Static underwrite layout",
    errorStateExpected: "Lifecycle guard blocks if not ready",
    successCriteria: "Underwrite surface renders; lifecycle-gated",
    status: "visual",
    notes: "No stitch_exports/underwrite/code.html exists. Uses native lifecycle guards.",
  },
  {
    key: "credit_committee",
    route: "/deals/[dealId]/committee",
    slug: "deal-summary",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "financial_snapshot", "committee_votes"],
    apiCallsExpected: [],
    writeActionsExpected: ["cast_vote", "export_pdf"],
    permissionModel: "bank_member + committee_role",
    hasActivationScript: false,
    emptyStateExpected: "Static committee layout",
    errorStateExpected: "Native layout with snapshot unavailable state",
    successCriteria: "Committee view renders; future: live vote/snapshot injection",
    status: "visual",
    notes: "No stitch_exports/deal-summary/code.html exists. Wrapped in native CommitteeView.",
  },
  {
    key: "pipeline_analytics_command_center",
    route: "/analytics",
    slug: "pipeline-analytics-command-center",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["deals_aggregate", "pipeline_metrics"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static analytics charts with demo data",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Analytics dashboard renders; shows demo charts. Future: live pipeline data.",
    status: "visual",
    notes: "Contains mock chart areas. Needs activation script for live pipeline metrics.",
  },
  {
    key: "loan_servicing_command_center",
    route: "/servicing",
    slug: "loan-servicing-command-center",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["loans", "payment_history", "delinquency"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static servicing layout with demo data",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Servicing dashboard renders with demo Highland Capital data",
    status: "visual",
    notes: "Contains demo Highland Capital Partners data + mock chart. Needs activation.",
  },
  {
    key: "workout_command_center",
    route: "/workout",
    slug: "workout-command-center",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["workout_cases"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static workout layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Workout command center renders with demo data",
    status: "visual",
    notes: "Contains demo Highland Capital + Healthy Grocer data.",
  },
  {
    key: "workout_case_file",
    route: "/workout/case-file",
    slug: "workout-case-file",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["workout_case"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static case file layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Workout case file renders",
    status: "visual",
    notes: "Static Stitch design.",
  },
  {
    key: "workout_committee_packet",
    route: "/workout/committee-packet",
    slug: "workout-committee-packet",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["workout_packet"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static committee packet layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Workout committee packet renders",
    status: "visual",
    notes: "Static Stitch design.",
  },
  {
    key: "workout_legal_execution_tracker",
    route: "/workout/legal",
    slug: "workout-legal-execution-tracker",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["legal_actions"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static legal tracker layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Legal execution tracker renders",
    status: "visual",
    notes: "Static Stitch design.",
  },
  {
    key: "reo_command_center",
    route: "/workout/reo",
    slug: "reo-command-center",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["reo_properties"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static REO layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "REO command center renders",
    status: "visual",
    notes: "Static Stitch design.",
  },
  {
    key: "chargeoff_recovery_command_center",
    route: "/workout/chargeoff",
    slug: "chargeoff-recovery-command-center",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["chargeoff_cases"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static chargeoff layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Chargeoff recovery center renders",
    status: "visual",
    notes: "Static Stitch design.",
  },
  {
    key: "audit_compliance_ledger",
    route: "/compliance/audit-ledger",
    slug: "audit-compliance-ledger",
    owner: "admin",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["audit_events", "compliance_checks"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "super_admin",
    hasActivationScript: false,
    emptyStateExpected: "Static audit ledger layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Audit compliance ledger renders",
    status: "visual",
    notes: "Static Stitch design. Previously had native AuditLedgerClient.",
  },
  {
    key: "document_template_vault",
    route: "/templates/vault",
    slug: "document-template-vault",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["templates"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static template vault layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Template vault renders with demo templates",
    status: "visual",
    notes: "Contains 'Test with Sample' button. Static Stitch design.",
  },
  {
    key: "exceptions_change_review",
    route: "/exceptions",
    slug: "exceptions-change-review",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["exceptions", "change_requests"],
    apiCallsExpected: [],
    writeActionsExpected: ["approve_exception", "escalate"],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static exceptions layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Exceptions review renders with demo data",
    status: "visual",
    notes: "Static Stitch design. Action buttons are visual-only.",
  },
  {
    key: "ocr_review_data_validation",
    route: "/ocr/review",
    slug: "ocr-review-data-validation",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["ocr_results", "validation_queue"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static OCR review layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "OCR review renders",
    status: "visual",
    notes: "Static Stitch design.",
  },
  {
    key: "roles_permissions_control",
    route: "/admin/roles",
    slug: "roles-permissions-control",
    owner: "admin",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["roles", "permissions"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "super_admin",
    hasActivationScript: false,
    emptyStateExpected: "Static roles layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Roles control renders",
    status: "visual",
    notes: "Static Stitch design. Previously had native RolesAdminClient.",
  },
  {
    key: "merge_field_registry",
    route: "/admin/merge-fields",
    slug: "merge-field-registry",
    owner: "admin",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["merge_fields"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "super_admin",
    hasActivationScript: false,
    emptyStateExpected: "Static merge field layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Merge field registry renders with demo fields",
    status: "visual",
    notes: "Contains hard-coded DL-2023-8492. Static Stitch design.",
  },
  {
    key: "borrower_control_record",
    route: "/borrowers/control-record",
    slug: "borrower-control-record",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["borrowers", "compliance"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static borrower control record",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Borrower control record renders with demo data",
    status: "visual",
    notes: "Contains demo Highland Capital + DL-9210. Static Stitch design.",
  },
  {
    key: "credit_committee_view",
    route: "/credit/committee",
    slug: "credit-committee-view",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["deals", "committee_votes", "snapshots"],
    apiCallsExpected: [],
    writeActionsExpected: ["cast_vote"],
    permissionModel: "bank_member + committee_role",
    hasActivationScript: false,
    emptyStateExpected: "Static committee overview",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Credit committee overview renders with demo Project Atlas data",
    status: "visual",
    notes: "Contains demo Project Atlas / Titan Equities / DL-24901 data.",
  },
  {
    key: "borrower_task_inbox",
    route: "/deals/[dealId]/portal-inbox",
    slug: "borrower-task-inbox",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["borrower_tasks", "deal"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    emptyStateExpected: "Static task inbox layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Borrower task inbox renders; deal-scoped",
    status: "visual",
    notes: "Static Stitch design. Needs activation script for deal-specific tasks.",
  },
  {
    key: "borrower_document_upload_inbox",
    route: "/deals/[dealId]/borrower-inbox",
    slug: "borrower-document-upload-review",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["borrower_uploads", "deal"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    emptyStateExpected: "Static upload inbox layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Borrower upload inbox renders; deal-scoped",
    status: "visual",
    notes: "Shares slug with borrower_portal but at a different route. No activation script for this route.",
  },
  {
    key: "borrower_profile",
    route: "/deals/[dealId]/borrower",
    slug: "borrower-profile",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["borrower", "deal"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    emptyStateExpected: "Static borrower profile layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Borrower profile renders; deal-scoped",
    status: "visual",
    notes: "Static Stitch design.",
  },
  {
    key: "pricing_memo_command_center",
    route: "/deals/[dealId]/pricing-memo",
    slug: "pricing-memo-command-center",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "pricing_scenarios", "pricing_decisions"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    emptyStateExpected: "Static pricing memo layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Pricing memo renders; deal-scoped",
    status: "visual",
    notes: "Static Stitch design. Previously had native PricingMemoCommandCenterClient.",
  },
  {
    key: "credit_memo_pdf_template",
    route: "/deals/[dealId]/memo-template",
    slug: "credit-memo-pdf-template",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "credit_memo", "financial_snapshot"],
    apiCallsExpected: [],
    writeActionsExpected: ["export_pdf"],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    emptyStateExpected: "Static memo template layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Credit memo template renders with demo Beacon Capital data",
    status: "visual",
    notes: "Contains demo Beacon Capital / Michael Davis data. Static Stitch design.",
  },
  {
    key: "deal_output_credit_memo_spreads",
    route: "/deals/[dealId]/memos/new",
    slug: "deal-output-credit-memo-spreads",
    owner: "banker",
    required: true,
    integrationType: "visual_only",
    routeParamsNeeded: ["dealId"],
    dataDependencies: ["deal", "credit_memo", "spreads"],
    apiCallsExpected: [],
    writeActionsExpected: ["generate_memo"],
    permissionModel: "bank_member + deal_access",
    hasActivationScript: false,
    emptyStateExpected: "Static memo output layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Memo spreads output renders with demo Project Atlas data",
    status: "visual",
    notes: "Contains demo Project Atlas / Titan Equities / DL-24901 data.",
  },

  // ══════════════════════════════════════════════════════════════
  // OPTIONAL — Recovery routes
  // ══════════════════════════════════════════════════════════════
  {
    key: "deals_pipeline_recovery",
    route: "/stitch-recovery/deals",
    slug: "deals-pipeline-command-center",
    owner: "banker",
    required: false,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["deals"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static deals pipeline layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Recovery route renders pipeline view",
    status: "visual",
    notes: "Recovery route — compare with native /deals before promoting.",
  },
  {
    key: "deal_intake_recovery",
    route: "/stitch-recovery/deals-new",
    slug: "deal-intake-console",
    owner: "banker",
    required: false,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: ["deals"],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "bank_member",
    hasActivationScript: false,
    emptyStateExpected: "Static intake layout",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Recovery route renders intake view",
    status: "visual",
    notes: "Recovery route — compare with native /deals/new before promoting.",
  },
  {
    key: "stitch_login",
    route: "/stitch-login",
    slug: "stitch_buddy_login_page",
    owner: "borrower",
    required: false,
    integrationType: "visual_only",
    routeParamsNeeded: [],
    dataDependencies: [],
    apiCallsExpected: [],
    writeActionsExpected: [],
    permissionModel: "public",
    hasActivationScript: false,
    emptyStateExpected: "Login shell",
    errorStateExpected: "Stitch bridge error card",
    successCriteria: "Login page renders branded Stitch shell",
    status: "visual",
    notes: "Recovery route — does not replace Clerk auth.",
  },
];

/** Lookup by surface key */
export function getWiringEntry(key: string): SurfaceWiringEntry | undefined {
  return SURFACE_WIRING_LEDGER.find((e) => e.key === key);
}

/** Summary counts */
export function getWiringSummary() {
  const total = SURFACE_WIRING_LEDGER.length;
  const wired = SURFACE_WIRING_LEDGER.filter((e) => e.status === "wired").length;
  const visual = SURFACE_WIRING_LEDGER.filter((e) => e.status === "visual").length;
  const partial = SURFACE_WIRING_LEDGER.filter((e) => e.status === "partial").length;
  const broken = SURFACE_WIRING_LEDGER.filter((e) => e.status === "broken").length;
  const unverified = SURFACE_WIRING_LEDGER.filter((e) => e.status === "unverified").length;
  const required = SURFACE_WIRING_LEDGER.filter((e) => e.required).length;
  const withActivation = SURFACE_WIRING_LEDGER.filter((e) => e.hasActivationScript).length;

  return { total, wired, visual, partial, broken, unverified, required, withActivation };
}
