import "server-only";

// src/lib/feasibility/feasibilityRenderer.ts
// Phase God Tier Feasibility — PDF Renderer (step 10/16).
// Follows the same PDFKit patterns as src/lib/sba/sbaPackageRenderer.ts:
// same constants, same DocState threading, same Promise<Buffer> return.
// The orchestrator uploads the buffer to Supabase storage; we do not
// handle storage here (matches the SBA renderer contract).

import PDFDocument from "pdfkit";
import type {
  ComparativeAnalysisResult,
  CompositeFeasibilityScore,
  DimensionScore,
  FeasibilityNarratives,
  FinancialViabilityScore,
  LocationSuitabilityScore,
  MarketDemandScore,
  MarketFlag,
  OperationalReadinessScore,
} from "./types";

// ─── Constants (mirrors sbaPackageRenderer) ──────────────────────────────

const FONT_NORMAL = "Helvetica";
const FONT_BOLD = "Helvetica-Bold";
const FONT_SIZE_BODY = 10;
const FONT_SIZE_HEADER = 11;
const FONT_SIZE_TITLE = 16;
const FONT_SIZE_SECTION = 14;
const FONT_SIZE_SMALL = 7;
const PAGE_MARGIN = 40;
const HEADER_HEIGHT = 50;
const FOOTER_HEIGHT = 40;
const ROW_HEIGHT = 16;

const BRAND_NAVY = "#0f1e3c";

// Score → color tier (same thresholds as the recommendation rubric).
function scoreColor(score: number): string {
  if (score >= 80) return "#16a34a"; // green — Strongly Recommended
  if (score >= 65) return "#2563eb"; // blue — Recommended
  if (score >= 50) return "#d97706"; // amber — Conditionally Feasible
  if (score >= 35) return "#ea580c"; // orange — Significant Concerns
  return "#dc2626"; // red — Not Recommended
}

const DISCLAIMER =
  "This feasibility study is an analytical assessment based on available data at the time of preparation and does not constitute a guarantee of business success or a commitment to lend. " +
  "Scores are derived from deterministic scoring models; narratives are generated by AI and reviewed by the assigned analyst. " +
  "All projections, demographics, and market data are subject to change.";

// ─── Input + DocState ────────────────────────────────────────────────────

export interface FeasibilityRenderInput {
  dealName: string;
  city: string | null;
  state: string | null;
  composite: CompositeFeasibilityScore;
  marketDemand: MarketDemandScore;
  financialViability: FinancialViabilityScore;
  operationalReadiness: OperationalReadinessScore;
  locationSuitability: LocationSuitabilityScore;
  narratives: FeasibilityNarratives;
  franchiseComparison: ComparativeAnalysisResult | null;
  isFranchise: boolean;
  brandName: string | null;
  generatedAt?: string;
  /** Sprint 3: when true, stamps a cosmetic preview watermark on every page. */
  previewWatermark?: boolean;
}

type DocState = {
  doc: PDFKit.PDFDocument;
  y: number;
  pageNum: number;
  input: FeasibilityRenderInput;
};

// ─── Page chrome ─────────────────────────────────────────────────────────

function drawPageHeader(s: DocState, sectionTitle: string) {
  const { doc, input } = s;
  const rightEdge = doc.page.width - PAGE_MARGIN;

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_TITLE).fillColor(BRAND_NAVY);
  doc.text("Feasibility Study", PAGE_MARGIN, PAGE_MARGIN, {
    width: rightEdge - PAGE_MARGIN,
  });

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_HEADER).fillColor("#000000");
  doc.text(input.dealName, PAGE_MARGIN, PAGE_MARGIN + 18);
  const locationStr = input.city
    ? `${input.city}${input.state ? `, ${input.state}` : ""}`
    : input.state ?? "";
  if (locationStr) {
    doc.text(locationStr, rightEdge - 200, PAGE_MARGIN + 18, {
      width: 200,
      align: "right",
    });
  }

  const ruleY = PAGE_MARGIN + HEADER_HEIGHT - 4;
  doc
    .moveTo(PAGE_MARGIN, ruleY)
    .lineTo(rightEdge, ruleY)
    .lineWidth(0.5)
    .stroke("#333333");

  s.y = PAGE_MARGIN + HEADER_HEIGHT + 4;

  if (sectionTitle) {
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_SECTION).fillColor(BRAND_NAVY);
    doc.text(sectionTitle, PAGE_MARGIN, s.y);
    doc.fillColor("#000000");
    s.y += 22;
  }
}

function drawPageFooter(s: DocState) {
  const { doc } = s;
  const bottomY = doc.page.height - FOOTER_HEIGHT;
  const rightEdge = doc.page.width - PAGE_MARGIN;

  doc
    .moveTo(PAGE_MARGIN, bottomY)
    .lineTo(rightEdge, bottomY)
    .lineWidth(0.3)
    .stroke("#999999");

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_SMALL).fillColor("#555555");
  doc.text(DISCLAIMER, PAGE_MARGIN, bottomY + 4, {
    width: rightEdge - PAGE_MARGIN - 60,
    lineGap: 1,
  });
  doc.text(`Page ${s.pageNum}`, rightEdge - 50, bottomY + 4, {
    width: 50,
    align: "right",
  });
  doc.fillColor("#000000");
}

function newPage(s: DocState, sectionTitle: string) {
  drawPageFooter(s);
  s.doc.addPage();
  s.pageNum++;
  drawPageHeader(s, sectionTitle);
}

function checkPageBreak(s: DocState, needed: number, sectionTitle: string) {
  const bottomLimit = s.doc.page.height - FOOTER_HEIGHT - 20;
  if (s.y + needed > bottomLimit) newPage(s, sectionTitle);
}

// ─── Reusable blocks ─────────────────────────────────────────────────────

function renderNarrativeBody(
  s: DocState,
  text: string,
  sectionTitle: string,
) {
  if (!text) return;
  const { doc } = s;
  const maxWidth = doc.page.width - PAGE_MARGIN * 2;
  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY).fillColor("#000000");
  const paragraphs = text.split(/\n\n+/);
  for (const p of paragraphs) {
    checkPageBreak(s, 60, sectionTitle);
    doc.text(p.trim(), PAGE_MARGIN, s.y, {
      width: maxWidth,
      lineGap: 3,
    });
    s.y = doc.y + 6;
  }
}

function renderScoreBar(
  s: DocState,
  label: string,
  score: number,
  width: number,
) {
  const { doc } = s;
  const barH = 18;
  const x = PAGE_MARGIN;

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY).fillColor("#000000");
  doc.text(label, x, s.y, { width: 180 });
  doc.font(FONT_NORMAL);
  doc.text(`${score}/100`, x + width - 50, s.y, {
    width: 50,
    align: "right",
  });
  s.y += 14;

  // Track
  doc.rect(x, s.y, width, barH).fill("#e5e7eb");
  // Fill
  const fillW = Math.max(2, Math.round((score / 100) * width));
  doc.rect(x, s.y, fillW, barH).fill(scoreColor(score));
  doc.fillColor("#000000");
  s.y += barH + 10;
}

function renderDimensionDetail(
  s: DocState,
  label: string,
  dim: DimensionScore,
) {
  const { doc } = s;
  checkPageBreak(s, 40, "");

  const maxWidth = doc.page.width - PAGE_MARGIN * 2;
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY).fillColor("#000000");
  doc.text(`${label}: ${dim.score}/100`, PAGE_MARGIN, s.y);
  s.y += 14;
  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_SMALL).fillColor("#6b7280");
  doc.text(`Source: ${dim.dataSource}`, PAGE_MARGIN, s.y, {
    width: maxWidth,
  });
  s.y += 10;
  doc.fontSize(FONT_SIZE_BODY).fillColor("#000000");
  doc.text(dim.detail, PAGE_MARGIN, s.y, { width: maxWidth, lineGap: 2 });
  s.y = doc.y + 8;
}

function renderFlagList(s: DocState, flags: MarketFlag[]) {
  if (!flags.length) return;
  const { doc } = s;
  const maxWidth = doc.page.width - PAGE_MARGIN * 2;
  for (const f of flags) {
    checkPageBreak(s, 40, "");
    const badge =
      f.severity === "critical"
        ? "#dc2626"
        : f.severity === "warning"
          ? "#d97706"
          : "#2563eb";
    doc.rect(PAGE_MARGIN, s.y, 3, 14).fill(badge);
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY).fillColor(badge);
    doc.text(
      `${f.severity.toUpperCase()} · ${f.dimension}`,
      PAGE_MARGIN + 10,
      s.y,
      {
        width: maxWidth - 10,
      },
    );
    s.y += 14;
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY).fillColor("#000000");
    doc.text(f.message, PAGE_MARGIN + 10, s.y, {
      width: maxWidth - 10,
      lineGap: 2,
    });
    s.y = doc.y + 8;
  }
}

// ─── Pages ───────────────────────────────────────────────────────────────

function renderCoverPage(s: DocState) {
  const { doc, input } = s;
  const centerX = doc.page.width / 2;
  const rightEdge = doc.page.width - PAGE_MARGIN;

  // Phase 2 — top branding bar (matches SBA business-plan cover)
  doc.rect(0, 0, doc.page.width, 80).fill(BRAND_NAVY);
  doc.font(FONT_BOLD).fontSize(11).fillColor("#ffffff");
  doc.text("BUDDY THE UNDERWRITER", PAGE_MARGIN, 30, {
    width: doc.page.width - PAGE_MARGIN * 2,
  });
  doc.text("FEASIBILITY STUDY", doc.page.width - PAGE_MARGIN - 200, 30, {
    width: 200,
    align: "right",
  });
  doc.fillColor("#000000");

  // Title (shifted down to clear the branding bar)
  doc.font(FONT_BOLD).fontSize(36).fillColor(BRAND_NAVY);
  doc.text("Feasibility Study", PAGE_MARGIN, 140, {
    width: rightEdge - PAGE_MARGIN,
    align: "center",
  });
  doc.font(FONT_NORMAL).fontSize(14).fillColor("#6b7280");
  doc.text(
    "Market Demand · Financial Viability · Operational Readiness · Location Suitability",
    PAGE_MARGIN,
    190,
    { width: rightEdge - PAGE_MARGIN, align: "center" },
  );

  // Borrower + location
  doc.font(FONT_BOLD).fontSize(22).fillColor("#000000");
  doc.text(input.dealName, PAGE_MARGIN, 240, {
    width: rightEdge - PAGE_MARGIN,
    align: "center",
  });
  if (input.city || input.state) {
    doc.font(FONT_NORMAL).fontSize(14).fillColor("#374151");
    doc.text(
      `${input.city ?? ""}${input.city && input.state ? ", " : ""}${input.state ?? ""}`,
      PAGE_MARGIN,
      268,
      { width: rightEdge - PAGE_MARGIN, align: "center" },
    );
  }

  // Composite badge
  const badgeW = 260;
  const badgeH = 140;
  const badgeX = centerX - badgeW / 2;
  const badgeY = 330;
  const color = scoreColor(input.composite.overallScore);
  doc.rect(badgeX, badgeY, badgeW, badgeH).fill(color);
  doc.font(FONT_BOLD).fontSize(56).fillColor("#ffffff");
  doc.text(`${input.composite.overallScore}`, badgeX, badgeY + 18, {
    width: badgeW,
    align: "center",
  });
  doc.fontSize(12);
  doc.text("/ 100 Feasibility", badgeX, badgeY + 82, {
    width: badgeW,
    align: "center",
  });
  doc.fontSize(14);
  doc.text(input.composite.recommendation, badgeX, badgeY + 102, {
    width: badgeW,
    align: "center",
  });

  // Confidence + franchise subtitle
  doc.font(FONT_NORMAL).fontSize(12).fillColor("#000000");
  doc.text(
    `Confidence: ${input.composite.confidenceLevel}${
      input.isFranchise && input.brandName
        ? `  ·  Franchise: ${input.brandName}`
        : ""
    }`,
    PAGE_MARGIN,
    badgeY + badgeH + 22,
    { width: rightEdge - PAGE_MARGIN, align: "center" },
  );

  // Footer
  const footerY = doc.page.height - 100;
  doc.font(FONT_NORMAL).fontSize(9).fillColor("#6b7280");
  const gen = input.generatedAt ?? new Date().toISOString();
  doc.text(
    `Generated ${gen.slice(0, 10)}  ·  Confidential — Prepared for authorized parties only`,
    PAGE_MARGIN,
    footerY,
    { width: rightEdge - PAGE_MARGIN, align: "center" },
  );

  doc.fillColor("#000000");
}

// Phase 2 — radar chart for the 4 dimension scores. Drawn on the
// scorecard page, below the score bars.
function renderRadarChart(s: DocState) {
  const { doc, input } = s;
  const cx = doc.page.width / 2;
  const cy = s.y + 100;
  const radius = 80;

  const dims = [
    { label: "Market", score: input.composite.marketDemand.score },
    { label: "Financial", score: input.composite.financialViability.score },
    { label: "Operations", score: input.composite.operationalReadiness.score },
    { label: "Location", score: input.composite.locationSuitability.score },
  ];

  // Concentric rings at 25 / 50 / 75 / 100
  for (const ring of [25, 50, 75, 100]) {
    const r = (ring / 100) * radius;
    doc.save();
    doc.opacity(0.15);
    const points = dims.map((_, i) => {
      const angle = Math.PI / 2 + (i * Math.PI * 2) / dims.length;
      return { x: cx + r * Math.cos(angle), y: cy - r * Math.sin(angle) };
    });
    doc.moveTo(points[0].x, points[0].y);
    for (let i = 1; i < points.length; i++) {
      doc.lineTo(points[i].x, points[i].y);
    }
    doc.closePath().stroke("#666666");
    doc.restore();
  }

  // Score polygon
  const scorePoints = dims.map((d, i) => {
    const r = (d.score / 100) * radius;
    const angle = Math.PI / 2 + (i * Math.PI * 2) / dims.length;
    return { x: cx + r * Math.cos(angle), y: cy - r * Math.sin(angle) };
  });

  doc.save();
  doc.opacity(0.25);
  doc.moveTo(scorePoints[0].x, scorePoints[0].y);
  for (let i = 1; i < scorePoints.length; i++) {
    doc.lineTo(scorePoints[i].x, scorePoints[i].y);
  }
  doc.closePath().fill(scoreColor(input.composite.overallScore));
  doc.restore();

  doc.moveTo(scorePoints[0].x, scorePoints[0].y);
  for (let i = 1; i < scorePoints.length; i++) {
    doc.lineTo(scorePoints[i].x, scorePoints[i].y);
  }
  doc
    .closePath()
    .lineWidth(2)
    .stroke(scoreColor(input.composite.overallScore));

  // Labels
  const labelOffset = radius + 20;
  for (let i = 0; i < dims.length; i++) {
    const angle = Math.PI / 2 + (i * Math.PI * 2) / dims.length;
    const lx = cx + labelOffset * Math.cos(angle);
    const ly = cy - labelOffset * Math.sin(angle);
    doc.font(FONT_BOLD).fontSize(8).fillColor("#374151");
    doc.text(`${dims[i].label} (${dims[i].score})`, lx - 35, ly - 4, {
      width: 70,
      align: "center",
    });
  }

  doc.fillColor("#000000");
  s.y = cy + radius + 40;
}

// Phase 2 — severity bar rendered above the per-flag list on the
// Risk Assessment page. Proportional widths by severity.
function renderRiskMatrix(s: DocState) {
  const { doc, input } = s;
  const flags = input.composite.allFlags;
  if (!flags.length) return;

  const critical = flags.filter((f) => f.severity === "critical").length;
  const warning = flags.filter((f) => f.severity === "warning").length;
  const info = flags.filter((f) => f.severity === "info").length;
  const total = flags.length;

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY).fillColor("#000000");
  doc.text(
    `Risk Summary: ${critical} critical, ${warning} warning, ${info} informational`,
    PAGE_MARGIN,
    s.y,
  );
  s.y += 20;

  const barW = 300;
  const barH = 12;
  const x = PAGE_MARGIN;

  if (critical > 0) {
    const w = (critical / total) * barW;
    doc.rect(x, s.y, w, barH).fill("#dc2626");
  }
  if (warning > 0) {
    const w = (warning / total) * barW;
    const offset = (critical / total) * barW;
    doc.rect(x + offset, s.y, w, barH).fill("#d97706");
  }
  if (info > 0) {
    const w = (info / total) * barW;
    const offset = ((critical + warning) / total) * barW;
    doc.rect(x + offset, s.y, w, barH).fill("#2563eb");
  }

  doc.fillColor("#000000");
  s.y += barH + 16;
}

function renderScorecardPage(s: DocState) {
  const { doc, input } = s;
  newPage(s, "Feasibility Scorecard");

  const barW = doc.page.width - PAGE_MARGIN * 2;

  renderScoreBar(s, "Market Demand", input.composite.marketDemand.score, barW);
  renderScoreBar(
    s,
    "Financial Viability",
    input.composite.financialViability.score,
    barW,
  );
  renderScoreBar(
    s,
    "Operational Readiness",
    input.composite.operationalReadiness.score,
    barW,
  );
  renderScoreBar(
    s,
    "Location Suitability",
    input.composite.locationSuitability.score,
    barW,
  );

  s.y += 8;
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY).fillColor(BRAND_NAVY);
  doc.text(
    `Composite: ${input.composite.overallScore}/100  ·  ${input.composite.recommendation}`,
    PAGE_MARGIN,
    s.y,
  );
  s.y += 16;
  doc.font(FONT_NORMAL).fillColor("#374151");
  doc.text(
    `Confidence: ${input.composite.confidenceLevel}  ·  Data completeness: ${(input.composite.overallDataCompleteness * 100).toFixed(0)}%`,
    PAGE_MARGIN,
    s.y,
  );
  s.y += 16;
  doc.text(
    `Flags — Critical: ${input.composite.criticalFlags}, Warning: ${input.composite.warningFlags}, Info: ${input.composite.infoFlags}`,
    PAGE_MARGIN,
    s.y,
  );
  s.y += 24;
  doc.fillColor("#000000");

  if (input.composite.dimensionsMissingData.length > 0) {
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY).fillColor("#d97706");
    doc.text("Dimensions with limited data:", PAGE_MARGIN, s.y);
    s.y += 14;
    doc.font(FONT_NORMAL).fillColor("#000000");
    doc.text(
      input.composite.dimensionsMissingData.join(", "),
      PAGE_MARGIN,
      s.y,
      { width: barW },
    );
    s.y = doc.y + 8;
  }

  // Phase 2 — radar chart showing the 4 dimensions at a glance.
  s.y += 8;
  renderRadarChart(s);
}

// ─── Main entry ──────────────────────────────────────────────────────────

/**
 * Diagonal translucent preview watermark. Cosmetic only — real redaction
 * is enforced at the data layer by redactFeasibilityForPreview().
 */
function drawPreviewWatermark(doc: PDFKit.PDFDocument): void {
  doc.save();
  const { width, height } = doc.page;
  const cx = width / 2;
  const cy = height / 2;
  doc.translate(cx, cy).rotate(-30);
  doc.opacity(0.12);
  doc.font("Helvetica-Bold").fontSize(48).fillColor("#1f2937");
  doc.text("PREVIEW — UNLOCKS WHEN YOU PICK A LENDER", -width / 2, -24, {
    width,
    align: "center",
  });
  doc.opacity(1);
  doc.restore();
}

export function renderFeasibilityPDF(
  input: FeasibilityRenderInput,
): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({
      size: "letter",
      margin: PAGE_MARGIN,
      bufferPages: true,
    });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const s: DocState = { doc, y: 0, pageNum: 1, input };

    // Page 1 — Cover
    renderCoverPage(s);

    // Page 2 — Executive Summary
    newPage(s, "Executive Summary");
    renderNarrativeBody(
      s,
      input.narratives.executiveSummary,
      "Executive Summary (cont.)",
    );

    // Page 3 — Feasibility Scorecard
    renderScorecardPage(s);

    // Page 4+ — Market Demand
    newPage(s, "Market Demand Analysis");
    renderDimensionDetail(
      s,
      "Population Adequacy",
      input.marketDemand.populationAdequacy,
    );
    renderDimensionDetail(
      s,
      "Income Alignment",
      input.marketDemand.incomeAlignment,
    );
    renderDimensionDetail(
      s,
      "Competitive Density",
      input.marketDemand.competitiveDensity,
    );
    renderDimensionDetail(s, "Demand Trend", input.marketDemand.demandTrend);
    checkPageBreak(s, 80, "Market Demand Analysis (cont.)");
    renderNarrativeBody(
      s,
      input.narratives.marketDemandNarrative,
      "Market Demand Analysis (cont.)",
    );

    // Financial Viability
    newPage(s, "Financial Viability Analysis");
    renderDimensionDetail(
      s,
      "Debt Service Coverage",
      input.financialViability.debtServiceCoverage,
    );
    renderDimensionDetail(
      s,
      "Break-Even Margin",
      input.financialViability.breakEvenMargin,
    );
    renderDimensionDetail(
      s,
      "Capitalization",
      input.financialViability.capitalizationAdequacy,
    );
    renderDimensionDetail(
      s,
      "Cash Runway",
      input.financialViability.cashRunway,
    );
    renderDimensionDetail(
      s,
      "Downside Resilience",
      input.financialViability.downsideResilience,
    );
    checkPageBreak(s, 80, "Financial Viability Analysis (cont.)");
    renderNarrativeBody(
      s,
      input.narratives.financialViabilityNarrative,
      "Financial Viability Analysis (cont.)",
    );

    // Operational Readiness
    newPage(s, "Operational Readiness Analysis");
    renderDimensionDetail(
      s,
      "Management Experience",
      input.operationalReadiness.managementExperience,
    );
    renderDimensionDetail(
      s,
      "Industry Knowledge",
      input.operationalReadiness.industryKnowledge,
    );
    renderDimensionDetail(
      s,
      "Staffing Readiness",
      input.operationalReadiness.staffingReadiness,
    );
    if (input.isFranchise) {
      renderDimensionDetail(
        s,
        "Franchise Support",
        input.operationalReadiness.franchiseSupport,
      );
    }
    checkPageBreak(s, 80, "Operational Readiness Analysis (cont.)");
    renderNarrativeBody(
      s,
      input.narratives.operationalReadinessNarrative,
      "Operational Readiness Analysis (cont.)",
    );

    // Location Suitability
    newPage(s, "Location Suitability Analysis");
    renderDimensionDetail(
      s,
      "Economic Health",
      input.locationSuitability.economicHealth,
    );
    renderDimensionDetail(
      s,
      "Real Estate Market",
      input.locationSuitability.realEstateMarket,
    );
    renderDimensionDetail(
      s,
      "Access & Visibility",
      input.locationSuitability.accessAndVisibility,
    );
    renderDimensionDetail(
      s,
      "Risk Exposure",
      input.locationSuitability.riskExposure,
    );
    checkPageBreak(s, 80, "Location Suitability Analysis (cont.)");
    renderNarrativeBody(
      s,
      input.narratives.locationSuitabilityNarrative,
      "Location Suitability Analysis (cont.)",
    );

    // Risk Assessment
    newPage(s, "Risk Assessment");
    renderRiskMatrix(s);
    renderFlagList(s, input.composite.allFlags);
    checkPageBreak(s, 80, "Risk Assessment (cont.)");
    renderNarrativeBody(
      s,
      input.narratives.riskAssessment,
      "Risk Assessment (cont.)",
    );

    // Franchise Comparison (franchise deals only)
    if (input.isFranchise && input.narratives.franchiseComparisonNarrative) {
      newPage(s, "Franchise Comparison");
      renderNarrativeBody(
        s,
        input.narratives.franchiseComparisonNarrative,
        "Franchise Comparison (cont.)",
      );
    }

    // Recommendation
    newPage(s, "Recommendation & Conditions");
    renderNarrativeBody(
      s,
      input.narratives.recommendation,
      "Recommendation & Conditions (cont.)",
    );

    // Methodology
    newPage(s, "Methodology & Data Sources");
    doc
      .font(FONT_NORMAL)
      .fontSize(FONT_SIZE_BODY)
      .fillColor("#000000")
      .text(
        "Feasibility is scored across four deterministic dimensions — Market Demand, Financial Viability, Operational Readiness, and Location Suitability — and combined into a weighted composite. Weights differ for franchise deals (operational readiness carries more weight) versus non-franchise deals (financial viability carries more weight). Narratives are generated by Gemini Pro using the deterministic score outputs plus BIE research as the only ground-truth inputs. Scores cannot be moved by the narrative model. Data completeness is reported per dimension. Missing data is surfaced rather than filled with assumptions.",
        PAGE_MARGIN,
        s.y,
        {
          width: doc.page.width - PAGE_MARGIN * 2,
          lineGap: 3,
        },
      );

    // Ensure final page footer is drawn.
    drawPageFooter(s);

    // Silence unused ROW_HEIGHT warning — kept here to match the SBA
    // renderer's constant surface should future rows land on this page.
    void ROW_HEIGHT;

    // Sprint 3: preview watermark applied to every buffered page.
    if (input.previewWatermark) {
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        drawPreviewWatermark(doc);
      }
    }

    doc.end();
  });
}
