import type { FormSpecification } from "../types";

export const SCHEDULE_C_2022: FormSpecification = {
  formType: "SCHEDULE_C",
  taxYear: 2022,
  version: 1,
  description: "Profit or Loss From Business (Sole Proprietorship) — 2022",
  softwareVariants: ["TurboTax", "H&R Block", "ProConnect", "Drake", "TaxAct"],
  fields: [
    {
      canonicalKey: "GROSS_RECEIPTS",
      lineNumbers: ["1"],
      label: "Gross receipts or sales",
      labelVariants: ["Gross receipts", "Revenue", "Sales"],
      requiredForValidation: true,
      nullAsZero: false,
      isEbitdaAddBack: false,
    },
    {
      canonicalKey: "COST_OF_GOODS_SOLD",
      lineNumbers: ["4"],
      label: "Cost of goods sold",
      labelVariants: ["COGS"],
      requiredForValidation: false,
      nullAsZero: true,
      isEbitdaAddBack: false,
    },
    {
      canonicalKey: "GROSS_PROFIT",
      lineNumbers: ["5"],
      label: "Gross profit",
      labelVariants: ["Gross profit"],
      requiredForValidation: true,
      nullAsZero: false,
      isEbitdaAddBack: false,
    },
    {
      canonicalKey: "DEPRECIATION",
      lineNumbers: ["13"],
      label: "Depreciation and section 179 expense deduction",
      labelVariants: ["Depreciation", "Depr & amort"],
      requiredForValidation: false,
      nullAsZero: true,
      isEbitdaAddBack: true,
      notes: "Includes Section 179 on Schedule C. No separate line for 179.",
    },
    {
      canonicalKey: "INTEREST_EXPENSE",
      lineNumbers: ["16b"],
      label: "Interest (mortgage paid to banks)",
      labelVariants: ["Interest", "Interest expense"],
      requiredForValidation: false,
      nullAsZero: true,
      isEbitdaAddBack: true,
    },
    {
      canonicalKey: "RENT_EXPENSE",
      lineNumbers: ["20b"],
      label: "Rent or lease (other business property)",
      labelVariants: ["Rent", "Lease"],
      requiredForValidation: false,
      nullAsZero: true,
      isEbitdaAddBack: false,
    },
    {
      canonicalKey: "OTHER_DEDUCTIONS",
      lineNumbers: ["48"],
      label: "Other expenses",
      labelVariants: ["Other expenses", "Other deductions"],
      requiredForValidation: false,
      nullAsZero: true,
      isEbitdaAddBack: false,
    },
    {
      canonicalKey: "TOTAL_DEDUCTIONS",
      lineNumbers: ["28"],
      label: "Total expenses before expenses for business use of home",
      labelVariants: ["Total expenses"],
      requiredForValidation: true,
      nullAsZero: false,
      isEbitdaAddBack: false,
    },
    {
      canonicalKey: "NET_PROFIT",
      lineNumbers: ["31"],
      label: "Net profit or (loss)",
      labelVariants: ["Net profit", "Net loss", "Net income"],
      requiredForValidation: true,
      nullAsZero: false,
      isEbitdaAddBack: false,
    },
  ],
  identityChecks: [
    {
      id: "SCHC_GROSS_PROFIT",
      description: "Gross Receipts - COGS = Gross Profit",
      lhs: ["GROSS_RECEIPTS"],
      rhs: ["COST_OF_GOODS_SOLD", "GROSS_PROFIT"],
      operator: "=",
      toleranceDollars: 1,
      requiredForValidation: true,
      sourceDescription: "Schedule C Lines 1, 4, 5",
    },
    {
      id: "SCHC_NET_PROFIT",
      description: "Gross Profit - Total Expenses = Net Profit",
      lhs: ["GROSS_PROFIT"],
      rhs: ["TOTAL_DEDUCTIONS", "NET_PROFIT"],
      operator: "=",
      toleranceDollars: 5,  // Home office, meals, and other partial deductions create minor rounding
      requiredForValidation: true,
      sourceDescription: "Schedule C Lines 5, 28, 31",
    },
  ],
  ebitdaAddBackKeys: ["INTEREST_EXPENSE", "DEPRECIATION", "AMORTIZATION"],
};

export function getScheduleCSpec(taxYear: number): FormSpecification {
  return { ...SCHEDULE_C_2022, taxYear };
}
