import PDFDocument from "pdfkit";
import type {
  CashFlowRow,
  ClassicSpreadInput,
  FinancialRow,
  GlobalCashFlowSection,
  RatioSection,
  StatementPeriod,
} from "./types";
import type { PersonalIncomeSection, PersonalIncomeYear } from "./personalIncomeLoader";
import type { SpreadNarrative } from "./narrativeEngine";
import { sanitizeForPdf } from "./pdfText";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const FONT_NORMAL = "Helvetica";
const FONT_BOLD = "Helvetica-Bold";
const FONT_SIZE_BODY = 8;
const FONT_SIZE_HEADER = 9;
const FONT_SIZE_TITLE = 11;
const FONT_SIZE_META = 7;
// SPEC-CLASSIC-SPREAD-5COL-LAYOUT-1:
// Dynamic column widths based on period count.
// Letter portrait usable = 612 - 2×36 = 540pt.
//   4 cols: 165 + 4 × (60 + 30) = 525pt ✓
//   5 cols: 140 + 5 × (52 + 26) = 530pt ✓
function computeLayout(periodCount: number) {
  if (periodCount >= 5) {
    return { label: 140, value: 52, pct: 26 };
  }
  return { label: 165, value: 60, pct: 30 };
}

// Default layout for 4 or fewer periods (used as fallback).
const DEFAULT_LAYOUT: LayoutConfig = { label: 165, value: 60, pct: 30 };
const ROW_HEIGHT = 12;
const PAGE_MARGIN = 36;
const HEADER_HEIGHT = 56;
const FOOTER_HEIGHT = 50;

const DOUBLE_RULE_LABELS = new Set([
  "TOTAL ASSETS",
  "TOTAL LIABILITIES & NET WORTH",
  "NET PROFIT",
  "EBITDA",
  "CASH FROM OPERATIONS (UCA)",
  "CASH AVAILABLE FOR DEBT SERVICE",
]);

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------

function fmtNumber(val: number | null, isNegative?: boolean): string {
  // SPEC-CLASSIC-SPREAD-SYSTEM-HARDENING-AUDIT-2 #6: distinguish true zero from missing. `null`
  // (missing/blocked) renders as an em dash; a genuine reported `0` renders as "0" \u2014 never collapse
  // a real zero to a blank.
  if (val == null) return "\u2014"; // em dash \u2014 missing
  if (val === 0) return "0"; // true zero
  let n = isNegative ? -val : val;
  if (n < 0) {
    return `(${Math.abs(n).toLocaleString("en-US", { maximumFractionDigits: 0 })})`;
  }
  return n.toLocaleString("en-US", { maximumFractionDigits: 0 });
}

function fmtPct(val: number | null, base: number | null): string {
  if (val == null || base == null || base === 0) return "\u2014";
  const pct = (val / base) * 100;
  if (pct < 0) {
    return `(${Math.abs(pct).toFixed(1)})`;
  }
  return pct.toFixed(1);
}

function fmtRatioValue(val: number | string | null, format: string, decimals: number): string {
  if (val === "N/A") return "N/A";
  if (val == null) return "\u2014";
  if (typeof val === "string") return val;

  switch (format) {
    case "currency":
      if (val === 0) return "0"; // #6: true zero, not a blank
      if (val < 0) return `(${Math.abs(val).toLocaleString("en-US", { maximumFractionDigits: 0 })})`;
      return val.toLocaleString("en-US", { maximumFractionDigits: 0 });
    case "percent":
      if (val < 0) return `(${Math.abs(val).toFixed(decimals)})`;
      return val.toFixed(decimals);
    case "ratio":
      if (val < 0) return `(${Math.abs(val).toFixed(decimals)})`;
      return val.toFixed(decimals);
    case "days":
      if (val < 0) return `(${Math.abs(val).toFixed(decimals)})`;
      return val.toFixed(decimals);
    default:
      return val.toFixed(decimals);
  }
}

// ---------------------------------------------------------------------------
// PDF Document helpers
// ---------------------------------------------------------------------------

type LayoutConfig = { label: number; value: number; pct: number };

type DocState = {
  doc: PDFKit.PDFDocument;
  y: number;
  pageNum: number;
  input: ClassicSpreadInput;
  pageTitle: string;
  periods: StatementPeriod[];
  showPctColumns: boolean;
  layout: LayoutConfig;
};

function drawPageHeader(s: DocState) {
  const { doc, input } = s;
  const rightEdge = doc.page.width - PAGE_MARGIN;

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_TITLE);
  doc.text(input.companyName.toUpperCase(), PAGE_MARGIN, PAGE_MARGIN, { width: rightEdge - PAGE_MARGIN });

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_HEADER);
  doc.text(s.pageTitle, PAGE_MARGIN, PAGE_MARGIN + 14, { width: 300 });
  doc.text("Generated by Buddy", rightEdge - 150, PAGE_MARGIN + 14, { width: 150, align: "right" });

  let naicsLine = "";
  if (input.naicsCode) {
    naicsLine = `NAICS: ${input.naicsCode}`;
    if (input.naicsDescription) naicsLine += ` \u2014 ${input.naicsDescription}`;
  }
  doc.fontSize(FONT_SIZE_META);
  if (naicsLine) {
    doc.text(naicsLine, PAGE_MARGIN, PAGE_MARGIN + 28, { width: 350 });
  }
  doc.text(input.preparedDate, rightEdge - 150, PAGE_MARGIN + 28, { width: 150, align: "right" });

  // Horizontal rule below header
  const ruleY = PAGE_MARGIN + HEADER_HEIGHT - 4;
  doc.moveTo(PAGE_MARGIN, ruleY).lineTo(rightEdge, ruleY).lineWidth(0.5).stroke("#333333");

  s.y = PAGE_MARGIN + HEADER_HEIGHT;
}

function drawPageFooter(s: DocState) {
  const { doc, input } = s;
  const rightEdge = doc.page.width - PAGE_MARGIN;
  const footerTop = doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT + 8;

  // Thin rule above footer
  doc.moveTo(PAGE_MARGIN, footerTop).lineTo(rightEdge, footerTop).lineWidth(0.3).stroke("#999999");

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#666666");
  doc.text(`Page ${s.pageNum}`, PAGE_MARGIN, footerTop + 6, { width: 100, lineBreak: false });
  doc.text("Buddy The Underwriter", rightEdge - 160, footerTop + 6, { width: 160, align: "right", lineBreak: false });

  let naicsLine = input.companyName;
  if (input.naicsCode) {
    naicsLine += `          NAICS ${input.naicsCode}`;
    if (input.naicsDescription) naicsLine += ` \u2014 ${input.naicsDescription}`;
  }
  doc.text(naicsLine, PAGE_MARGIN, footerTop + 16, { width: rightEdge - PAGE_MARGIN, lineBreak: false });
  doc.text("Confidential \u2014 For Internal Use Only", PAGE_MARGIN, footerTop + 26, { width: rightEdge - PAGE_MARGIN, align: "center", lineBreak: false });

  doc.fillColor("#000000"); // reset
}

function newPage(s: DocState) {
  drawPageFooter(s);
  s.doc.addPage();
  s.pageNum++;
  drawPageHeader(s);
}

function checkPageBreak(s: DocState, rowsNeeded: number = 1) {
  const maxY = s.doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT - 10;
  if (s.y + rowsNeeded * ROW_HEIGHT > maxY) {
    newPage(s);
  }
}

// ---------------------------------------------------------------------------
// Statement Metadata Row
// ---------------------------------------------------------------------------

function drawMetadataGrid(s: DocState) {
  const { doc, periods } = s;
  const metaRows = ["Statement Date", "Months Covered", "Audit Method", "Stmt Type"];
  const metaFns: ((p: StatementPeriod) => string)[] = [
    (p) => p.date,
    (p) => String(p.months),
    (p) => p.auditMethod,
    (p) => p.stmtType,
  ];

  doc.fontSize(FONT_SIZE_META);

  for (let r = 0; r < metaRows.length; r++) {
    const rowY = s.y;

    // Label cell (gray bg)
    doc.rect(PAGE_MARGIN, rowY, s.layout.label, ROW_HEIGHT).fill("#f0f0f0");
    doc.fillColor("#000000").font(FONT_BOLD).fontSize(FONT_SIZE_META);
    doc.text(metaRows[r]!, PAGE_MARGIN + 4, rowY + 2, { width: s.layout.label - 8 });

    // Value cells
    doc.font(FONT_NORMAL);
    let x = PAGE_MARGIN + s.layout.label;
    for (let c = 0; c < periods.length; c++) {
      const colW = s.showPctColumns ? s.layout.value + s.layout.pct : s.layout.value;
      const val = metaFns[r]!(periods[c]!);
      doc.text(val, x + 2, rowY + 2, { width: colW - 4, align: "center" });
      x += colW;
    }

    // Light line
    doc.moveTo(PAGE_MARGIN, rowY + ROW_HEIGHT)
      .lineTo(x, rowY + ROW_HEIGHT)
      .lineWidth(0.2).stroke("#cccccc");

    s.y += ROW_HEIGHT;
  }

  s.y += 4; // gap after metadata
}

// ---------------------------------------------------------------------------
// Column Headers
// ---------------------------------------------------------------------------

function drawColumnHeaders(s: DocState) {
  const { doc, periods } = s;
  const rowY = s.y;

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
  doc.text("LINE ITEM", PAGE_MARGIN + 4, rowY + 2, { width: s.layout.label - 8 });

  let x = PAGE_MARGIN + s.layout.label;
  for (const p of periods) {
    doc.text(p.label, x, rowY + 2, { width: s.layout.value, align: "right" });
    x += s.layout.value;
    if (s.showPctColumns) {
      doc.text("%", x, rowY + 2, { width: s.layout.pct, align: "right" });
      x += s.layout.pct;
    }
  }

  // Underline
  doc.moveTo(PAGE_MARGIN, rowY + ROW_HEIGHT)
    .lineTo(x, rowY + ROW_HEIGHT)
    .lineWidth(0.5).stroke("#333333");

  s.y = rowY + ROW_HEIGHT + 2;
}

// ---------------------------------------------------------------------------
// Financial Row Rendering
// ---------------------------------------------------------------------------

function drawFinancialRow(s: DocState, row: FinancialRow) {
  if (!row.label && row.values.every((v) => v == null)) {
    s.y += 4; // spacer row
    return;
  }

  checkPageBreak(s);
  const { doc, periods } = s;
  const rowY = s.y;
  const rightEdge = PAGE_MARGIN + s.layout.label +
    periods.length * (s.layout.value + (s.showPctColumns && row.showPct ? s.layout.pct : 0));

  // Double rule before certain totals
  if (DOUBLE_RULE_LABELS.has(row.label)) {
    doc.moveTo(PAGE_MARGIN, rowY - 1).lineTo(rightEdge, rowY - 1).lineWidth(0.3).stroke("#666666");
    doc.moveTo(PAGE_MARGIN, rowY + 1).lineTo(rightEdge, rowY + 1).lineWidth(0.3).stroke("#666666");
    s.y += 3;
  }

  // Section header: gray background band
  if (row.indent === 0 && row.isBold && row.values.every((v) => v == null)) {
    doc.rect(PAGE_MARGIN, s.y, rightEdge - PAGE_MARGIN, ROW_HEIGHT).fill("#f5f5f5");
    doc.fillColor("#000000");
  }

  // Label
  const indent = row.indent * 12;
  doc.font(row.isBold ? FONT_BOLD : FONT_NORMAL).fontSize(FONT_SIZE_BODY);
  doc.text(row.label, PAGE_MARGIN + 4 + indent, s.y + 2, { width: s.layout.label - 8 - indent });

  // Values
  let x = PAGE_MARGIN + s.layout.label;
  for (let i = 0; i < periods.length; i++) {
    const val = row.values[i] ?? null;
    const display = fmtNumber(val, row.isNegative);
    doc.font(row.isBold ? FONT_BOLD : FONT_NORMAL).fontSize(FONT_SIZE_BODY);
    doc.text(display, x, s.y + 2, { width: s.layout.value - 4, align: "right" });
    x += s.layout.value;

    if (s.showPctColumns && row.showPct) {
      const base = row.pctBase?.[i] ?? null;
      const pctDisplay = fmtPct(val, base);
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META);
      doc.text(pctDisplay, x, s.y + 2, { width: s.layout.pct - 4, align: "right" });
      x += s.layout.pct;
    }
  }

  // Light horizontal rule
  doc.moveTo(PAGE_MARGIN, s.y + ROW_HEIGHT)
    .lineTo(x, s.y + ROW_HEIGHT)
    .lineWidth(0.15).stroke("#dddddd");

  s.y += ROW_HEIGHT;
}

// ---------------------------------------------------------------------------
// Cash Flow Row Rendering (no % columns)
// ---------------------------------------------------------------------------

function drawCashFlowRow(s: DocState, row: CashFlowRow) {
  if (!row.label && row.values.every((v) => v == null)) {
    s.y += 4; // spacer row
    return;
  }

  checkPageBreak(s);
  const { doc, periods } = s;
  const rightEdge = PAGE_MARGIN + s.layout.label + periods.length * s.layout.value;

  // Double rule before key totals
  if (DOUBLE_RULE_LABELS.has(row.label)) {
    doc.moveTo(PAGE_MARGIN, s.y - 1).lineTo(rightEdge, s.y - 1).lineWidth(0.3).stroke("#666666");
    doc.moveTo(PAGE_MARGIN, s.y + 1).lineTo(rightEdge, s.y + 1).lineWidth(0.3).stroke("#666666");
    s.y += 3;
  }

  // Section header: gray background band
  if (row.indent === 0 && row.isBold && row.values.every((v) => v == null)) {
    doc.rect(PAGE_MARGIN, s.y, rightEdge - PAGE_MARGIN, ROW_HEIGHT).fill("#f5f5f5");
    doc.fillColor("#000000");
  }

  // Label
  const indent = row.indent * 12;
  doc.font(row.isBold ? FONT_BOLD : FONT_NORMAL).fontSize(FONT_SIZE_BODY);
  doc.text(row.label, PAGE_MARGIN + 4 + indent, s.y + 2, { width: s.layout.label - 8 - indent });

  // Values (no % columns for cash flow)
  let x = PAGE_MARGIN + s.layout.label;
  for (let i = 0; i < periods.length; i++) {
    const val = row.values[i] ?? null;
    const display = fmtNumber(val, row.isNegative);
    doc.font(row.isBold ? FONT_BOLD : FONT_NORMAL).fontSize(FONT_SIZE_BODY);
    doc.text(display, x, s.y + 2, { width: s.layout.value - 4, align: "right" });
    x += s.layout.value;
  }

  // Light horizontal rule
  doc.moveTo(PAGE_MARGIN, s.y + ROW_HEIGHT)
    .lineTo(x, s.y + ROW_HEIGHT)
    .lineWidth(0.15).stroke("#dddddd");

  s.y += ROW_HEIGHT;
}

// ---------------------------------------------------------------------------
// Narrative Section Rendering
// ---------------------------------------------------------------------------

function drawNarrativeSections(s: DocState, narrative: SpreadNarrative) {
  const { doc } = s;
  const rightEdge = doc.page.width - PAGE_MARGIN;
  const textWidth = rightEdge - PAGE_MARGIN;

  for (const section of narrative.sections) {
    checkPageBreak(s, 6);

    // Section title
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER).fillColor("#333333");
    doc.text(section.title, PAGE_MARGIN, s.y, { width: textWidth });
    s.y += 14;

    // Section body
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY).fillColor("#000000");
    const bodyHeight = doc.heightOfString(section.body, { width: textWidth });
    doc.text(section.body, PAGE_MARGIN, s.y, { width: textWidth });
    s.y += bodyHeight + 12;
  }

  // Attribution
  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#999999");
  doc.text(
    `Generated by ${narrative.model} at ${new Date(narrative.generatedAt).toLocaleString("en-US")}`,
    PAGE_MARGIN,
    s.y,
    { width: textWidth, align: "right", lineBreak: false },
  );
  doc.fillColor("#000000");
  s.y += 12;
}

// ---------------------------------------------------------------------------
// SPEC-CLASSIC-SPREAD-LINE-ACCURACY-COMPLETION-AUDIT-1 — Spread Accuracy & Completion Audit page
// ---------------------------------------------------------------------------

function drawSpreadAuditSection(
  s: DocState,
  audit: NonNullable<NonNullable<ClassicSpreadInput["certificationAudit"]>["spreadAccuracy"]> | null,
  notCertified: boolean = false,
) {
  const { doc } = s;
  const rightEdge = doc.page.width - PAGE_MARGIN;
  const textWidth = rightEdge - PAGE_MARGIN;

  // SPEC-CLASSIC-SPREAD-SYSTEM-HARDENING-AUDIT-2 #9: certification fail-closed banner. If the
  // certification gate could not run/succeed, say so loudly — never present this as certified.
  if (notCertified) {
    doc.rect(PAGE_MARGIN, s.y, textWidth, 22).fill("#dc2626");
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER).fillColor("#ffffff");
    doc.text("NOT CERTIFIED — certification unavailable", PAGE_MARGIN + 8, s.y + 5, { width: textWidth - 16 });
    doc.fillColor("#000000");
    s.y += 30;
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
    doc.text(
      "The certification/accuracy gate did not complete for this spread. Values shown are uncertified and must not be relied upon until certification succeeds.",
      PAGE_MARGIN,
      s.y,
      { width: textWidth },
    );
    s.y += 18;
    if (!audit) return;
  }
  if (!audit) return;

  const statusColor =
    audit.status === "blocker" ? "#dc2626" : audit.status === "warning" ? "#d97706" : "#16a34a";
  const statusLabel =
    audit.status === "blocker" ? "BLOCKER" : audit.status === "warning" ? "WARNING" : "CLEAN";

  // Status badge
  doc.rect(PAGE_MARGIN, s.y, 4, 18).fill(statusColor);
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER).fillColor(statusColor);
  doc.text(`Spread audit: ${statusLabel}`, PAGE_MARGIN + 12, s.y + 4, { width: textWidth - 12 });
  doc.fillColor("#000000");
  s.y += 24;

  // Summary line
  const sm = audit.summary;
  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#444444");
  doc.text(
    sanitizeForPdf(
      `${sm.blockers} blocker(s), ${sm.warnings} warning(s), ${sm.infos} info - ${sm.footingsChecked} footing checks across ${sm.periodsAudited.join(", ") || "no"} period(s); ` +
        `${sm.mappedFactKeys} source line(s) mapped, ${sm.unmappedFactKeys} unmapped.`,
    ),
    PAGE_MARGIN,
    s.y,
    { width: textWidth },
  );
  doc.fillColor("#000000");
  s.y += 18;

  if (audit.status === "clean") {
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
    doc.text(
      "All statements foot and every uploaded financial line is mapped or intentionally ignored. No reconciliation exceptions found.",
      PAGE_MARGIN,
      s.y,
      { width: textWidth },
    );
    s.y += 16;
    return;
  }

  // SPEC-CLASSIC-SPREAD-BLOCKER-BATCH-RESOLUTION-1 #5: action-oriented, concise. Show the grouped
  // action counts and the TOP BLOCKER actions (not every warning).
  const as = audit.actionSummary;
  const byAction = Object.entries(as.byAction).map(([a, n]) => `${a}: ${n}`).join(", ");
  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#444444");
  doc.text(sanitizeForPdf(`Source-review actions: ${as.unresolvedActionCount} unresolved${byAction ? ` (${byAction})` : ""}.`), PAGE_MARGIN, s.y, { width: textWidth });
  doc.fillColor("#000000");
  s.y += 16;

  const blockerActions = as.actions.filter((a) => a.severity === "blocker");
  const warningCount = as.actions.filter((a) => a.severity === "warning").length;
  const MAX_SHOWN = 12;
  const shown = blockerActions.slice(0, MAX_SHOWN);

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY).fillColor("#333333");
  doc.text("Top blocker actions", PAGE_MARGIN, s.y, { width: textWidth });
  doc.fillColor("#000000");
  s.y += 14;

  for (const a of shown) {
    checkPageBreak(s, 3);
    const head = sanitizeForPdf(`[${a.action}] ${a.period} - ${a.statement.replace(/_/g, " ")} - ${a.rowLabel}`);
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_META).fillColor("#dc2626");
    const headHeight = doc.heightOfString(head, { width: textWidth });
    doc.text(head, PAGE_MARGIN, s.y, { width: textWidth });
    s.y += headHeight + 1;

    const body = sanitizeForPdf(a.detail);
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#000000");
    const bodyHeight = doc.heightOfString(body, { width: textWidth - 8 });
    doc.text(body, PAGE_MARGIN + 8, s.y, { width: textWidth - 8 });
    s.y += bodyHeight + 5;
  }

  const extra: string[] = [];
  if (blockerActions.length > MAX_SHOWN) extra.push(`${blockerActions.length - MAX_SHOWN} more blocker action(s)`);
  if (warningCount > 0) extra.push(`${warningCount} warning(s)`);
  if (extra.length > 0) {
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#666666");
    doc.text(sanitizeForPdf(`Plus ${extra.join(" and ")}. See certificationAudit.spreadAccuracy for the full list.`), PAGE_MARGIN, s.y, { width: textWidth });
    doc.fillColor("#000000");
    s.y += 12;
  }
}

// ---------------------------------------------------------------------------
// Ratio Section Rendering
// ---------------------------------------------------------------------------

function drawRatioSections(s: DocState, sections: RatioSection[]) {
  const { doc, periods } = s;

  for (const section of sections) {
    checkPageBreak(s, 2);

    // Section title: gray band
    const rightEdge = PAGE_MARGIN + s.layout.label + periods.length * s.layout.value;
    doc.rect(PAGE_MARGIN, s.y, rightEdge - PAGE_MARGIN, ROW_HEIGHT).fill("#f0f0f0");
    doc.fillColor("#000000");
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
    doc.text(section.title, PAGE_MARGIN + 4, s.y + 2, { width: s.layout.label - 8 });
    s.y += ROW_HEIGHT;

    for (const row of section.rows) {
      checkPageBreak(s);

      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
      doc.text(row.label, PAGE_MARGIN + 16, s.y + 2, { width: s.layout.label - 20 });

      let x = PAGE_MARGIN + s.layout.label;
      for (let i = 0; i < periods.length; i++) {
        const val = row.values[i] ?? null;
        const display = fmtRatioValue(val, row.format, row.decimals);
        doc.text(display, x, s.y + 2, { width: s.layout.value - 4, align: "right" });
        x += s.layout.value;
      }

      doc.moveTo(PAGE_MARGIN, s.y + ROW_HEIGHT)
        .lineTo(x, s.y + ROW_HEIGHT)
        .lineWidth(0.15).stroke("#dddddd");

      s.y += ROW_HEIGHT;
    }

    s.y += 6; // gap between sections
  }
}

// ---------------------------------------------------------------------------
// Global Cash Flow Page
// ---------------------------------------------------------------------------

function fmtCurrency(val: number | null): string {
  if (val == null) return "\u2014";
  if (val < 0) return `($${Math.abs(val).toLocaleString("en-US", { maximumFractionDigits: 0 })})`;
  return `$${val.toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
}

// ---------------------------------------------------------------------------
// SPEC-B4 — Methodology Block (on GCF page)
// ---------------------------------------------------------------------------

function renderMethodologyBlock(
  doc: PDFKit.PDFDocument,
  gcf: GlobalCashFlowSection,
  startY: number,
): number {
  if (!gcf.methodology || gcf.methodology.length === 0) return startY;

  // Skip Axis 5 (living_expense) — too detail-heavy for PDF; lives in picker only
  const visibleEntries = gcf.methodology.filter((m) => m.axisId !== "living_expense");
  if (visibleEntries.length === 0) return startY;

  const rightEdge = doc.page.width - PAGE_MARGIN;
  const contentWidth = rightEdge - PAGE_MARGIN;
  let y = startY;

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER).fillColor("#333333");
  doc.text("METHODOLOGY", PAGE_MARGIN, y, { width: contentWidth });
  y += 14;

  doc.moveTo(PAGE_MARGIN, y).lineTo(rightEdge, y).lineWidth(0.3).stroke("#cccccc");
  y += 6;

  doc.fillColor("#000000");
  for (const entry of visibleEntries) {
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
    const heading = `${entry.axisLabel}: ${entry.chosenVariantLabel}`;
    doc.text(heading, PAGE_MARGIN + 8, y + 2, { width: contentWidth - 8 });
    y += ROW_HEIGHT;

    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#666666");
    const rationaleHeight = doc.heightOfString(entry.rationale, { width: contentWidth - 16 });
    doc.text(entry.rationale, PAGE_MARGIN + 16, y + 1, { width: contentWidth - 16 });
    y += rationaleHeight + 4;
    doc.fillColor("#000000");
  }

  return y + 8;
}

function renderGlobalCashFlowPage(
  doc: PDFKit.PDFDocument,
  input: ClassicSpreadInput,
  gcf: GlobalCashFlowSection,
  pageNum: number,
): number {
  const rightEdge = doc.page.width - PAGE_MARGIN;
  const contentWidth = rightEdge - PAGE_MARGIN;
  const labelWidth = 300;
  const valueX = rightEdge - 120;
  const valueWidth = 120;
  let y = PAGE_MARGIN;

  // ── Header bar ──────────────────────────────────────────────────────────
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_TITLE);
  doc.text(input.companyName.toUpperCase(), PAGE_MARGIN, y, { width: contentWidth });

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_HEADER);
  doc.text("Global Cash Flow Analysis", PAGE_MARGIN, y + 14, { width: 300 });
  doc.text("Generated by Buddy", rightEdge - 150, y + 14, { width: 150, align: "right" });

  doc.fontSize(FONT_SIZE_META);
  if (gcf.taxYear) {
    doc.text(`Tax Year: ${gcf.taxYear}`, PAGE_MARGIN, y + 28, { width: 350 });
  }
  doc.text(input.preparedDate, rightEdge - 150, y + 28, { width: 150, align: "right" });

  const ruleY = y + HEADER_HEIGHT - 4;
  doc.moveTo(PAGE_MARGIN, ruleY).lineTo(rightEdge, ruleY).lineWidth(0.5).stroke("#333333");
  y = ruleY + 12;

  // ── Section: Entity Cash Flow ───────────────────────────────────────────
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER).fillColor("#333333");
  doc.text("ENTITY CASH FLOW", PAGE_MARGIN, y, { width: contentWidth });
  y += 14;

  doc.moveTo(PAGE_MARGIN, y).lineTo(rightEdge, y).lineWidth(0.3).stroke("#cccccc");
  y += 4;

  if (gcf.entityCashFlowAvailable != null) {
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY).fillColor("#000000");
    doc.text("Entity Cash Flow Available", PAGE_MARGIN + 8, y + 2, { width: labelWidth });
    doc.font(FONT_BOLD);
    doc.text(fmtCurrency(gcf.entityCashFlowAvailable), valueX, y + 2, { width: valueWidth, align: "right" });
    y += ROW_HEIGHT;

    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#666666");
    doc.text(`(from ${gcf.entityCount} operating ${gcf.entityCount === 1 ? "entity" : "entities"})`, PAGE_MARGIN + 20, y + 1, { width: labelWidth });
    doc.fillColor("#000000");
    y += ROW_HEIGHT;
  } else {
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY).fillColor("#999999");
    doc.text("Entity data not yet computed \u2014 re-run spread pipeline", PAGE_MARGIN + 8, y + 2, { width: contentWidth });
    doc.fillColor("#000000");
    y += ROW_HEIGHT + 4;
  }

  y += 8;

  // ── Section: Sponsor Contributions ──────────────────────────────────────
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER).fillColor("#333333");
  doc.text("SPONSOR CONTRIBUTIONS", PAGE_MARGIN, y, { width: contentWidth });
  y += 14;

  doc.moveTo(PAGE_MARGIN, y).lineTo(rightEdge, y).lineWidth(0.3).stroke("#cccccc");
  y += 4;

  if (gcf.sponsors.length > 0) {
    for (const sponsor of gcf.sponsors) {
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY).fillColor("#000000");
      doc.text(sponsor.displayName, PAGE_MARGIN + 8, y + 2, { width: labelWidth });
      doc.text(fmtCurrency(sponsor.personalCashAvailable), valueX, y + 2, { width: valueWidth, align: "right" });
      y += ROW_HEIGHT;
    }
  } else {
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY).fillColor("#999999");
    doc.text("No personal financial data \u2014 re-extract personal tax returns", PAGE_MARGIN + 8, y + 2, { width: contentWidth });
    doc.fillColor("#000000");
    y += ROW_HEIGHT + 4;
  }

  y += 12;

  // ── Divider ─────────────────────────────────────────────────────────────
  doc.moveTo(PAGE_MARGIN, y).lineTo(rightEdge, y).lineWidth(0.8).stroke("#333333");
  y += 12;

  // ── Section: Global Summary ─────────────────────────────────────────────
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER).fillColor("#333333");
  doc.text("GLOBAL SUMMARY", PAGE_MARGIN, y, { width: contentWidth });
  y += 14;

  doc.moveTo(PAGE_MARGIN, y).lineTo(rightEdge, y).lineWidth(0.3).stroke("#cccccc");
  y += 4;

  // Global Cash Flow Available (bold)
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY).fillColor("#000000");
  doc.text("Global Cash Flow Available", PAGE_MARGIN + 8, y + 2, { width: labelWidth });
  doc.text(fmtCurrency(gcf.globalCashFlow), valueX, y + 2, { width: valueWidth, align: "right" });
  y += ROW_HEIGHT;

  // Proposed Annual Debt Service
  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
  doc.text("Proposed Annual Debt Service", PAGE_MARGIN + 8, y + 2, { width: labelWidth });
  const dsDisplay = gcf.proposedAnnualDebtService != null
    ? `(${fmtCurrency(gcf.proposedAnnualDebtService).replace(/^\$/, "$")})`
    : "\u2014";
  doc.text(dsDisplay, valueX, y + 2, { width: valueWidth, align: "right" });
  y += ROW_HEIGHT;

  // Separator line
  doc.moveTo(PAGE_MARGIN + 8, y).lineTo(rightEdge, y).lineWidth(0.3).stroke("#cccccc");
  y += 6;

  // Global DSCR (large, colored)
  doc.font(FONT_BOLD).fontSize(12);
  doc.text("Global DSCR", PAGE_MARGIN + 8, y + 2, { width: labelWidth });

  const dscrDisplay = gcf.globalDscr != null ? `${gcf.globalDscr.toFixed(2)}x` : "\u2014";
  // Patch B (BUGFIX classic-spread render consistency): a coverage band is only meaningful when the
  // global DSCR is numeric. Certification can blank globalDscr while leaving coverageStatus set to
  // ADEQUATE/TIGHT/DEFICIT \u2014 never present such a band (or "TIGHT \u2014 DSCR 1.00x\u20131.25x") without an
  // actual number. Fall back to the UNKNOWN / insufficient-data band.
  const coverageStatus = gcf.globalDscr != null ? gcf.coverageStatus : "UNKNOWN";
  const dscrColor = coverageStatus === "ADEQUATE" ? "#16a34a"
    : coverageStatus === "TIGHT" ? "#d97706"
    : coverageStatus === "DEFICIT" ? "#dc2626"
    : "#666666";
  doc.fillColor(dscrColor);
  doc.text(dscrDisplay, valueX, y + 2, { width: valueWidth, align: "right" });
  doc.fillColor("#000000");
  y += 20;

  // ── Coverage Signal Bar ─────────────────────────────────────────────────
  const barHeight = 28;
  const accentColor = coverageStatus === "ADEQUATE" ? "#22c55e"
    : coverageStatus === "TIGHT" ? "#f59e0b"
    : coverageStatus === "DEFICIT" ? "#ef4444"
    : "#999999";

  // Left accent border
  doc.rect(PAGE_MARGIN, y, 4, barHeight).fill(accentColor);
  // Light background
  doc.rect(PAGE_MARGIN + 4, y, contentWidth - 4, barHeight).fill("#f9fafb");

  const statusLabel = coverageStatus === "ADEQUATE" ? "ADEQUATE \u2014 DSCR \u2265 1.25x"
    : coverageStatus === "TIGHT" ? "TIGHT \u2014 DSCR 1.00x\u20131.25x"
    : coverageStatus === "DEFICIT" ? "DEFICIT \u2014 DSCR < 1.00x"
    : "UNKNOWN \u2014 Insufficient data to compute DSCR";

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY).fillColor(accentColor);
  doc.text(statusLabel, PAGE_MARGIN + 14, y + 9, { width: contentWidth - 24, lineBreak: false });
  doc.fillColor("#000000");
  y += barHeight + 16;

  // SPEC-B4 — Methodology block (renders after coverage signal bar)
  y = renderMethodologyBlock(doc, gcf, y);

  // ── Footer ──────────────────────────────────────────────────────────────
  const footerTop = doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT + 8;

  doc.moveTo(PAGE_MARGIN, footerTop).lineTo(rightEdge, footerTop).lineWidth(0.3).stroke("#999999");

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#666666");
  doc.text(`Page ${pageNum}`, PAGE_MARGIN, footerTop + 6, { width: 100, lineBreak: false });
  doc.text("Buddy The Underwriter", rightEdge - 160, footerTop + 6, { width: 160, align: "right", lineBreak: false });

  doc.text(
    "Global cash flow includes ownership-adjusted entity cash flow plus guarantor personal income net of personal obligations and living expenses.",
    PAGE_MARGIN,
    footerTop + 16,
    { width: contentWidth, lineBreak: false },
  );
  doc.text("Confidential \u2014 For Internal Use Only", PAGE_MARGIN, footerTop + 26, { width: contentWidth, align: "center", lineBreak: false });

  doc.fillColor("#000000");

  return pageNum;
}

// ---------------------------------------------------------------------------
// Personal Income Page (Form 1040)
// ---------------------------------------------------------------------------

type PIRow = {
  label: string;
  getter: (y: PersonalIncomeYear) => number | null;
  isBold?: boolean;
  isSectionHeader?: boolean;
  isNegative?: boolean;
};

const PI_SECTIONS: PIRow[] = [
  { label: "INCOME SOURCES", getter: () => null, isSectionHeader: true },
  { label: "W-2 Wages & Salaries", getter: (y) => y.wagesW2 },
  { label: "Schedule C \u2014 Net Business Income", getter: (y) => y.schedCNet },
  { label: "Schedule E \u2014 Net Rental/Royalty", getter: (y) => y.schedENet },
  { label: "K-1 \u2014 Partnership/S-Corp Income", getter: (y) => y.k1OrdinaryIncome },
  { label: "Capital Gains / (Losses)", getter: (y) => y.capitalGains },
  { label: "Interest & Dividend Income", getter: (y) => {
    const interest = y.taxableInterest ?? 0;
    const dividends = y.ordinaryDividends ?? 0;
    return (y.taxableInterest != null || y.ordinaryDividends != null) ? interest + dividends : null;
  }},
  { label: "Pension / Social Security", getter: (y) => {
    const pension = y.pensionAnnuity ?? 0;
    const ss = y.socialSecurity ?? 0;
    return (y.pensionAnnuity != null || y.socialSecurity != null) ? pension + ss : null;
  }},
  { label: "Other Income", getter: (y) => y.otherIncome },
  { label: "Less: Adjustments to Income", getter: (y) => y.adjustmentsToIncome, isNegative: true },
  { label: "ADJUSTED GROSS INCOME", getter: (y) => y.adjustedGrossIncome, isBold: true },

  { label: "DEDUCTIONS", getter: () => null, isSectionHeader: true },
  { label: "Standard / Itemized Deductions", getter: (y) => y.standardDeduction },
  { label: "QBI Deduction (Sec 199A)", getter: (y) => y.qbiDeduction },
  { label: "TAXABLE INCOME", getter: (y) => y.taxableIncome, isBold: true },
  { label: "Total Tax", getter: (y) => y.totalTax },

  { label: "DEPRECIATION ADDBACK (Form 4562)", getter: () => null, isSectionHeader: true },
  { label: "Section 179 Elected", getter: (y) => y.f4562Sec179 },
  { label: "Bonus Depreciation", getter: (y) => y.f4562BonusDepreciation },
  { label: "Total Depreciation & Amortization", getter: (y) => y.f4562TotalDepreciation, isBold: true },

  { label: "SCHEDULE E RENTAL DETAIL", getter: () => null, isSectionHeader: true },
  { label: "Gross Rents Received", getter: (y) => y.schEGrossRents },
  { label: "Mortgage Interest Paid", getter: (y) => y.schEMortgageInterest },
  { label: "Depreciation (Schedule E)", getter: (y) => y.schEDepreciation },
  { label: "Total Rental Expenses", getter: (y) => y.schETotalExpenses },
  { label: "Net Rental Income / (Loss)", getter: (y) => y.schedENet },

  { label: "ENTITY RENTAL (Form 8825)", getter: () => null, isSectionHeader: true },
  { label: "Net Rental Income \u2014 Entity Level", getter: (y) => y.f8825NetIncomeLoss },
];

function renderPersonalIncomePage(
  doc: PDFKit.PDFDocument,
  input: ClassicSpreadInput,
  pi: PersonalIncomeSection,
  pageNum: number,
  layout: LayoutConfig = DEFAULT_LAYOUT,
): number {
  // Alias for all s.layout.* references in this standalone function
  const s = { layout };
  const rightEdge = doc.page.width - PAGE_MARGIN;
  const contentWidth = rightEdge - PAGE_MARGIN;

  // Use up to 4 most recent years, newest right
  const displayYears = pi.years.slice(-4);
  const numCols = displayYears.length;
  const totalRowWidth = PAGE_MARGIN + s.layout.label + numCols * s.layout.value;

  let y = PAGE_MARGIN;

  // ── Header ──────────────────────────────────────────────────────────────
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_TITLE);
  doc.text(input.companyName.toUpperCase(), PAGE_MARGIN, y, { width: contentWidth });

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_HEADER);
  doc.text("Personal Income Analysis (Form 1040)", PAGE_MARGIN, y + 14, { width: 300 });
  doc.text("Generated by Buddy", rightEdge - 150, y + 14, { width: 150, align: "right" });

  doc.fontSize(FONT_SIZE_META);
  doc.text("Guarantor Tax Return Summary", PAGE_MARGIN, y + 28, { width: 350 });
  doc.text(input.preparedDate, rightEdge - 150, y + 28, { width: 150, align: "right" });

  const ruleY = y + HEADER_HEIGHT - 4;
  doc.moveTo(PAGE_MARGIN, ruleY).lineTo(rightEdge, ruleY).lineWidth(0.5).stroke("#333333");
  y = ruleY + 8;

  // ── Year column headers ─────────────────────────────────────────────────
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
  doc.text("LINE ITEM", PAGE_MARGIN + 4, y + 2, { width: s.layout.label - 8 });
  let hx = PAGE_MARGIN + s.layout.label;
  for (const yr of displayYears) {
    doc.text(String(yr.year), hx, y + 2, { width: s.layout.value, align: "right" });
    hx += s.layout.value;
  }
  doc.moveTo(PAGE_MARGIN, y + ROW_HEIGHT).lineTo(totalRowWidth, y + ROW_HEIGHT).lineWidth(0.5).stroke("#333333");
  y = y + ROW_HEIGHT + 2;

  // ── Data rows ───────────────────────────────────────────────────────────
  const maxY = doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT - 10;

  for (const row of PI_SECTIONS) {
    // Page break check
    if (y + ROW_HEIGHT > maxY) {
      // Draw footer before page break
      const footerTop = doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT + 8;
      doc.moveTo(PAGE_MARGIN, footerTop).lineTo(rightEdge, footerTop).lineWidth(0.3).stroke("#999999");
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#666666");
      doc.text(`Page ${pageNum}`, PAGE_MARGIN, footerTop + 6, { width: 100, lineBreak: false });
      doc.text("Buddy The Underwriter", rightEdge - 160, footerTop + 6, { width: 160, align: "right", lineBreak: false });
      doc.text("Confidential \u2014 For Internal Use Only", PAGE_MARGIN, footerTop + 26, { width: contentWidth, align: "center", lineBreak: false });
      doc.fillColor("#000000");

      doc.addPage();
      pageNum++;

      // Redraw header on new page
      y = PAGE_MARGIN;
      doc.font(FONT_BOLD).fontSize(FONT_SIZE_TITLE);
      doc.text(input.companyName.toUpperCase(), PAGE_MARGIN, y, { width: contentWidth });
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_HEADER);
      doc.text("Personal Income Analysis (cont.)", PAGE_MARGIN, y + 14, { width: 300 });
      const r2 = y + HEADER_HEIGHT - 4;
      doc.moveTo(PAGE_MARGIN, r2).lineTo(rightEdge, r2).lineWidth(0.5).stroke("#333333");
      y = r2 + 8;
    }

    if (row.isSectionHeader) {
      // Gray band section header
      y += 4; // gap before section
      doc.rect(PAGE_MARGIN, y, totalRowWidth - PAGE_MARGIN, ROW_HEIGHT).fill("#f0f0f0");
      doc.fillColor("#000000").font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
      doc.text(row.label, PAGE_MARGIN + 4, y + 2, { width: s.layout.label - 8 });
      y += ROW_HEIGHT;
      continue;
    }

    // Bold underline for totals
    if (row.isBold) {
      doc.moveTo(PAGE_MARGIN, y - 1).lineTo(totalRowWidth, y - 1).lineWidth(0.3).stroke("#666666");
    }

    // Label
    doc.font(row.isBold ? FONT_BOLD : FONT_NORMAL).fontSize(FONT_SIZE_BODY);
    doc.text(row.label, PAGE_MARGIN + (row.isBold ? 4 : 16), y + 2, {
      width: s.layout.label - (row.isBold ? 8 : 20),
    });

    // Values
    let vx = PAGE_MARGIN + s.layout.label;
    for (const yr of displayYears) {
      const val = row.getter(yr);
      const display = fmtNumber(val, row.isNegative);
      doc.font(row.isBold ? FONT_BOLD : FONT_NORMAL).fontSize(FONT_SIZE_BODY);
      doc.text(display, vx, y + 2, { width: s.layout.value - 4, align: "right" });
      vx += s.layout.value;
    }

    // Light horizontal rule
    doc.moveTo(PAGE_MARGIN, y + ROW_HEIGHT)
      .lineTo(totalRowWidth, y + ROW_HEIGHT)
      .lineWidth(0.15).stroke("#dddddd");

    y += ROW_HEIGHT;
  }

  // ── Footer ──────────────────────────────────────────────────────────────
  const footerTop = doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT + 8;
  doc.moveTo(PAGE_MARGIN, footerTop).lineTo(rightEdge, footerTop).lineWidth(0.3).stroke("#999999");

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#666666");
  doc.text(`Page ${pageNum}`, PAGE_MARGIN, footerTop + 6, { width: 100, lineBreak: false });
  doc.text("Buddy The Underwriter", rightEdge - 160, footerTop + 6, { width: 160, align: "right", lineBreak: false });
  doc.text(
    "Source: IRS Form 1040 + Schedules C, E | Extracted by Buddy",
    PAGE_MARGIN,
    footerTop + 16,
    { width: contentWidth, lineBreak: false },
  );
  doc.text("Confidential \u2014 For Internal Use Only", PAGE_MARGIN, footerTop + 26, { width: contentWidth, align: "center", lineBreak: false });
  doc.fillColor("#000000");

  return pageNum;
}

// ---------------------------------------------------------------------------
// Main Renderer
// ---------------------------------------------------------------------------

export function renderClassicSpread(
  input: ClassicSpreadInput,
  narrative?: SpreadNarrative | null,
): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: "letter", margin: PAGE_MARGIN });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const { periods } = input;
    if (periods.length === 0) {
      // No data at all — single page with message
      doc.fontSize(FONT_SIZE_TITLE).text("Classic Banker Spread Report", { align: "center" });
      doc.moveDown();
      doc.fontSize(FONT_SIZE_BODY).text("No financial data available for this deal.", { align: "center" });
      doc.end();
      return;
    }

    // ===== Page 1: Balance Sheet =====
    const layout = computeLayout(periods.length);
    const s: DocState = {
      doc,
      y: 0,
      pageNum: 1,
      input,
      pageTitle: "Detailed Balance Sheet - Actual and % Amounts",
      periods,
      showPctColumns: true,
      layout,
    };

    drawPageHeader(s);

    // SPEC-CLASSIC-SPREAD-SYSTEM-HARDENING-AUDIT-2 #9: fail-closed banner on the first page banker
    // sees — an uncertified spread must announce itself, not look certified.
    if (input.certified === false) {
      const bannerW = doc.page.width - 2 * PAGE_MARGIN;
      doc.rect(PAGE_MARGIN, s.y, bannerW, 16).fill("#dc2626");
      doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY).fillColor("#ffffff");
      doc.text("NOT CERTIFIED — certification unavailable; values are uncertified", PAGE_MARGIN + 6, s.y + 3, { width: bannerW - 12, lineBreak: false });
      doc.fillColor("#000000");
      s.y += 22;
    }

    if (input.balanceSheet.length > 0) {
      drawMetadataGrid(s);
      drawColumnHeaders(s);
      for (const row of input.balanceSheet) {
        drawFinancialRow(s, row);
      }
    } else {
      s.y += 20;
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
      doc.text("Balance sheet data not available", PAGE_MARGIN, s.y, { align: "center" });
    }

    drawPageFooter(s);

    // ===== Page 2: Income Statement =====
    doc.addPage();
    s.pageNum++;
    s.pageTitle = "Detailed Income Statement - Actual and % Amounts";
    drawPageHeader(s);

    if (input.incomeStatement.length > 0) {
      drawMetadataGrid(s);
      drawColumnHeaders(s);
      for (const row of input.incomeStatement) {
        drawFinancialRow(s, row);
      }
    } else {
      s.y += 20;
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
      doc.text("Income statement data not available", PAGE_MARGIN, s.y, { align: "center" });
    }

    drawPageFooter(s);

    // ===== Page 3: Statement of Cash Flows (UCA) =====
    if (input.cashFlow.length > 0) {
      doc.addPage();
      s.pageNum++;
      s.pageTitle = "Derived Statement of Cash Flows (UCA Method)";
      s.showPctColumns = false;
      drawPageHeader(s);

      drawMetadataGrid(s);

      // Column headers (no % columns)
      const cfColY = s.y;
      doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
      doc.text("LINE ITEM", PAGE_MARGIN + 4, cfColY + 2, { width: s.layout.label - 8 });
      let cfx = PAGE_MARGIN + s.layout.label;
      for (const p of periods) {
        doc.text(p.label, cfx, cfColY + 2, { width: s.layout.value, align: "right" });
        cfx += s.layout.value;
      }
      doc.moveTo(PAGE_MARGIN, cfColY + ROW_HEIGHT).lineTo(cfx, cfColY + ROW_HEIGHT).lineWidth(0.5).stroke("#333333");
      s.y = cfColY + ROW_HEIGHT + 2;

      for (const row of input.cashFlow) {
        drawCashFlowRow(s, row);
      }

      drawPageFooter(s);
    }

    // ===== Page 4: Ratios =====
    doc.addPage();
    s.pageNum++;
    s.pageTitle = "Detailed Ratios";
    s.showPctColumns = false;
    drawPageHeader(s);

    // Ratio column headers (no % columns)
    const ratioY = s.y;
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
    doc.text("RATIO", PAGE_MARGIN + 4, ratioY + 2, { width: s.layout.label - 8 });
    let rx = PAGE_MARGIN + s.layout.label;
    for (const p of periods) {
      doc.text(p.label, rx, ratioY + 2, { width: s.layout.value, align: "right" });
      rx += s.layout.value;
    }
    doc.moveTo(PAGE_MARGIN, ratioY + ROW_HEIGHT).lineTo(rx, ratioY + ROW_HEIGHT).lineWidth(0.5).stroke("#333333");
    s.y = ratioY + ROW_HEIGHT + 2;

    drawRatioSections(s, input.ratioSections);
    drawPageFooter(s);

    // ===== Global Cash Flow Page (if data exists) =====
    if (input.globalCashFlow != null &&
        (input.globalCashFlow.entityCashFlowAvailable != null || input.globalCashFlow.sponsors.length > 0)) {
      doc.addPage();
      s.pageNum++;
      renderGlobalCashFlowPage(doc, input, input.globalCashFlow, s.pageNum);
    }

    // ===== Personal Income Page (if data exists) =====
    if (input.personalIncome != null && input.personalIncome.years.length > 0) {
      doc.addPage();
      s.pageNum++;
      s.pageNum = renderPersonalIncomePage(doc, input, input.personalIncome, s.pageNum, layout);
    }

    // ===== Executive Summary =====
    doc.addPage();
    s.pageNum++;
    s.pageTitle = "Executive Financial Statement - Actual and % Amounts";
    s.showPctColumns = true;
    drawPageHeader(s);

    // Assets section
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER);
    doc.text("ASSETS", PAGE_MARGIN, s.y + 2);
    s.y += ROW_HEIGHT + 2;
    drawColumnHeaders(s);
    for (const row of input.executiveSummary.assets) {
      drawFinancialRow(s, row);
    }

    s.y += 8;

    // Liabilities & Net Worth section
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER);
    doc.text("LIABILITIES & NET WORTH", PAGE_MARGIN, s.y + 2);
    s.y += ROW_HEIGHT + 2;
    for (const row of input.executiveSummary.liabilitiesAndNetWorth) {
      drawFinancialRow(s, row);
    }

    s.y += 8;

    // Income Statement section
    checkPageBreak(s, 8);
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER);
    doc.text("INCOME STATEMENT", PAGE_MARGIN, s.y + 2);
    s.y += ROW_HEIGHT + 2;
    for (const row of input.executiveSummary.incomeStatement) {
      drawFinancialRow(s, row);
    }

    drawPageFooter(s);

    // ===== Spread Accuracy & Completion Audit (if computed) =====
    const spreadAudit = input.certificationAudit?.spreadAccuracy ?? null;
    const notCertified = input.certified === false;
    if (spreadAudit || notCertified) {
      doc.addPage();
      s.pageNum++;
      s.pageTitle = "Spread Accuracy & Completion Audit";
      s.showPctColumns = false;
      drawPageHeader(s);
      drawSpreadAuditSection(s, spreadAudit, notCertified);
      drawPageFooter(s);
    }

    // ===== Optional: Narrative Analysis =====
    if (narrative && narrative.sections.length > 0) {
      doc.addPage();
      s.pageNum++;
      s.pageTitle = "Financial Analysis Narrative";
      s.showPctColumns = false;
      drawPageHeader(s);
      drawNarrativeSections(s, narrative);
      drawPageFooter(s);
    }

    doc.end();
  });
}
