import PDFDocument from "pdfkit";
import type {
  CashFlowRow,
  ClassicSpreadInput,
  FinancialRow,
  GlobalCashFlowSection,
  RatioSection,
  StatementPeriod,
} from "./types";
import type { SpreadNarrative } from "./narrativeEngine";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const FONT_NORMAL = "Helvetica";
const FONT_BOLD = "Helvetica-Bold";
const FONT_SIZE_BODY = 8;
const FONT_SIZE_HEADER = 9;
const FONT_SIZE_TITLE = 11;
const FONT_SIZE_META = 7;
// Tuned to fit 4 periods + % columns within letter portrait (540pt usable).
// 165 + 4 × (60 + 30) = 525pt — fits with margin to spare.
const COL_WIDTH_LABEL = 165;
const COL_WIDTH_VALUE = 60;
const COL_WIDTH_PCT = 30;
const ROW_HEIGHT = 12;
const PAGE_MARGIN = 36;
const HEADER_HEIGHT = 56;
const FOOTER_HEIGHT = 50;

const DOUBLE_RULE_LABELS = new Set([
  "TOTAL ASSETS",
  "TOTAL LIABILITIES & NET WORTH",
  "NET PROFIT",
  "EBITDA",
  "CASH FROM OPERATIONS (UCA)",
  "CASH AVAILABLE FOR DEBT SERVICE",
]);

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------

function fmtNumber(val: number | null, isNegative?: boolean): string {
  if (val == null || val === 0) return "\u2014"; // em dash
  let n = isNegative ? -val : val;
  if (n < 0) {
    return `(${Math.abs(n).toLocaleString("en-US", { maximumFractionDigits: 0 })})`;
  }
  return n.toLocaleString("en-US", { maximumFractionDigits: 0 });
}

function fmtPct(val: number | null, base: number | null): string {
  if (val == null || base == null || base === 0) return "\u2014";
  const pct = (val / base) * 100;
  if (pct < 0) {
    return `(${Math.abs(pct).toFixed(1)})`;
  }
  return pct.toFixed(1);
}

function fmtRatioValue(val: number | string | null, format: string, decimals: number): string {
  if (val === "N/A") return "N/A";
  if (val == null) return "\u2014";
  if (typeof val === "string") return val;

  switch (format) {
    case "currency":
      if (val === 0) return "\u2014";
      if (val < 0) return `(${Math.abs(val).toLocaleString("en-US", { maximumFractionDigits: 0 })})`;
      return val.toLocaleString("en-US", { maximumFractionDigits: 0 });
    case "percent":
      if (val < 0) return `(${Math.abs(val).toFixed(decimals)})`;
      return val.toFixed(decimals);
    case "ratio":
      if (val < 0) return `(${Math.abs(val).toFixed(decimals)})`;
      return val.toFixed(decimals);
    case "days":
      if (val < 0) return `(${Math.abs(val).toFixed(decimals)})`;
      return val.toFixed(decimals);
    default:
      return val.toFixed(decimals);
  }
}

// ---------------------------------------------------------------------------
// PDF Document helpers
// ---------------------------------------------------------------------------

type DocState = {
  doc: PDFKit.PDFDocument;
  y: number;
  pageNum: number;
  input: ClassicSpreadInput;
  pageTitle: string;
  periods: StatementPeriod[];
  showPctColumns: boolean;
};

function drawPageHeader(s: DocState) {
  const { doc, input } = s;
  const rightEdge = doc.page.width - PAGE_MARGIN;

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_TITLE);
  doc.text(input.companyName.toUpperCase(), PAGE_MARGIN, PAGE_MARGIN, { width: rightEdge - PAGE_MARGIN });

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_HEADER);
  doc.text(s.pageTitle, PAGE_MARGIN, PAGE_MARGIN + 14, { width: 300 });
  doc.text("Generated by Buddy", rightEdge - 150, PAGE_MARGIN + 14, { width: 150, align: "right" });

  let naicsLine = "";
  if (input.naicsCode) {
    naicsLine = `NAICS: ${input.naicsCode}`;
    if (input.naicsDescription) naicsLine += ` \u2014 ${input.naicsDescription}`;
  }
  doc.fontSize(FONT_SIZE_META);
  if (naicsLine) {
    doc.text(naicsLine, PAGE_MARGIN, PAGE_MARGIN + 28, { width: 350 });
  }
  doc.text(input.preparedDate, rightEdge - 150, PAGE_MARGIN + 28, { width: 150, align: "right" });

  // Horizontal rule below header
  const ruleY = PAGE_MARGIN + HEADER_HEIGHT - 4;
  doc.moveTo(PAGE_MARGIN, ruleY).lineTo(rightEdge, ruleY).lineWidth(0.5).stroke("#333333");

  s.y = PAGE_MARGIN + HEADER_HEIGHT;
}

function drawPageFooter(s: DocState) {
  const { doc, input } = s;
  const rightEdge = doc.page.width - PAGE_MARGIN;
  const footerTop = doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT + 8;

  // Thin rule above footer
  doc.moveTo(PAGE_MARGIN, footerTop).lineTo(rightEdge, footerTop).lineWidth(0.3).stroke("#999999");

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#666666");
  doc.text(`Page ${s.pageNum}`, PAGE_MARGIN, footerTop + 6, { width: 100, lineBreak: false });
  doc.text("Buddy The Underwriter", rightEdge - 160, footerTop + 6, { width: 160, align: "right", lineBreak: false });

  let naicsLine = input.companyName;
  if (input.naicsCode) {
    naicsLine += `          NAICS ${input.naicsCode}`;
    if (input.naicsDescription) naicsLine += ` \u2014 ${input.naicsDescription}`;
  }
  doc.text(naicsLine, PAGE_MARGIN, footerTop + 16, { width: rightEdge - PAGE_MARGIN, lineBreak: false });
  doc.text("Confidential \u2014 For Internal Use Only", PAGE_MARGIN, footerTop + 26, { width: rightEdge - PAGE_MARGIN, align: "center", lineBreak: false });

  doc.fillColor("#000000"); // reset
}

function newPage(s: DocState) {
  drawPageFooter(s);
  s.doc.addPage();
  s.pageNum++;
  drawPageHeader(s);
}

function checkPageBreak(s: DocState, rowsNeeded: number = 1) {
  const maxY = s.doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT - 10;
  if (s.y + rowsNeeded * ROW_HEIGHT > maxY) {
    newPage(s);
  }
}

// ---------------------------------------------------------------------------
// Statement Metadata Row
// ---------------------------------------------------------------------------

function drawMetadataGrid(s: DocState) {
  const { doc, periods } = s;
  const metaRows = ["Statement Date", "Months Covered", "Audit Method", "Stmt Type"];
  const metaFns: ((p: StatementPeriod) => string)[] = [
    (p) => p.date,
    (p) => String(p.months),
    (p) => p.auditMethod,
    (p) => p.stmtType,
  ];

  doc.fontSize(FONT_SIZE_META);

  for (let r = 0; r < metaRows.length; r++) {
    const rowY = s.y;

    // Label cell (gray bg)
    doc.rect(PAGE_MARGIN, rowY, COL_WIDTH_LABEL, ROW_HEIGHT).fill("#f0f0f0");
    doc.fillColor("#000000").font(FONT_BOLD).fontSize(FONT_SIZE_META);
    doc.text(metaRows[r]!, PAGE_MARGIN + 4, rowY + 2, { width: COL_WIDTH_LABEL - 8 });

    // Value cells
    doc.font(FONT_NORMAL);
    let x = PAGE_MARGIN + COL_WIDTH_LABEL;
    for (let c = 0; c < periods.length; c++) {
      const colW = s.showPctColumns ? COL_WIDTH_VALUE + COL_WIDTH_PCT : COL_WIDTH_VALUE;
      const val = metaFns[r]!(periods[c]!);
      doc.text(val, x + 2, rowY + 2, { width: colW - 4, align: "center" });
      x += colW;
    }

    // Light line
    doc.moveTo(PAGE_MARGIN, rowY + ROW_HEIGHT)
      .lineTo(x, rowY + ROW_HEIGHT)
      .lineWidth(0.2).stroke("#cccccc");

    s.y += ROW_HEIGHT;
  }

  s.y += 4; // gap after metadata
}

// ---------------------------------------------------------------------------
// Column Headers
// ---------------------------------------------------------------------------

function drawColumnHeaders(s: DocState) {
  const { doc, periods } = s;
  const rowY = s.y;

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
  doc.text("LINE ITEM", PAGE_MARGIN + 4, rowY + 2, { width: COL_WIDTH_LABEL - 8 });

  let x = PAGE_MARGIN + COL_WIDTH_LABEL;
  for (const p of periods) {
    doc.text(p.label, x, rowY + 2, { width: COL_WIDTH_VALUE, align: "right" });
    x += COL_WIDTH_VALUE;
    if (s.showPctColumns) {
      doc.text("%", x, rowY + 2, { width: COL_WIDTH_PCT, align: "right" });
      x += COL_WIDTH_PCT;
    }
  }

  // Underline
  doc.moveTo(PAGE_MARGIN, rowY + ROW_HEIGHT)
    .lineTo(x, rowY + ROW_HEIGHT)
    .lineWidth(0.5).stroke("#333333");

  s.y = rowY + ROW_HEIGHT + 2;
}

// ---------------------------------------------------------------------------
// Financial Row Rendering
// ---------------------------------------------------------------------------

function drawFinancialRow(s: DocState, row: FinancialRow) {
  if (!row.label && row.values.every((v) => v == null)) {
    s.y += 4; // spacer row
    return;
  }

  checkPageBreak(s);
  const { doc, periods } = s;
  const rowY = s.y;
  const rightEdge = PAGE_MARGIN + COL_WIDTH_LABEL +
    periods.length * (COL_WIDTH_VALUE + (s.showPctColumns && row.showPct ? COL_WIDTH_PCT : 0));

  // Double rule before certain totals
  if (DOUBLE_RULE_LABELS.has(row.label)) {
    doc.moveTo(PAGE_MARGIN, rowY - 1).lineTo(rightEdge, rowY - 1).lineWidth(0.3).stroke("#666666");
    doc.moveTo(PAGE_MARGIN, rowY + 1).lineTo(rightEdge, rowY + 1).lineWidth(0.3).stroke("#666666");
    s.y += 3;
  }

  // Section header: gray background band
  if (row.indent === 0 && row.isBold && row.values.every((v) => v == null)) {
    doc.rect(PAGE_MARGIN, s.y, rightEdge - PAGE_MARGIN, ROW_HEIGHT).fill("#f5f5f5");
    doc.fillColor("#000000");
  }

  // Label
  const indent = row.indent * 12;
  doc.font(row.isBold ? FONT_BOLD : FONT_NORMAL).fontSize(FONT_SIZE_BODY);
  doc.text(row.label, PAGE_MARGIN + 4 + indent, s.y + 2, { width: COL_WIDTH_LABEL - 8 - indent });

  // Values
  let x = PAGE_MARGIN + COL_WIDTH_LABEL;
  for (let i = 0; i < periods.length; i++) {
    const val = row.values[i] ?? null;
    const display = fmtNumber(val, row.isNegative);
    doc.font(row.isBold ? FONT_BOLD : FONT_NORMAL).fontSize(FONT_SIZE_BODY);
    doc.text(display, x, s.y + 2, { width: COL_WIDTH_VALUE - 4, align: "right" });
    x += COL_WIDTH_VALUE;

    if (s.showPctColumns && row.showPct) {
      const base = row.pctBase?.[i] ?? null;
      const pctDisplay = fmtPct(val, base);
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META);
      doc.text(pctDisplay, x, s.y + 2, { width: COL_WIDTH_PCT - 4, align: "right" });
      x += COL_WIDTH_PCT;
    }
  }

  // Light horizontal rule
  doc.moveTo(PAGE_MARGIN, s.y + ROW_HEIGHT)
    .lineTo(x, s.y + ROW_HEIGHT)
    .lineWidth(0.15).stroke("#dddddd");

  s.y += ROW_HEIGHT;
}

// ---------------------------------------------------------------------------
// Cash Flow Row Rendering (no % columns)
// ---------------------------------------------------------------------------

function drawCashFlowRow(s: DocState, row: CashFlowRow) {
  if (!row.label && row.values.every((v) => v == null)) {
    s.y += 4; // spacer row
    return;
  }

  checkPageBreak(s);
  const { doc, periods } = s;
  const rightEdge = PAGE_MARGIN + COL_WIDTH_LABEL + periods.length * COL_WIDTH_VALUE;

  // Double rule before key totals
  if (DOUBLE_RULE_LABELS.has(row.label)) {
    doc.moveTo(PAGE_MARGIN, s.y - 1).lineTo(rightEdge, s.y - 1).lineWidth(0.3).stroke("#666666");
    doc.moveTo(PAGE_MARGIN, s.y + 1).lineTo(rightEdge, s.y + 1).lineWidth(0.3).stroke("#666666");
    s.y += 3;
  }

  // Section header: gray background band
  if (row.indent === 0 && row.isBold && row.values.every((v) => v == null)) {
    doc.rect(PAGE_MARGIN, s.y, rightEdge - PAGE_MARGIN, ROW_HEIGHT).fill("#f5f5f5");
    doc.fillColor("#000000");
  }

  // Label
  const indent = row.indent * 12;
  doc.font(row.isBold ? FONT_BOLD : FONT_NORMAL).fontSize(FONT_SIZE_BODY);
  doc.text(row.label, PAGE_MARGIN + 4 + indent, s.y + 2, { width: COL_WIDTH_LABEL - 8 - indent });

  // Values (no % columns for cash flow)
  let x = PAGE_MARGIN + COL_WIDTH_LABEL;
  for (let i = 0; i < periods.length; i++) {
    const val = row.values[i] ?? null;
    const display = fmtNumber(val, row.isNegative);
    doc.font(row.isBold ? FONT_BOLD : FONT_NORMAL).fontSize(FONT_SIZE_BODY);
    doc.text(display, x, s.y + 2, { width: COL_WIDTH_VALUE - 4, align: "right" });
    x += COL_WIDTH_VALUE;
  }

  // Light horizontal rule
  doc.moveTo(PAGE_MARGIN, s.y + ROW_HEIGHT)
    .lineTo(x, s.y + ROW_HEIGHT)
    .lineWidth(0.15).stroke("#dddddd");

  s.y += ROW_HEIGHT;
}

// ---------------------------------------------------------------------------
// Narrative Section Rendering
// ---------------------------------------------------------------------------

function drawNarrativeSections(s: DocState, narrative: SpreadNarrative) {
  const { doc } = s;
  const rightEdge = doc.page.width - PAGE_MARGIN;
  const textWidth = rightEdge - PAGE_MARGIN;

  for (const section of narrative.sections) {
    checkPageBreak(s, 6);

    // Section title
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER).fillColor("#333333");
    doc.text(section.title, PAGE_MARGIN, s.y, { width: textWidth });
    s.y += 14;

    // Section body
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY).fillColor("#000000");
    const bodyHeight = doc.heightOfString(section.body, { width: textWidth });
    doc.text(section.body, PAGE_MARGIN, s.y, { width: textWidth });
    s.y += bodyHeight + 12;
  }

  // Attribution
  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#999999");
  doc.text(
    `Generated by ${narrative.model} at ${new Date(narrative.generatedAt).toLocaleString("en-US")}`,
    PAGE_MARGIN,
    s.y,
    { width: textWidth, align: "right", lineBreak: false },
  );
  doc.fillColor("#000000");
  s.y += 12;
}

// ---------------------------------------------------------------------------
// Ratio Section Rendering
// ---------------------------------------------------------------------------

function drawRatioSections(s: DocState, sections: RatioSection[]) {
  const { doc, periods } = s;

  for (const section of sections) {
    checkPageBreak(s, 2);

    // Section title: gray band
    const rightEdge = PAGE_MARGIN + COL_WIDTH_LABEL + periods.length * COL_WIDTH_VALUE;
    doc.rect(PAGE_MARGIN, s.y, rightEdge - PAGE_MARGIN, ROW_HEIGHT).fill("#f0f0f0");
    doc.fillColor("#000000");
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
    doc.text(section.title, PAGE_MARGIN + 4, s.y + 2, { width: COL_WIDTH_LABEL - 8 });
    s.y += ROW_HEIGHT;

    for (const row of section.rows) {
      checkPageBreak(s);

      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
      doc.text(row.label, PAGE_MARGIN + 16, s.y + 2, { width: COL_WIDTH_LABEL - 20 });

      let x = PAGE_MARGIN + COL_WIDTH_LABEL;
      for (let i = 0; i < periods.length; i++) {
        const val = row.values[i] ?? null;
        const display = fmtRatioValue(val, row.format, row.decimals);
        doc.text(display, x, s.y + 2, { width: COL_WIDTH_VALUE - 4, align: "right" });
        x += COL_WIDTH_VALUE;
      }

      doc.moveTo(PAGE_MARGIN, s.y + ROW_HEIGHT)
        .lineTo(x, s.y + ROW_HEIGHT)
        .lineWidth(0.15).stroke("#dddddd");

      s.y += ROW_HEIGHT;
    }

    s.y += 6; // gap between sections
  }
}

// ---------------------------------------------------------------------------
// Global Cash Flow Page
// ---------------------------------------------------------------------------

function fmtCurrency(val: number | null): string {
  if (val == null) return "\u2014";
  if (val < 0) return `($${Math.abs(val).toLocaleString("en-US", { maximumFractionDigits: 0 })})`;
  return `$${val.toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
}

function renderGlobalCashFlowPage(
  doc: PDFKit.PDFDocument,
  input: ClassicSpreadInput,
  gcf: GlobalCashFlowSection,
  pageNum: number,
): number {
  const rightEdge = doc.page.width - PAGE_MARGIN;
  const contentWidth = rightEdge - PAGE_MARGIN;
  const labelWidth = 300;
  const valueX = rightEdge - 120;
  const valueWidth = 120;
  let y = PAGE_MARGIN;

  // ── Header bar ──────────────────────────────────────────────────────────
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_TITLE);
  doc.text(input.companyName.toUpperCase(), PAGE_MARGIN, y, { width: contentWidth });

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_HEADER);
  doc.text("Global Cash Flow Analysis", PAGE_MARGIN, y + 14, { width: 300 });
  doc.text("Generated by Buddy", rightEdge - 150, y + 14, { width: 150, align: "right" });

  doc.fontSize(FONT_SIZE_META);
  if (gcf.taxYear) {
    doc.text(`Tax Year: ${gcf.taxYear}`, PAGE_MARGIN, y + 28, { width: 350 });
  }
  doc.text(input.preparedDate, rightEdge - 150, y + 28, { width: 150, align: "right" });

  const ruleY = y + HEADER_HEIGHT - 4;
  doc.moveTo(PAGE_MARGIN, ruleY).lineTo(rightEdge, ruleY).lineWidth(0.5).stroke("#333333");
  y = ruleY + 12;

  // ── Section: Entity Cash Flow ───────────────────────────────────────────
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER).fillColor("#333333");
  doc.text("ENTITY CASH FLOW", PAGE_MARGIN, y, { width: contentWidth });
  y += 14;

  doc.moveTo(PAGE_MARGIN, y).lineTo(rightEdge, y).lineWidth(0.3).stroke("#cccccc");
  y += 4;

  if (gcf.entityCashFlowAvailable != null) {
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY).fillColor("#000000");
    doc.text("Entity Cash Flow Available", PAGE_MARGIN + 8, y + 2, { width: labelWidth });
    doc.font(FONT_BOLD);
    doc.text(fmtCurrency(gcf.entityCashFlowAvailable), valueX, y + 2, { width: valueWidth, align: "right" });
    y += ROW_HEIGHT;

    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#666666");
    doc.text(`(from ${gcf.entityCount} operating ${gcf.entityCount === 1 ? "entity" : "entities"})`, PAGE_MARGIN + 20, y + 1, { width: labelWidth });
    doc.fillColor("#000000");
    y += ROW_HEIGHT;
  } else {
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY).fillColor("#999999");
    doc.text("Entity data not yet computed \u2014 re-run spread pipeline", PAGE_MARGIN + 8, y + 2, { width: contentWidth });
    doc.fillColor("#000000");
    y += ROW_HEIGHT + 4;
  }

  y += 8;

  // ── Section: Sponsor Contributions ──────────────────────────────────────
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER).fillColor("#333333");
  doc.text("SPONSOR CONTRIBUTIONS", PAGE_MARGIN, y, { width: contentWidth });
  y += 14;

  doc.moveTo(PAGE_MARGIN, y).lineTo(rightEdge, y).lineWidth(0.3).stroke("#cccccc");
  y += 4;

  if (gcf.sponsors.length > 0) {
    for (const sponsor of gcf.sponsors) {
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY).fillColor("#000000");
      doc.text(sponsor.displayName, PAGE_MARGIN + 8, y + 2, { width: labelWidth });
      doc.text(fmtCurrency(sponsor.personalCashAvailable), valueX, y + 2, { width: valueWidth, align: "right" });
      y += ROW_HEIGHT;
    }
  } else {
    doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY).fillColor("#999999");
    doc.text("No personal financial data \u2014 re-extract personal tax returns", PAGE_MARGIN + 8, y + 2, { width: contentWidth });
    doc.fillColor("#000000");
    y += ROW_HEIGHT + 4;
  }

  y += 12;

  // ── Divider ─────────────────────────────────────────────────────────────
  doc.moveTo(PAGE_MARGIN, y).lineTo(rightEdge, y).lineWidth(0.8).stroke("#333333");
  y += 12;

  // ── Section: Global Summary ─────────────────────────────────────────────
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER).fillColor("#333333");
  doc.text("GLOBAL SUMMARY", PAGE_MARGIN, y, { width: contentWidth });
  y += 14;

  doc.moveTo(PAGE_MARGIN, y).lineTo(rightEdge, y).lineWidth(0.3).stroke("#cccccc");
  y += 4;

  // Global Cash Flow Available (bold)
  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY).fillColor("#000000");
  doc.text("Global Cash Flow Available", PAGE_MARGIN + 8, y + 2, { width: labelWidth });
  doc.text(fmtCurrency(gcf.globalCashFlow), valueX, y + 2, { width: valueWidth, align: "right" });
  y += ROW_HEIGHT;

  // Proposed Annual Debt Service
  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
  doc.text("Proposed Annual Debt Service", PAGE_MARGIN + 8, y + 2, { width: labelWidth });
  const dsDisplay = gcf.proposedAnnualDebtService != null
    ? `(${fmtCurrency(gcf.proposedAnnualDebtService).replace(/^\$/, "$")})`
    : "\u2014";
  doc.text(dsDisplay, valueX, y + 2, { width: valueWidth, align: "right" });
  y += ROW_HEIGHT;

  // Separator line
  doc.moveTo(PAGE_MARGIN + 8, y).lineTo(rightEdge, y).lineWidth(0.3).stroke("#cccccc");
  y += 6;

  // Global DSCR (large, colored)
  doc.font(FONT_BOLD).fontSize(12);
  doc.text("Global DSCR", PAGE_MARGIN + 8, y + 2, { width: labelWidth });

  const dscrDisplay = gcf.globalDscr != null ? `${gcf.globalDscr.toFixed(2)}x` : "\u2014";
  const dscrColor = gcf.coverageStatus === "ADEQUATE" ? "#16a34a"
    : gcf.coverageStatus === "TIGHT" ? "#d97706"
    : gcf.coverageStatus === "DEFICIT" ? "#dc2626"
    : "#666666";
  doc.fillColor(dscrColor);
  doc.text(dscrDisplay, valueX, y + 2, { width: valueWidth, align: "right" });
  doc.fillColor("#000000");
  y += 20;

  // ── Coverage Signal Bar ─────────────────────────────────────────────────
  const barHeight = 28;
  const accentColor = gcf.coverageStatus === "ADEQUATE" ? "#22c55e"
    : gcf.coverageStatus === "TIGHT" ? "#f59e0b"
    : gcf.coverageStatus === "DEFICIT" ? "#ef4444"
    : "#999999";

  // Left accent border
  doc.rect(PAGE_MARGIN, y, 4, barHeight).fill(accentColor);
  // Light background
  doc.rect(PAGE_MARGIN + 4, y, contentWidth - 4, barHeight).fill("#f9fafb");

  const statusLabel = gcf.coverageStatus === "ADEQUATE" ? "ADEQUATE \u2014 DSCR \u2265 1.25x"
    : gcf.coverageStatus === "TIGHT" ? "TIGHT \u2014 DSCR 1.00x\u20131.25x"
    : gcf.coverageStatus === "DEFICIT" ? "DEFICIT \u2014 DSCR < 1.00x"
    : "UNKNOWN \u2014 Insufficient data to compute DSCR";

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY).fillColor(accentColor);
  doc.text(statusLabel, PAGE_MARGIN + 14, y + 9, { width: contentWidth - 24, lineBreak: false });
  doc.fillColor("#000000");
  y += barHeight + 16;

  // ── Footer ──────────────────────────────────────────────────────────────
  const footerTop = doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT + 8;

  doc.moveTo(PAGE_MARGIN, footerTop).lineTo(rightEdge, footerTop).lineWidth(0.3).stroke("#999999");

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#666666");
  doc.text(`Page ${pageNum}`, PAGE_MARGIN, footerTop + 6, { width: 100, lineBreak: false });
  doc.text("Buddy The Underwriter", rightEdge - 160, footerTop + 6, { width: 160, align: "right", lineBreak: false });

  doc.text(
    "Global cash flow includes ownership-adjusted entity cash flow plus guarantor personal income net of personal obligations and living expenses.",
    PAGE_MARGIN,
    footerTop + 16,
    { width: contentWidth, lineBreak: false },
  );
  doc.text("Confidential \u2014 For Internal Use Only", PAGE_MARGIN, footerTop + 26, { width: contentWidth, align: "center", lineBreak: false });

  doc.fillColor("#000000");

  return pageNum;
}

// ---------------------------------------------------------------------------
// Main Renderer
// ---------------------------------------------------------------------------

export function renderClassicSpread(
  input: ClassicSpreadInput,
  narrative?: SpreadNarrative | null,
): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: "letter", margin: PAGE_MARGIN });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const { periods } = input;
    if (periods.length === 0) {
      // No data at all — single page with message
      doc.fontSize(FONT_SIZE_TITLE).text("Classic Banker Spread Report", { align: "center" });
      doc.moveDown();
      doc.fontSize(FONT_SIZE_BODY).text("No financial data available for this deal.", { align: "center" });
      doc.end();
      return;
    }

    // ===== Page 1: Balance Sheet =====
    const s: DocState = {
      doc,
      y: 0,
      pageNum: 1,
      input,
      pageTitle: "Detailed Balance Sheet - Actual and % Amounts",
      periods,
      showPctColumns: true,
    };

    drawPageHeader(s);

    if (input.balanceSheet.length > 0) {
      drawMetadataGrid(s);
      drawColumnHeaders(s);
      for (const row of input.balanceSheet) {
        drawFinancialRow(s, row);
      }
    } else {
      s.y += 20;
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
      doc.text("Balance sheet data not available", PAGE_MARGIN, s.y, { align: "center" });
    }

    drawPageFooter(s);

    // ===== Page 2: Income Statement =====
    doc.addPage();
    s.pageNum++;
    s.pageTitle = "Detailed Income Statement - Actual and % Amounts";
    drawPageHeader(s);

    if (input.incomeStatement.length > 0) {
      drawMetadataGrid(s);
      drawColumnHeaders(s);
      for (const row of input.incomeStatement) {
        drawFinancialRow(s, row);
      }
    } else {
      s.y += 20;
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
      doc.text("Income statement data not available", PAGE_MARGIN, s.y, { align: "center" });
    }

    drawPageFooter(s);

    // ===== Page 3: Statement of Cash Flows (UCA) =====
    if (input.cashFlow.length > 0) {
      doc.addPage();
      s.pageNum++;
      s.pageTitle = "Derived Statement of Cash Flows (UCA Method)";
      s.showPctColumns = false;
      drawPageHeader(s);

      drawMetadataGrid(s);

      // Column headers (no % columns)
      const cfColY = s.y;
      doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
      doc.text("LINE ITEM", PAGE_MARGIN + 4, cfColY + 2, { width: COL_WIDTH_LABEL - 8 });
      let cfx = PAGE_MARGIN + COL_WIDTH_LABEL;
      for (const p of periods) {
        doc.text(p.label, cfx, cfColY + 2, { width: COL_WIDTH_VALUE, align: "right" });
        cfx += COL_WIDTH_VALUE;
      }
      doc.moveTo(PAGE_MARGIN, cfColY + ROW_HEIGHT).lineTo(cfx, cfColY + ROW_HEIGHT).lineWidth(0.5).stroke("#333333");
      s.y = cfColY + ROW_HEIGHT + 2;

      for (const row of input.cashFlow) {
        drawCashFlowRow(s, row);
      }

      drawPageFooter(s);
    }

    // ===== Page 4: Ratios =====
    doc.addPage();
    s.pageNum++;
    s.pageTitle = "Detailed Ratios";
    s.showPctColumns = false;
    drawPageHeader(s);

    // Ratio column headers (no % columns)
    const ratioY = s.y;
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
    doc.text("RATIO", PAGE_MARGIN + 4, ratioY + 2, { width: COL_WIDTH_LABEL - 8 });
    let rx = PAGE_MARGIN + COL_WIDTH_LABEL;
    for (const p of periods) {
      doc.text(p.label, rx, ratioY + 2, { width: COL_WIDTH_VALUE, align: "right" });
      rx += COL_WIDTH_VALUE;
    }
    doc.moveTo(PAGE_MARGIN, ratioY + ROW_HEIGHT).lineTo(rx, ratioY + ROW_HEIGHT).lineWidth(0.5).stroke("#333333");
    s.y = ratioY + ROW_HEIGHT + 2;

    drawRatioSections(s, input.ratioSections);
    drawPageFooter(s);

    // ===== Global Cash Flow Page (if data exists) =====
    if (input.globalCashFlow != null &&
        (input.globalCashFlow.entityCashFlowAvailable != null || input.globalCashFlow.sponsors.length > 0)) {
      doc.addPage();
      s.pageNum++;
      renderGlobalCashFlowPage(doc, input, input.globalCashFlow, s.pageNum);
    }

    // ===== Executive Summary =====
    doc.addPage();
    s.pageNum++;
    s.pageTitle = "Executive Financial Statement - Actual and % Amounts";
    s.showPctColumns = true;
    drawPageHeader(s);

    // Assets section
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER);
    doc.text("ASSETS", PAGE_MARGIN, s.y + 2);
    s.y += ROW_HEIGHT + 2;
    drawColumnHeaders(s);
    for (const row of input.executiveSummary.assets) {
      drawFinancialRow(s, row);
    }

    s.y += 8;

    // Liabilities & Net Worth section
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER);
    doc.text("LIABILITIES & NET WORTH", PAGE_MARGIN, s.y + 2);
    s.y += ROW_HEIGHT + 2;
    for (const row of input.executiveSummary.liabilitiesAndNetWorth) {
      drawFinancialRow(s, row);
    }

    s.y += 8;

    // Income Statement section
    checkPageBreak(s, 8);
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER);
    doc.text("INCOME STATEMENT", PAGE_MARGIN, s.y + 2);
    s.y += ROW_HEIGHT + 2;
    for (const row of input.executiveSummary.incomeStatement) {
      drawFinancialRow(s, row);
    }

    drawPageFooter(s);

    // ===== Optional: Narrative Analysis =====
    if (narrative && narrative.sections.length > 0) {
      doc.addPage();
      s.pageNum++;
      s.pageTitle = "Financial Analysis Narrative";
      s.showPctColumns = false;
      drawPageHeader(s);
      drawNarrativeSections(s, narrative);
      drawPageFooter(s);
    }

    doc.end();
  });
}
