import PDFDocument from "pdfkit";
import type {
  ClassicSpreadInput,
  FinancialRow,
  RatioSection,
  StatementPeriod,
} from "./types";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const FONT_NORMAL = "Helvetica";
const FONT_BOLD = "Helvetica-Bold";
const FONT_SIZE_BODY = 8;
const FONT_SIZE_HEADER = 9;
const FONT_SIZE_TITLE = 11;
const FONT_SIZE_META = 7;
const COL_WIDTH_LABEL = 180;
const COL_WIDTH_VALUE = 72;
const COL_WIDTH_PCT = 44;
const ROW_HEIGHT = 12;
const PAGE_MARGIN = 36;
const HEADER_HEIGHT = 56;
const FOOTER_HEIGHT = 36;

const DOUBLE_RULE_LABELS = new Set([
  "TOTAL ASSETS",
  "TOTAL LIABILITIES & NET WORTH",
  "NET PROFIT",
  "EBITDA",
]);

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------

function fmtNumber(val: number | null, isNegative?: boolean): string {
  if (val == null || val === 0) return "\u2014"; // em dash
  let n = isNegative ? -val : val;
  if (n < 0) {
    return `(${Math.abs(n).toLocaleString("en-US", { maximumFractionDigits: 0 })})`;
  }
  return n.toLocaleString("en-US", { maximumFractionDigits: 0 });
}

function fmtPct(val: number | null, base: number | null): string {
  if (val == null || base == null || base === 0) return "\u2014";
  const pct = (val / base) * 100;
  if (pct < 0) {
    return `(${Math.abs(pct).toFixed(1)})`;
  }
  return pct.toFixed(1);
}

function fmtRatioValue(val: number | string | null, format: string, decimals: number): string {
  if (val === "N/A") return "N/A";
  if (val == null) return "\u2014";
  if (typeof val === "string") return val;

  switch (format) {
    case "currency":
      if (val === 0) return "\u2014";
      if (val < 0) return `(${Math.abs(val).toLocaleString("en-US", { maximumFractionDigits: 0 })})`;
      return val.toLocaleString("en-US", { maximumFractionDigits: 0 });
    case "percent":
      if (val < 0) return `(${Math.abs(val).toFixed(decimals)})`;
      return val.toFixed(decimals);
    case "ratio":
      if (val < 0) return `(${Math.abs(val).toFixed(decimals)})`;
      return val.toFixed(decimals);
    case "days":
      if (val < 0) return `(${Math.abs(val).toFixed(decimals)})`;
      return val.toFixed(decimals);
    default:
      return val.toFixed(decimals);
  }
}

// ---------------------------------------------------------------------------
// PDF Document helpers
// ---------------------------------------------------------------------------

type DocState = {
  doc: PDFKit.PDFDocument;
  y: number;
  pageNum: number;
  input: ClassicSpreadInput;
  pageTitle: string;
  periods: StatementPeriod[];
  showPctColumns: boolean;
};

function drawPageHeader(s: DocState) {
  const { doc, input } = s;
  const rightEdge = doc.page.width - PAGE_MARGIN;

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_TITLE);
  doc.text(input.companyName.toUpperCase(), PAGE_MARGIN, PAGE_MARGIN, { width: rightEdge - PAGE_MARGIN });

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_HEADER);
  doc.text(s.pageTitle, PAGE_MARGIN, PAGE_MARGIN + 14, { width: 300 });
  doc.text("Generated by Buddy", rightEdge - 150, PAGE_MARGIN + 14, { width: 150, align: "right" });

  let naicsLine = "";
  if (input.naicsCode) {
    naicsLine = `NAICS: ${input.naicsCode}`;
    if (input.naicsDescription) naicsLine += ` \u2014 ${input.naicsDescription}`;
  }
  doc.fontSize(FONT_SIZE_META);
  if (naicsLine) {
    doc.text(naicsLine, PAGE_MARGIN, PAGE_MARGIN + 28, { width: 350 });
  }
  doc.text(input.preparedDate, rightEdge - 150, PAGE_MARGIN + 28, { width: 150, align: "right" });

  // Horizontal rule below header
  const ruleY = PAGE_MARGIN + HEADER_HEIGHT - 4;
  doc.moveTo(PAGE_MARGIN, ruleY).lineTo(rightEdge, ruleY).lineWidth(0.5).stroke("#333333");

  s.y = PAGE_MARGIN + HEADER_HEIGHT;
}

function drawPageFooter(s: DocState) {
  const { doc, input } = s;
  const rightEdge = doc.page.width - PAGE_MARGIN;
  const footerTop = doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT + 8;

  // Thin rule above footer
  doc.moveTo(PAGE_MARGIN, footerTop).lineTo(rightEdge, footerTop).lineWidth(0.3).stroke("#999999");

  doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META).fillColor("#666666");
  doc.text(`Page ${s.pageNum}`, PAGE_MARGIN, footerTop + 6, { width: 100 });
  doc.text("Buddy The Underwriter", rightEdge - 160, footerTop + 6, { width: 160, align: "right" });

  let naicsLine = input.companyName;
  if (input.naicsCode) {
    naicsLine += `          NAICS ${input.naicsCode}`;
    if (input.naicsDescription) naicsLine += ` \u2014 ${input.naicsDescription}`;
  }
  doc.text(naicsLine, PAGE_MARGIN, footerTop + 16, { width: rightEdge - PAGE_MARGIN });
  doc.text("Confidential \u2014 For Internal Use Only", PAGE_MARGIN, footerTop + 26, { width: rightEdge - PAGE_MARGIN, align: "center" });

  doc.fillColor("#000000"); // reset
}

function newPage(s: DocState) {
  drawPageFooter(s);
  s.doc.addPage();
  s.pageNum++;
  drawPageHeader(s);
}

function checkPageBreak(s: DocState, rowsNeeded: number = 1) {
  const maxY = s.doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT - 10;
  if (s.y + rowsNeeded * ROW_HEIGHT > maxY) {
    newPage(s);
  }
}

// ---------------------------------------------------------------------------
// Statement Metadata Row
// ---------------------------------------------------------------------------

function drawMetadataGrid(s: DocState) {
  const { doc, periods } = s;
  const metaRows = ["Statement Date", "Months Covered", "Audit Method", "Stmt Type"];
  const metaFns: ((p: StatementPeriod) => string)[] = [
    (p) => p.date,
    (p) => String(p.months),
    (p) => p.auditMethod,
    (p) => p.stmtType,
  ];

  doc.fontSize(FONT_SIZE_META);

  for (let r = 0; r < metaRows.length; r++) {
    const rowY = s.y;

    // Label cell (gray bg)
    doc.rect(PAGE_MARGIN, rowY, COL_WIDTH_LABEL, ROW_HEIGHT).fill("#f0f0f0");
    doc.fillColor("#000000").font(FONT_BOLD).fontSize(FONT_SIZE_META);
    doc.text(metaRows[r]!, PAGE_MARGIN + 4, rowY + 2, { width: COL_WIDTH_LABEL - 8 });

    // Value cells
    doc.font(FONT_NORMAL);
    let x = PAGE_MARGIN + COL_WIDTH_LABEL;
    for (let c = 0; c < periods.length; c++) {
      const colW = s.showPctColumns ? COL_WIDTH_VALUE + COL_WIDTH_PCT : COL_WIDTH_VALUE;
      const val = metaFns[r]!(periods[c]!);
      doc.text(val, x + 2, rowY + 2, { width: colW - 4, align: "center" });
      x += colW;
    }

    // Light line
    doc.moveTo(PAGE_MARGIN, rowY + ROW_HEIGHT)
      .lineTo(x, rowY + ROW_HEIGHT)
      .lineWidth(0.2).stroke("#cccccc");

    s.y += ROW_HEIGHT;
  }

  s.y += 4; // gap after metadata
}

// ---------------------------------------------------------------------------
// Column Headers
// ---------------------------------------------------------------------------

function drawColumnHeaders(s: DocState) {
  const { doc, periods } = s;
  const rowY = s.y;

  doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
  doc.text("LINE ITEM", PAGE_MARGIN + 4, rowY + 2, { width: COL_WIDTH_LABEL - 8 });

  let x = PAGE_MARGIN + COL_WIDTH_LABEL;
  for (const p of periods) {
    doc.text(p.label, x, rowY + 2, { width: COL_WIDTH_VALUE, align: "right" });
    x += COL_WIDTH_VALUE;
    if (s.showPctColumns) {
      doc.text("%", x, rowY + 2, { width: COL_WIDTH_PCT, align: "right" });
      x += COL_WIDTH_PCT;
    }
  }

  // Underline
  doc.moveTo(PAGE_MARGIN, rowY + ROW_HEIGHT)
    .lineTo(x, rowY + ROW_HEIGHT)
    .lineWidth(0.5).stroke("#333333");

  s.y = rowY + ROW_HEIGHT + 2;
}

// ---------------------------------------------------------------------------
// Financial Row Rendering
// ---------------------------------------------------------------------------

function drawFinancialRow(s: DocState, row: FinancialRow) {
  if (!row.label && row.values.every((v) => v == null)) {
    s.y += 4; // spacer row
    return;
  }

  checkPageBreak(s);
  const { doc, periods } = s;
  const rowY = s.y;
  const rightEdge = PAGE_MARGIN + COL_WIDTH_LABEL +
    periods.length * (COL_WIDTH_VALUE + (s.showPctColumns && row.showPct ? COL_WIDTH_PCT : 0));

  // Double rule before certain totals
  if (DOUBLE_RULE_LABELS.has(row.label)) {
    doc.moveTo(PAGE_MARGIN, rowY - 1).lineTo(rightEdge, rowY - 1).lineWidth(0.3).stroke("#666666");
    doc.moveTo(PAGE_MARGIN, rowY + 1).lineTo(rightEdge, rowY + 1).lineWidth(0.3).stroke("#666666");
    s.y += 3;
  }

  // Section header: gray background band
  if (row.indent === 0 && row.isBold && row.values.every((v) => v == null)) {
    doc.rect(PAGE_MARGIN, s.y, rightEdge - PAGE_MARGIN, ROW_HEIGHT).fill("#f5f5f5");
    doc.fillColor("#000000");
  }

  // Label
  const indent = row.indent * 12;
  doc.font(row.isBold ? FONT_BOLD : FONT_NORMAL).fontSize(FONT_SIZE_BODY);
  doc.text(row.label, PAGE_MARGIN + 4 + indent, s.y + 2, { width: COL_WIDTH_LABEL - 8 - indent });

  // Values
  let x = PAGE_MARGIN + COL_WIDTH_LABEL;
  for (let i = 0; i < periods.length; i++) {
    const val = row.values[i] ?? null;
    const display = fmtNumber(val, row.isNegative);
    doc.font(row.isBold ? FONT_BOLD : FONT_NORMAL).fontSize(FONT_SIZE_BODY);
    doc.text(display, x, s.y + 2, { width: COL_WIDTH_VALUE - 4, align: "right" });
    x += COL_WIDTH_VALUE;

    if (s.showPctColumns && row.showPct) {
      const base = row.pctBase?.[i] ?? null;
      const pctDisplay = fmtPct(val, base);
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_META);
      doc.text(pctDisplay, x, s.y + 2, { width: COL_WIDTH_PCT - 4, align: "right" });
      x += COL_WIDTH_PCT;
    }
  }

  // Light horizontal rule
  doc.moveTo(PAGE_MARGIN, s.y + ROW_HEIGHT)
    .lineTo(x, s.y + ROW_HEIGHT)
    .lineWidth(0.15).stroke("#dddddd");

  s.y += ROW_HEIGHT;
}

// ---------------------------------------------------------------------------
// Ratio Section Rendering
// ---------------------------------------------------------------------------

function drawRatioSections(s: DocState, sections: RatioSection[]) {
  const { doc, periods } = s;

  for (const section of sections) {
    checkPageBreak(s, 2);

    // Section title: gray band
    const rightEdge = PAGE_MARGIN + COL_WIDTH_LABEL + periods.length * COL_WIDTH_VALUE;
    doc.rect(PAGE_MARGIN, s.y, rightEdge - PAGE_MARGIN, ROW_HEIGHT).fill("#f0f0f0");
    doc.fillColor("#000000");
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
    doc.text(section.title, PAGE_MARGIN + 4, s.y + 2, { width: COL_WIDTH_LABEL - 8 });
    s.y += ROW_HEIGHT;

    for (const row of section.rows) {
      checkPageBreak(s);

      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
      doc.text(row.label, PAGE_MARGIN + 16, s.y + 2, { width: COL_WIDTH_LABEL - 20 });

      let x = PAGE_MARGIN + COL_WIDTH_LABEL;
      for (let i = 0; i < periods.length; i++) {
        const val = row.values[i] ?? null;
        const display = fmtRatioValue(val, row.format, row.decimals);
        doc.text(display, x, s.y + 2, { width: COL_WIDTH_VALUE - 4, align: "right" });
        x += COL_WIDTH_VALUE;
      }

      doc.moveTo(PAGE_MARGIN, s.y + ROW_HEIGHT)
        .lineTo(x, s.y + ROW_HEIGHT)
        .lineWidth(0.15).stroke("#dddddd");

      s.y += ROW_HEIGHT;
    }

    s.y += 6; // gap between sections
  }
}

// ---------------------------------------------------------------------------
// Main Renderer
// ---------------------------------------------------------------------------

export function renderClassicSpread(input: ClassicSpreadInput): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: "letter", margin: PAGE_MARGIN });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const { periods } = input;
    if (periods.length === 0) {
      // No data at all — single page with message
      doc.fontSize(FONT_SIZE_TITLE).text("Classic Banker Spread Report", { align: "center" });
      doc.moveDown();
      doc.fontSize(FONT_SIZE_BODY).text("No financial data available for this deal.", { align: "center" });
      doc.end();
      return;
    }

    // ===== Page 1: Balance Sheet =====
    const s: DocState = {
      doc,
      y: 0,
      pageNum: 1,
      input,
      pageTitle: "Detailed Balance Sheet - Actual and % Amounts",
      periods,
      showPctColumns: true,
    };

    drawPageHeader(s);

    if (input.balanceSheet.length > 0) {
      drawMetadataGrid(s);
      drawColumnHeaders(s);
      for (const row of input.balanceSheet) {
        drawFinancialRow(s, row);
      }
    } else {
      s.y += 20;
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
      doc.text("Balance sheet data not available", PAGE_MARGIN, s.y, { align: "center" });
    }

    drawPageFooter(s);

    // ===== Page 2: Income Statement =====
    doc.addPage();
    s.pageNum++;
    s.pageTitle = "Detailed Income Statement - Actual and % Amounts";
    drawPageHeader(s);

    if (input.incomeStatement.length > 0) {
      drawMetadataGrid(s);
      drawColumnHeaders(s);
      for (const row of input.incomeStatement) {
        drawFinancialRow(s, row);
      }
    } else {
      s.y += 20;
      doc.font(FONT_NORMAL).fontSize(FONT_SIZE_BODY);
      doc.text("Income statement data not available", PAGE_MARGIN, s.y, { align: "center" });
    }

    drawPageFooter(s);

    // ===== Page 3: Ratios =====
    doc.addPage();
    s.pageNum++;
    s.pageTitle = "Detailed Ratios";
    s.showPctColumns = false;
    drawPageHeader(s);

    // Ratio column headers (no % columns)
    const ratioY = s.y;
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_BODY);
    doc.text("RATIO", PAGE_MARGIN + 4, ratioY + 2, { width: COL_WIDTH_LABEL - 8 });
    let rx = PAGE_MARGIN + COL_WIDTH_LABEL;
    for (const p of periods) {
      doc.text(p.label, rx, ratioY + 2, { width: COL_WIDTH_VALUE, align: "right" });
      rx += COL_WIDTH_VALUE;
    }
    doc.moveTo(PAGE_MARGIN, ratioY + ROW_HEIGHT).lineTo(rx, ratioY + ROW_HEIGHT).lineWidth(0.5).stroke("#333333");
    s.y = ratioY + ROW_HEIGHT + 2;

    drawRatioSections(s, input.ratioSections);
    drawPageFooter(s);

    // ===== Page 4: Executive Summary =====
    doc.addPage();
    s.pageNum++;
    s.pageTitle = "Executive Financial Statement - Actual and % Amounts";
    s.showPctColumns = true;
    drawPageHeader(s);

    // Assets section
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER);
    doc.text("ASSETS", PAGE_MARGIN, s.y + 2);
    s.y += ROW_HEIGHT + 2;
    drawColumnHeaders(s);
    for (const row of input.executiveSummary.assets) {
      drawFinancialRow(s, row);
    }

    s.y += 8;

    // Liabilities & Net Worth section
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER);
    doc.text("LIABILITIES & NET WORTH", PAGE_MARGIN, s.y + 2);
    s.y += ROW_HEIGHT + 2;
    for (const row of input.executiveSummary.liabilitiesAndNetWorth) {
      drawFinancialRow(s, row);
    }

    s.y += 8;

    // Income Statement section
    checkPageBreak(s, 8);
    doc.font(FONT_BOLD).fontSize(FONT_SIZE_HEADER);
    doc.text("INCOME STATEMENT", PAGE_MARGIN, s.y + 2);
    s.y += ROW_HEIGHT + 2;
    for (const row of input.executiveSummary.incomeStatement) {
      drawFinancialRow(s, row);
    }

    drawPageFooter(s);

    doc.end();
  });
}
