export type StitchPage = { slug: string; title: string; route?: string; group?: string; };

export const STITCH_PAGES: StitchPage[] = [
  { slug: "audit-compliance-ledger", title: "Audit Compliance Ledger", group: "Compliance", route: "/compliance/audit-ledger" },
  { slug: "borrower-control-record", title: "Borrower Control Record", group: "Borrower", route: "/borrowers/control-record" },
  { slug: "borrower-document-upload-review", title: "Borrower Document Upload Review", group: "Borrower", route: "/borrower/portal" },
  { slug: "borrower-profile", title: "Borrower Profile", group: "Borrower", route: "/borrowers/test-id" },
  { slug: "borrower-task-inbox", title: "Borrower Task Inbox", group: "Borrower", route: "/borrower" },
  { slug: "chargeoff-recovery-command-center", title: "Chargeoff Recovery Command Center", group: "Recovery", route: "/recovery" },
  { slug: "command-center-latest", title: "Command Center Latest", group: "Command", route: "/command" },
  { slug: "credit-committee-view", title: "Credit Committee View", group: "Credit", route: "/credit/committee" },
  { slug: "credit-memo-pdf-template", title: "Credit Memo PDF Template", group: "Credit", route: "/credit-memo" },
  { slug: "deal-intake-console", title: "Deal Intake Console", group: "Deals", route: "/intake" },
  { slug: "deal-output-credit-memo-spreads", title: "Deal Output Credit Memo Spreads", group: "Output", route: "/output" },
  { slug: "deals-command-bridge", title: "Deals Command Bridge", group: "Underwrite", route: "/underwrite" },
  { slug: "deals-pipeline-command-center", title: "Deals Pipeline Command Center", group: "Deals", route: "/deals" },
  { slug: "document-template-vault", title: "Document Template Vault", group: "Templates", route: "/templates/vault" },
  { slug: "exceptions-change-review", title: "Exceptions Change Review", group: "Ops", route: "/exceptions" },
  { slug: "loan-servicing-command-center", title: "Loan Servicing Command Center", group: "Servicing", route: "/servicing" },
  { slug: "merge-field-registry", title: "Merge Field Registry", group: "Admin", route: "/admin/merge-fields" },
  { slug: "ocr-review-data-validation", title: "OCR Review Data Validation", group: "Ops", route: "/ocr-review" },
  { slug: "pipeline-analytics-command-center", title: "Pipeline Analytics Command Center", group: "Analytics", route: "/analytics" },
  { slug: "portfolio-command-bridge", title: "Portfolio Command Bridge", group: "Portfolio", route: "/portfolio" },
  { slug: "pricing-memo-command-center", title: "Pricing Memo Command Center", group: "Pricing", route: "/pricing" },
  { slug: "reo-command-center", title: "REO Command Center", group: "REO", route: "/reo" },
  { slug: "roles-permissions-control", title: "Roles Permissions Control", group: "Admin", route: "/admin/roles" },
  { slug: "stitch_buddy_login_page", title: "Stitch Buddy Login Page", group: "Auth", route: "/stitch-login" },
  { slug: "workout-case-file", title: "Workout Case File", group: "Workout", route: "/workout/case-file" },
  { slug: "workout-command-center", title: "Workout Command Center", group: "Workout", route: "/workout" },
  { slug: "workout-committee-packet", title: "Workout Committee Packet", group: "Workout", route: "/workout/committee-packet" },
  { slug: "workout-legal-execution-tracker", title: "Workout Legal Execution Tracker", group: "Workout", route: "/workout/legal" },
];
