// src/lib/stitch/stitchRouteMap.ts

/**
 * Stitch → App Route Map
 * 
 * Auto-generated from STITCH_ROUTE_DEFS.
 * 
 * DO NOT EDIT THIS FILE.
 * To add routes, edit autoGenerateRouteMap.ts instead.
 */

import { buildStitchRouteMap } from "./autoGenerateRouteMap";

export type StitchRouteMatch = {
  match: (href: string) => boolean;
  to: (href: string) => string;
};

/**
 * Route mapping rules (auto-generated from definitions)
 */
export const STITCH_ROUTE_MAP: StitchRouteMatch[] = buildStitchRouteMap();
