#!/bin/bash
# Test script for bulk upload functionality

set -e

echo "🧪 Testing Bulk Upload Functionality"
echo "===================================="

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo ""
echo -e "${YELLOW}This script helps test the bulk upload feature${NC}"
echo ""
echo "Prerequisites:"
echo "  1. Get a valid borrower portal token from your database"
echo "  2. Create some test files to upload"
echo ""
echo "Example test files you can create:"
echo "  mkdir -p /tmp/test-upload"
echo "  echo 'Bank Statement Q1' > /tmp/test-upload/bank_statement_q1.pdf"
echo "  echo 'Tax Return 2023' > /tmp/test-upload/tax_return_2023.pdf"
echo "  echo 'Personal Financial Statement' > /tmp/test-upload/pfs.pdf"
echo ""
echo "Manual test with curl:"
echo ""
echo "  TOKEN='your-token-here'"
echo "  curl -X POST \\"
echo "    http://localhost:3000/api/borrower/portal/\${TOKEN}/upload \\"
echo "    -F 'files=@/tmp/test-upload/bank_statement_q1.pdf' \\"
echo "    -F 'files=@/tmp/test-upload/tax_return_2023.pdf' \\"
echo "    -F 'files=@/tmp/test-upload/pfs.pdf'"
echo ""
echo -e "${GREEN}✓ Expected response format:${NC}"
echo "  {"
echo "    \"ok\": true,"
echo "    \"deal_id\": \"uuid\"," 
echo "    \"uploaded\": ["
echo "      {"
echo "        \"original_name\": \"bank_statement_q1.pdf\","
echo "        \"stored_path\": \"bank_id/deal_id/timestamp_filename\","
echo "        \"size\": 1234,"
echo "        \"mime_type\": \"application/pdf\","
echo "        \"matched\": true,"
echo "        \"match_confidence\": 92,"
echo "        \"matched_title\": \"Bank statements\""
echo "      },"
echo "      ..."
echo "    ],"
echo "    \"activity\": ["
echo "      {"
echo "        \"kind\": \"UPLOAD_RECEIVED\","
echo "        \"message\": \"Received 3 files.\","
echo "        \"created_at\": \"2024-01-01T00:00:00.000Z\""
echo "      },"
echo "      ..."
echo "    ]"
echo "  }"
echo ""
echo "UI Test:"
echo "  1. Start the dev server: npm run dev"
echo "  2. Open borrower portal: http://localhost:3000/borrower/portal?token=YOUR_TOKEN"
echo "  3. Drag and drop multiple files onto the upload zone"
echo "  4. Verify:"
echo "     - Loading state shows during upload"
echo "     - Success banner appears with file count"
echo "     - Activity feed updates with new uploads"
echo "     - Matched documents show confidence bars"
echo ""
