/**
 * Canonical AI-surface disclaimers (SPEC-M1 AI-GATEWAY-1, Program Invariant
 * #2). Every surface that renders AI-generated or AI-narrated content to a
 * borrower, banker, or lender MUST import its disclaimer from here rather
 * than retype it — enforced by scripts/guards/guard-ai-disclaimer.mjs.
 *
 * No AI output is ever presented as a decision or approval. These strings
 * are the one place that promise gets kept — Matt reviews any change to
 * this file's exported copy before merge (program risk register: "Glass
 * Box read misconstrued as approval promise (UDAP)").
 */

export type DisclaimerSurface = "readiness" | "memo" | "fix_card" | "interview";

export const READINESS_DISCLAIMER =
  "This is a readiness read, not a credit decision or loan approval. " +
  "It's generated by Buddy to help you understand where your application " +
  "stands. Only a licensed lender can approve a loan.";

export const MEMO_DISCLAIMER =
  "AI-assisted draft for banker/underwriter review only. This is not a " +
  "credit decision. All figures come from Buddy's deterministic financial " +
  "model; any narrative text is subject to verification before it can be " +
  "relied on.";

export const FIX_CARD_DISCLAIMER =
  "This suggests documentation or information that could strengthen your " +
  "application. It is not a promise that providing it will change any " +
  "lending decision.";

export const INTERVIEW_DISCLAIMER =
  "This conversation helps Buddy gather information about your business " +
  "and loan request. It is not a credit decision, and nothing said here " +
  "is a commitment by any lender.";

const DISCLAIMERS: Record<DisclaimerSurface, string> = {
  readiness: READINESS_DISCLAIMER,
  memo: MEMO_DISCLAIMER,
  fix_card: FIX_CARD_DISCLAIMER,
  interview: INTERVIEW_DISCLAIMER,
};

export function getDisclaimer(surface: DisclaimerSurface): string {
  return DISCLAIMERS[surface];
}
