-- BRK-10L+10M Alerting + Notification
CREATE TABLE IF NOT EXISTS public.brokerage_alerts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), alert_key text NOT NULL, source text NOT NULL, severity text NOT NULL DEFAULT 'warning' CHECK (severity IN ('critical','warning','info')), status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','resolved','suppressed')), deal_id uuid REFERENCES public.deals(id), title text NOT NULL, message text NOT NULL, action text NOT NULL, first_seen_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz, suppressed_at timestamptz, suppressed_until timestamptz, occurrence_count integer NOT NULL DEFAULT 1, metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE UNIQUE INDEX IF NOT EXISTS brokerage_alerts_active_key ON public.brokerage_alerts (alert_key) WHERE status = 'active';
ALTER TABLE public.brokerage_alerts ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.brokerage_alert_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), alert_id uuid NOT NULL REFERENCES public.brokerage_alerts(id), event_type text NOT NULL CHECK (event_type IN ('created','recurred','resolved','suppressed','escalated')), actor_scope text NOT NULL DEFAULT 'system' CHECK (actor_scope IN ('system','brokerage_ops')), actor_id text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.brokerage_alert_events ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.brokerage_alert_subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subscriber_email text NOT NULL, subscriber_name text, severity_filter text NOT NULL DEFAULT 'critical' CHECK (severity_filter IN ('critical','warning','all')), channel text NOT NULL DEFAULT 'email' CHECK (channel IN ('email','slack','dashboard')), active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.brokerage_alert_subscriptions ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.brokerage_notification_outbox (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), alert_id uuid REFERENCES public.brokerage_alerts(id), subscription_id uuid REFERENCES public.brokerage_alert_subscriptions(id), channel text NOT NULL, recipient text NOT NULL, subject text, body text NOT NULL, status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','failed')), attempts integer NOT NULL DEFAULT 0, last_attempt_at timestamptz, sent_at timestamptz, error text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.brokerage_notification_outbox ENABLE ROW LEVEL SECURITY;
