-- BRK-10E Compliance Package
CREATE TABLE IF NOT EXISTS public.legal_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), document_type text NOT NULL, version text NOT NULL, title text NOT NULL, body_md text NOT NULL, status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','superseded')), effective_at timestamptz, superseded_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS legal_documents_active_type_version_idx ON public.legal_documents (document_type, version) WHERE status = 'active';
ALTER TABLE public.legal_documents ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.brokerage_fee_config (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), version text NOT NULL, status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','superseded')), borrower_packaging_fee_cents integer NOT NULL DEFAULT 100000, borrower_packaging_fee_label text NOT NULL DEFAULT 'SBA loan packaging fee', lender_referral_fee_min_bps integer NOT NULL DEFAULT 100, lender_referral_fee_max_bps integer NOT NULL DEFAULT 200, financed_into_loan_default boolean NOT NULL DEFAULT true, effective_at timestamptz, superseded_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS brokerage_fee_config_one_active ON public.brokerage_fee_config (status) WHERE status = 'active';
ALTER TABLE public.brokerage_fee_config ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.brokerage_disclosures (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), deal_id uuid NOT NULL REFERENCES public.deals(id), borrower_session_token_hash text, disclosure_type text NOT NULL CHECK (disclosure_type IN ('borrower_engagement_letter','fee_disclosure','form_159_preview','two_masters_consent','privacy_notice')), version text NOT NULL, status text NOT NULL DEFAULT 'presented' CHECK (status IN ('presented','acknowledged','voided')), body_md text NOT NULL, presented_at timestamptz NOT NULL DEFAULT now(), acknowledged_at timestamptz, acknowledged_by_name text, acknowledged_by_email text, ip_address inet, user_agent text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS brokerage_disclosures_deal_id_idx ON public.brokerage_disclosures (deal_id);
ALTER TABLE public.brokerage_disclosures ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.brokerage_fee_ledger (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), deal_id uuid NOT NULL REFERENCES public.deals(id), fee_type text NOT NULL CHECK (fee_type IN ('borrower_packaging','lender_referral','success_fee','waiver')), payer_type text NOT NULL CHECK (payer_type IN ('borrower','lender')), payee_type text NOT NULL DEFAULT 'buddy_brokerage', amount_cents integer, bps integer, basis_amount_cents integer, status text NOT NULL DEFAULT 'estimated' CHECK (status IN ('estimated','disclosed','earned','funded','waived','cancelled')), disclosed_on_form_159 boolean NOT NULL DEFAULT false, disclosure_id uuid REFERENCES public.brokerage_disclosures(id), funding_verified_at timestamptz, waived_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS brokerage_fee_ledger_deal_id_idx ON public.brokerage_fee_ledger (deal_id);
ALTER TABLE public.brokerage_fee_ledger ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.sba_form_159_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), deal_id uuid NOT NULL REFERENCES public.deals(id), version text NOT NULL DEFAULT 'v1', status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','generated','borrower_acknowledged','fully_acknowledged','locked','voided')), borrower_fee_cents integer NOT NULL DEFAULT 0, lender_referral_fee_bps integer, lender_referral_fee_estimated_cents integer, lender_bank_id uuid REFERENCES public.banks(id), generated_payload jsonb NOT NULL DEFAULT '{}'::jsonb, generated_pdf_path text, generated_at timestamptz, borrower_acknowledged_at timestamptz, lender_acknowledged_at timestamptz, locked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS sba_form_159_records_deal_id_idx ON public.sba_form_159_records (deal_id);
ALTER TABLE public.sba_form_159_records ENABLE ROW LEVEL SECURITY;
INSERT INTO public.legal_documents (document_type, version, title, body_md, status, effective_at) VALUES ('borrower_engagement_letter','v1','Borrower Engagement Letter','# Engagement Letter\n\nPackaging fee: $1,000.\n\n*DRAFT*','active',now()), ('lender_marketplace_agreement','v1','Lender Agreement','# Lender Agreement\n\nReferral fee per schedule.\n\n*DRAFT*','active',now()), ('fee_disclosure','v1','Fee Disclosure','# Fee Disclosure\n\nPackaging fee + referral fee disclosed on Form 159.\n\n*DRAFT*','active',now()), ('form_159_preview_notice','v1','Form 159 Preview','# Form 159 Preview\n\n*DRAFT*','active',now()), ('two_masters_consent','v1','Two-Masters Consent','# Dual Compensation Disclosure\n\n*DRAFT*','active',now()) ON CONFLICT DO NOTHING;
INSERT INTO public.brokerage_fee_config (version, status, effective_at) VALUES ('v1','active',now()) ON CONFLICT DO NOTHING;
