-- BRK-10H Closing Coordination
CREATE TABLE IF NOT EXISTS public.brokerage_closing_workflows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), deal_id uuid NOT NULL REFERENCES public.deals(id), listing_id uuid REFERENCES public.marketplace_listings(id), claim_id uuid REFERENCES public.marketplace_claims(id), lender_bank_id uuid REFERENCES public.banks(id), status text NOT NULL DEFAULT 'opened' CHECK (status IN ('opened','conditions_pending','submitted_to_lender','clear_to_close','funded','cancelled')), opened_at timestamptz NOT NULL DEFAULT now(), target_close_date date, funded_at timestamptz, cancelled_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE UNIQUE INDEX IF NOT EXISTS brokerage_closing_workflows_one_per_deal ON public.brokerage_closing_workflows (deal_id) WHERE status NOT IN ('cancelled');
ALTER TABLE public.brokerage_closing_workflows ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.brokerage_closing_conditions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_id uuid NOT NULL REFERENCES public.brokerage_closing_workflows(id), deal_id uuid NOT NULL REFERENCES public.deals(id), lender_bank_id uuid REFERENCES public.banks(id), condition_type text NOT NULL, title text NOT NULL, description text, status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','submitted','satisfied','waived','rejected')), source text NOT NULL DEFAULT 'buddy' CHECK (source IN ('buddy','lender','borrower','brokerage_ops')), due_date date, borrower_visible boolean NOT NULL DEFAULT true, lender_visible boolean NOT NULL DEFAULT true, assigned_to text, satisfied_at timestamptz, waived_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS brokerage_closing_conditions_workflow_idx ON public.brokerage_closing_conditions (workflow_id);
ALTER TABLE public.brokerage_closing_conditions ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.brokerage_condition_evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), condition_id uuid NOT NULL REFERENCES public.brokerage_closing_conditions(id), deal_id uuid NOT NULL REFERENCES public.deals(id), document_id uuid REFERENCES public.deal_documents(id), uploaded_by_scope text NOT NULL CHECK (uploaded_by_scope IN ('borrower','brokerage_ops','lender')), note text, status text NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted','accepted','rejected')), reviewed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.brokerage_condition_evidence ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.brokerage_closing_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_id uuid NOT NULL REFERENCES public.brokerage_closing_workflows(id), deal_id uuid NOT NULL REFERENCES public.deals(id), actor_scope text NOT NULL CHECK (actor_scope IN ('borrower','lender','brokerage_ops','system')), actor_id text, event_type text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS brokerage_closing_events_workflow_idx ON public.brokerage_closing_events (workflow_id);
ALTER TABLE public.brokerage_closing_events ENABLE ROW LEVEL SECURITY;
