/**
 * BRK-10D.1 Business Readiness Gate — READY / NOT_READY.
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { runSecurityAudit, type RateLimitSpec, type RouteContract } from "@/lib/brokerage/securityAudit";
export type BusinessReadinessGateStatus = "pass" | "fail" | "skip" | "warn";
export type GateResult = { name: string; category: string; status: BusinessReadinessGateStatus; duration: number; critical: number; warning: number; details: string; repairs: string[] };
export type BusinessReadinessGateResult = { overall: "READY" | "NOT_READY"; gates: GateResult[]; critical: number; warning: number; elapsed: number };
export type BusinessReadinessGateOptions = { skipBuild?: boolean; skipGolden?: boolean; strict?: boolean; sb?: any; dbData?: { listings?: Row[]; claims?: Row[]; picks?: Row[]; accesses?: Row[]; deals?: Row[]; banks?: Row[]; agreements?: Row[]; legalDocuments?: Row[]; feeConfigs?: Row[] } };
type Row = Record<string, any>;
function g(name: string, cat: string, status: BusinessReadinessGateStatus, dur: number, crit: number, warn: number, det: string, rep: string[] = []): GateResult { return { name, category: cat, status, duration: dur, critical: crit, warning: warn, details: det, repairs: rep }; }
function fe(p: string): boolean { return existsSync(resolve(process.cwd(), p)); }
// Transaction flow
export function checkGoldenRunStructure(): GateResult { const s=Date.now(); const r: string[]=[]; let c=0; if (!fe("scripts/golden-brokerage-run.ts")) {c++;r.push("Create scripts/golden-brokerage-run.ts");} if (!fe("src/lib/brokerage/goldenRun.ts")) {c++;r.push("Create src/lib/brokerage/goldenRun.ts");} return g("golden_run_structure","transaction_flow",c>0?"fail":"pass",Date.now()-s,c,0,c===0?"Present":`${c} missing`,r); }
export function checkIntegritySweepStructure(): GateResult { const s=Date.now(); const r: string[]=[]; let c=0; if (!fe("scripts/brokerage-integrity-sweep.ts")) {c++;r.push("Create scripts/brokerage-integrity-sweep.ts");} if (!fe("src/lib/brokerage/integritySweep.ts")) {c++;r.push("Create src/lib/brokerage/integritySweep.ts");} return g("integrity_sweep_structure","transaction_flow",c>0?"fail":"pass",Date.now()-s,c,0,c===0?"Present":`${c} missing`,r); }
export function checkRaceHarnessStructure(): GateResult { const s=Date.now(); const r: string[]=[]; let c=0; if (!fe("scripts/brokerage-race-harness.ts")) {c++;r.push("Create scripts/brokerage-race-harness.ts");} if (!fe("src/lib/brokerage/raceHarness.ts")) {c++;r.push("Create src/lib/brokerage/raceHarness.ts");} return g("race_harness_structure","transaction_flow",c>0?"fail":"pass",Date.now()-s,c,0,c===0?"Present":`${c} missing`,r); }
// Security
export function runSecurityGate(dbData?: Record<string,any>): GateResult { const s=Date.now(); const result = runSecurityAudit({ borrowerIsolation:{sessionA:{tokenHash:"g-a",dealId:"g-da"},sessionB:{tokenHash:"g-b",dealId:"g-db"},resolveSession:h=>h==="g-a"?{deal_id:"g-da"}:h==="g-b"?{deal_id:"g-db"}:null,resolveExpired:()=>null}, lenderIsolation:{listings:dbData?.listings??[],claims:dbData?.claims??[],agreements:dbData?.agreements??[],banks:dbData?.banks??[]}, packageAccess:{accesses:dbData?.accesses??[],claims:dbData?.claims??[],picks:dbData?.picks??[],listings:dbData?.listings??[]}, redaction:{listings:dbData?.listings??[],deals:dbData?.deals??[]}, adminPayloads:{payloads:[{source:"readiness",data:{gate:true}}]}, apiMethodSafety:{routes:[{path:"/api/brokerage/concierge",methods:["POST"],resolvesIdentityServerSide:true,acceptsClientBankId:false,acceptsClientDealId:false},{path:"/api/brokerage/marketplace/pick",methods:["POST"],resolvesIdentityServerSide:true,acceptsClientBankId:false,acceptsClientDealId:false},{path:"/api/lender/marketplace/claim",methods:["POST"],resolvesIdentityServerSide:true,acceptsClientBankId:false,acceptsClientDealId:false},{path:"/api/lender/marketplace/listings",methods:["GET"],resolvesIdentityServerSide:true,acceptsClientBankId:false,acceptsClientDealId:false}] satisfies RouteContract[]}, rateLimits:{specs:[{route:"/api/brokerage/concierge",hasRateLimit:true,limitType:"ip"},{route:"/api/brokerage/discovery",hasRateLimit:true,limitType:"ip"},{route:"/api/brokerage/uploads",hasRateLimit:true,limitType:"ip"},{route:"/api/lender/marketplace/claim",hasRateLimit:true,limitType:"authenticated"},{route:"/api/brokerage/marketplace/pick",hasRateLimit:true,limitType:"session"}] satisfies RateLimitSpec[]} }); const reps=result.findings.filter(f=>f.severity==="critical").map(f=>`${f.route}: ${f.repair}`); return g("security_audit","security",result.ok?"pass":"fail",Date.now()-s,result.critical,result.warning,`${result.total} checks, ${result.critical} critical`,reps); }
// Package generation
export function checkBuildStatus(opts?:{skip?:boolean}): GateResult { const s=Date.now(); if (opts?.skip) return g("build_typecheck","package_generation","skip",0,0,0,"Skipped",[]); try { const pkg=JSON.parse(readFileSync(resolve(process.cwd(),"package.json"),"utf-8")); const w: string[]=[]; if (!pkg.scripts?.typecheck) w.push("No typecheck"); if (!pkg.scripts?.build) w.push("No build"); return g("build_typecheck","package_generation",w.length>0?"warn":"pass",Date.now()-s,0,w.length,w.length===0?"Present":w.join("; "),w); } catch { return g("build_typecheck","package_generation","fail",Date.now()-s,1,0,"package.json not found",[]); } }
export function checkMigrationPresence(): GateResult { const s=Date.now(); const dir=resolve(process.cwd(),"supabase/migrations"); if (!existsSync(dir)) return g("migrations","package_generation","fail",Date.now()-s,1,0,"supabase/migrations not found",[]); const files=readdirSync(dir) as string[]; const reps: string[]=[]; let w=0; for (const req of [{p:"sealing_and_listings",d:"Sealed packages"},{p:"brokerage_tenant_model",d:"Tenant model"},{p:"brokerage_singleton_assert",d:"Singleton"}]) { if (!files.some(f=>f.includes(req.p))) {w++;reps.push(`Missing ${req.d} (${req.p})`);} } return g("migrations","package_generation",w>0?"warn":"pass",Date.now()-s,0,w,w===0?"Present":`${w} missing`,reps); }
// Operations
export function checkRequiredScripts(): GateResult { const s=Date.now(); const reps: string[]=[]; let w=0; for (const sc of [{f:"scripts/golden-brokerage-run.ts",n:"golden:brokerage"},{f:"scripts/brokerage-integrity-sweep.ts",n:"brokerage:integrity"},{f:"scripts/brokerage-race-harness.ts",n:"brokerage:race"},{f:"scripts/brokerage-security-audit.ts",n:"brokerage:security"},{f:"scripts/brokerage-business-readiness.ts",n:"brokerage:ready"}]) { if (!fe(sc.f)) {w++;reps.push(`Create ${sc.f} (pnpm ${sc.n})`);} } return g("required_scripts","operations",w>0?"warn":"pass",Date.now()-s,0,w,w===0?"Present":`${w} missing`,reps); }
export function checkEnvVars(): GateResult { const s=Date.now(); const reps: string[]=[]; let c=0,w=0; if (!process.env.SUPABASE_URL && !process.env.NEXT_PUBLIC_SUPABASE_URL) {c++;reps.push("Set SUPABASE_URL");} if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {c++;reps.push("Set SUPABASE_SERVICE_ROLE_KEY");} if (!process.env.CLERK_SECRET_KEY) {w++;reps.push("Set CLERK_SECRET_KEY (rec)");} if (!process.env.GEMINI_API_KEY) {w++;reps.push("Set GEMINI_API_KEY (rec)");} return g("env_vars","operations",c>0?"fail":w>0?"warn":"pass",Date.now()-s,c,w,c===0&&w===0?"All present":`${c} crit, ${w} opt`,reps); }
export function checkOpsCockpitStructure(): GateResult { const s=Date.now(); const reps: string[]=[]; let w=0; if (!fe("src/lib/brokerage/opsCockpit.ts")) {w++;reps.push("Create opsCockpit.ts");} if (!fe("src/lib/brokerage/opsDiagnostics.ts")) {w++;reps.push("Create opsDiagnostics.ts");} return g("ops_cockpit_structure","operations",w>0?"warn":"pass",Date.now()-s,0,w,w===0?"Present":`${w} missing`,reps); }
// Borrower experience
export async function checkSchemaPresence(args?:{sb?:any}): Promise<GateResult> { const s=Date.now(); if (!args?.sb) return g("schema_presence","borrower_experience","skip",0,0,0,"No SB — skip",[]); const reps: string[]=[]; let c=0; const tables=["borrower_concierge_sessions","borrower_session_tokens","borrower_applications","deal_financial_facts","deal_borrower_story","deal_document_slots","buddy_sba_scores","buddy_trident_bundles","buddy_sealed_packages","marketplace_listings","marketplace_claims","marketplace_picks","marketplace_package_access","marketplace_audit_log","lender_marketplace_agreements"]; for (const t of tables) { try { const {error}=await args.sb.from(t).select("id").limit(0); if (error?.message?.includes("does not exist")) {c++;reps.push(`Table "${t}" missing`);} } catch {} } return g("schema_presence","borrower_experience",c>0?"fail":"pass",Date.now()-s,c,0,c===0?`${tables.length} verified`:`${c} missing`,reps); }
// Lender marketplace
export async function checkRlsAdvisory(args?:{sb?:any}): Promise<GateResult> { const s=Date.now(); if (!args?.sb) return g("rls_advisory","lender_marketplace","skip",0,0,0,"No SB — skip",[]); try { const {data,error}=await args.sb.rpc("get_rls_status_for_tables",{table_names:["marketplace_claims","marketplace_audit_log","lender_marketplace_agreements","marketplace_picks","marketplace_package_access"]}); if (error) return g("rls_advisory","lender_marketplace","warn",Date.now()-s,0,1,"RPC unavailable",[]); let w=0; const reps: string[]=[]; for (const r of (data??[]) as Array<{tablename:string;rowsecurity:boolean}>) { if (!r.rowsecurity) {w++;reps.push(`"${r.tablename}" no RLS`);} } return g("rls_advisory","lender_marketplace",w>0?"warn":"pass",Date.now()-s,0,w,w===0?"RLS OK":`${w} without RLS`,reps); } catch { return g("rls_advisory","lender_marketplace","warn",Date.now()-s,0,1,"RLS check failed",[]); } }
// Compliance
export async function checkLegalDocumentsTable(args?:{sb?:any}): Promise<GateResult> { const s=Date.now(); if (!args?.sb) return g("legal_documents_table","compliance","skip",0,0,0,"No SB",[]); try { const {error}=await args.sb.from("legal_documents").select("id").limit(0); if (error?.message?.includes("does not exist")) return g("legal_documents_table","compliance","fail",Date.now()-s,1,0,"Missing","Run migration"); } catch {} return g("legal_documents_table","compliance","pass",Date.now()-s,0,0,"Exists",[]); }
export function checkLegalTemplates(args?:{legalDocuments?:Row[]}): GateResult { const s=Date.now(); const docs=args?.legalDocuments??[]; const reps: string[]=[]; let w=0; const active=new Map<string,boolean>(); for (const d of docs) if (d.status==="active") active.set(String(d.document_type),true); if (!active.has("borrower_engagement_letter")) {w++;reps.push("Create active engagement letter");} if (!active.has("lender_marketplace_agreement")) {w++;reps.push("Create active lender agreement");} return g("legal_templates","compliance",w>0?"warn":"pass",Date.now()-s,0,w,w===0?"Templates present":`${w} missing`,reps); }
export function checkForm159(args?:{legalDocuments?:Row[]}): GateResult { const s=Date.now(); const docs=args?.legalDocuments??[]; const has=docs.some(d=>String(d.document_type).toLowerCase().includes("form_159")||String(d.document_type).toLowerCase().includes("sba_159")); const gen=fe("src/lib/brokerage/compliancePackage.ts")||fe("src/lib/brokerage/trident/form159.ts")||fe("src/lib/sba/form159.ts"); if (!has&&!gen) return g("form_159","compliance","fail",Date.now()-s,1,0,"No Form 159 generator/template",["Create Form 159"]); return g("form_159","compliance","pass",Date.now()-s,0,0,"Form 159 present",[]); }
export function checkCompliancePackageStructure(): GateResult { const s=Date.now(); const reps: string[]=[]; let w=0; if (!fe("src/lib/brokerage/compliancePackage.ts")) {w++;reps.push("Create compliancePackage.ts");} if (!fe("src/lib/brokerage/complianceEnforcement.ts")) {w++;reps.push("Create complianceEnforcement.ts");} if (!fe("src/lib/brokerage/closingCoordination.ts")) {w++;reps.push("Create closingCoordination.ts");} if (!fe("src/lib/brokerage/revenueOps.ts")) {w++;reps.push("Create revenueOps.ts");} return g("compliance_package_structure","compliance",w>0?"warn":"pass",Date.now()-s,0,w,w===0?"Present":`${w} missing`,reps); }
// Communications
export function checkCommsAdapters(): GateResult { const s=Date.now(); const reps: string[]=[]; let w=0; if (!fe("src/lib/brokerage/commsAdapters.ts")) {w++;reps.push("Create commsAdapters.ts");} if (!process.env.RESEND_API_KEY) {w++;reps.push("Set RESEND_API_KEY");} if (!process.env.TELNYX_API_KEY) {w++;reps.push("Set TELNYX_API_KEY");} return g("comms_adapters","operations",w>0?"warn":"pass",Date.now()-s,0,w,w===0?"Comms ready":`${w} item(s) missing`,reps); }
// Economics
export function checkActiveFeeConfig(args?:{feeConfigs?:Row[]}): GateResult { const s=Date.now(); const cfgs=(args?.feeConfigs??[]).filter(c=>c.status==="active"); if (cfgs.length===0) return g("active_fee_config","economics","warn",Date.now()-s,0,1,"No active fee config",["Run compliance migration"]); return g("active_fee_config","economics","pass",Date.now()-s,0,0,"Active config present",[]); }
export function checkReferralFeeBps(args?:{agreements?:Row[]}): GateResult { const s=Date.now(); const agrs=(args?.agreements??[]).filter(a=>a.status==="active"); const reps: string[]=[]; let w=0; for (const a of agrs) if (a.referral_fee_bps==null||a.referral_fee_bps===0) {w++;reps.push(`Bank ${a.lender_bank_id}: fee ${a.referral_fee_bps??'null'}`);} if (agrs.length===0) return g("referral_fee_bps","economics","warn",Date.now()-s,0,1,"No active agreements",["Onboard lender"]); return g("referral_fee_bps","economics",w>0?"warn":"pass",Date.now()-s,0,w,w===0?`${agrs.length} OK`:`${w} missing fee`,reps); }
export function checkPackageAccessTraceability(args?:{accesses?:Row[];picks?:Row[]}): GateResult { const s=Date.now(); const accesses=args?.accesses??[]; const pci=new Set((args?.picks??[]).filter(p=>p.status==="picked").map(p=>String(p.claim_id))); const reps: string[]=[]; let c=0; for (const a of accesses) if (!pci.has(String(a.claim_id))) {c++;reps.push(`Access ${a.id}: not traced`);} return g("package_access_traceability","economics",c>0?"fail":"pass",Date.now()-s,c,0,c===0?`${accesses.length} traced`:`${c} untraceable`,reps); }
export function checkPackagingFeeConfig(): GateResult { const s=Date.now(); const has=fe("src/lib/brokerage/compliancePackage.ts")||fe("src/lib/brokerage/packagingFee.ts")||fe("src/lib/pricing/packagingFee.ts"); if (!has) return g("packaging_fee_config","economics","warn",Date.now()-s,0,1,"No fee config module",["Create"]); return g("packaging_fee_config","economics","pass",Date.now()-s,0,0,"Present",[]); }
export function checkReferralFeeDisclosure(): GateResult { const s=Date.now(); const has=fe("src/lib/brokerage/compliancePackage.ts")||fe("src/lib/brokerage/referralFeeDisclosure.ts"); if (!has) return g("referral_fee_disclosure","economics","warn",Date.now()-s,0,1,"No disclosure module",["Create"]); return g("referral_fee_disclosure","economics","pass",Date.now()-s,0,0,"Present",[]); }
// Runner
export async function runBusinessReadinessGate(opts?: BusinessReadinessGateOptions): Promise<BusinessReadinessGateResult> {
  const s=Date.now(); const gates: GateResult[] = [];
  if (opts?.skipGolden) gates.push(g("golden_run_structure","transaction_flow","skip",0,0,0,"Skipped",[])); else gates.push(checkGoldenRunStructure());
  gates.push(checkIntegritySweepStructure()); gates.push(checkRaceHarnessStructure()); gates.push(runSecurityGate(opts?.dbData));
  gates.push(checkBuildStatus({skip:opts?.skipBuild})); gates.push(checkMigrationPresence()); gates.push(checkRequiredScripts()); gates.push(checkEnvVars()); gates.push(checkOpsCockpitStructure());
  gates.push(await checkSchemaPresence({sb:opts?.sb})); gates.push(await checkRlsAdvisory({sb:opts?.sb}));
  gates.push(await checkLegalDocumentsTable({sb:opts?.sb})); gates.push(checkLegalTemplates({legalDocuments:opts?.dbData?.legalDocuments})); gates.push(checkForm159({legalDocuments:opts?.dbData?.legalDocuments})); gates.push(checkCompliancePackageStructure());
  gates.push(checkActiveFeeConfig({feeConfigs:opts?.dbData?.feeConfigs})); gates.push(checkReferralFeeBps({agreements:opts?.dbData?.agreements})); gates.push(checkPackageAccessTraceability({accesses:opts?.dbData?.accesses,picks:opts?.dbData?.picks})); gates.push(checkPackagingFeeConfig()); gates.push(checkReferralFeeDisclosure());
  gates.push(checkCommsAdapters());
  const tc=gates.reduce((s,g)=>s+g.critical,0); const tw=gates.reduce((s,g)=>s+g.warning,0);
  let overall: "READY"|"NOT_READY" = tc>0?"NOT_READY":"READY"; if (opts?.strict && tw>0) overall="NOT_READY";
  return { overall, gates, critical: tc, warning: tw, elapsed: Date.now()-s };
}
export const runReadinessGate = runBusinessReadinessGate;
export type ReadinessResult = BusinessReadinessGateResult;
