/**
 * BRK-10J Launch Gate — master go/no-go command.
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { runSecurityAudit, type RateLimitSpec, type RouteContract } from "@/lib/brokerage/securityAudit";
export type LaunchGateStatus = "pass" | "fail" | "skip" | "warn";
export type LaunchGateResult = { name: string; category: string; status: LaunchGateStatus; duration: number; critical: number; warning: number; details: string; repairs: string[] };
export type LaunchResult = { overall: "LAUNCH_READY" | "NOT_LAUNCH_READY"; gates: LaunchGateResult[]; critical: number; warning: number; elapsed: number; firstRepair: string | null };
export type LaunchOptions = { skipBuild?: boolean; strict?: boolean; gate?: string; sb?: any; dbData?: Record<string, any> };
function lg(n: string, c: string, s: LaunchGateStatus, d: number, cr: number, w: number, det: string, r: string[] = []): LaunchGateResult { return { name: n, category: c, status: s, duration: d, critical: cr, warning: w, details: det, repairs: r }; }
function fe(p: string): boolean { return existsSync(resolve(process.cwd(), p)); }

export function checkGoldenRunPresence(): LaunchGateResult { const s=Date.now(); let c=0; const r: string[]=[]; if (!fe("scripts/golden-brokerage-run.ts")) {c++;r.push("Create golden run script");} if (!fe("src/lib/brokerage/goldenRun.ts")) {c++;r.push("Create goldenRun.ts");} return lg("golden_run","transaction_flow",c>0?"fail":"pass",Date.now()-s,c,0,c===0?"Present":`${c} missing`,r); }
export function checkIntegritySweepPresence(): LaunchGateResult { const s=Date.now(); let c=0; const r: string[]=[]; if (!fe("scripts/brokerage-integrity-sweep.ts")) {c++;r.push("Create integrity script");} if (!fe("src/lib/brokerage/integritySweep.ts")) {c++;r.push("Create integritySweep.ts");} return lg("integrity_sweep","transaction_flow",c>0?"fail":"pass",Date.now()-s,c,0,c===0?"Present":`${c} missing`,r); }
export function checkRaceHarnessPresence(): LaunchGateResult { const s=Date.now(); let c=0; const r: string[]=[]; if (!fe("scripts/brokerage-race-harness.ts")) {c++;r.push("Create race script");} if (!fe("src/lib/brokerage/raceHarness.ts")) {c++;r.push("Create raceHarness.ts");} return lg("race_harness","marketplace",c>0?"fail":"pass",Date.now()-s,c,0,c===0?"Present":`${c} missing`,r); }
export function runSecurityGate(dbData?: Record<string, any>): LaunchGateResult { const s=Date.now(); const result=runSecurityAudit({borrowerIsolation:{sessionA:{tokenHash:"la",dealId:"lda"},sessionB:{tokenHash:"lb",dealId:"ldb"},resolveSession:h=>h==="la"?{deal_id:"lda"}:h==="lb"?{deal_id:"ldb"}:null,resolveExpired:()=>null},lenderIsolation:{listings:dbData?.listings??[],claims:dbData?.claims??[],agreements:dbData?.agreements??[],banks:dbData?.banks??[]},packageAccess:{accesses:dbData?.accesses??[],claims:dbData?.claims??[],picks:dbData?.picks??[],listings:dbData?.listings??[]},redaction:{listings:dbData?.listings??[],deals:dbData?.deals??[]},adminPayloads:{payloads:[{source:"launch",data:{}}]},apiMethodSafety:{routes:[{path:"/api/brokerage/concierge",methods:["POST"],resolvesIdentityServerSide:true,acceptsClientBankId:false,acceptsClientDealId:false},{path:"/api/brokerage/marketplace/pick",methods:["POST"],resolvesIdentityServerSide:true,acceptsClientBankId:false,acceptsClientDealId:false},{path:"/api/lender/marketplace/claim",methods:["POST"],resolvesIdentityServerSide:true,acceptsClientBankId:false,acceptsClientDealId:false}]satisfies RouteContract[]},rateLimits:{specs:[{route:"/api/brokerage/concierge",hasRateLimit:true,limitType:"ip"},{route:"/api/brokerage/discovery",hasRateLimit:true,limitType:"ip"},{route:"/api/brokerage/uploads",hasRateLimit:true,limitType:"ip"},{route:"/api/lender/marketplace/claim",hasRateLimit:true,limitType:"authenticated"},{route:"/api/brokerage/marketplace/pick",hasRateLimit:true,limitType:"session"}]satisfies RateLimitSpec[]}}); const reps=result.findings.filter(f=>f.severity==="critical").map(f=>`${f.route}: ${f.repair}`); return lg("security_audit","security",result.ok?"pass":"fail",Date.now()-s,result.critical,result.warning,`${result.total} checks`,reps); }
export function checkClosingPresence(): LaunchGateResult { const s=Date.now(); let w=0; const r: string[]=[]; if (!fe("src/lib/brokerage/closingCoordination.ts")) {w++;r.push("Create closingCoordination.ts");} return lg("closing_coordination","closing",w>0?"warn":"pass",Date.now()-s,0,w,w===0?"Present":`${w} missing`,r); }
export function checkOpsPresence(): LaunchGateResult { const s=Date.now(); let w=0; const r: string[]=[]; for (const f of ["src/lib/brokerage/complianceEnforcement.ts","src/lib/brokerage/packageDelivery.ts","src/lib/brokerage/securityAudit.ts"]) if (!fe(f)) {w++;r.push(`Create ${f}`);} return lg("ops_modules","operations",w>0?"warn":"pass",Date.now()-s,0,w,w===0?"Present":`${w} missing`,r); }
export function checkEnvVars(): LaunchGateResult { const s=Date.now(); let c=0,w=0; const r: string[]=[]; if (!process.env.SUPABASE_URL&&!process.env.NEXT_PUBLIC_SUPABASE_URL) {c++;r.push("Set SUPABASE_URL");} if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {c++;r.push("Set SERVICE_ROLE_KEY");} if (!process.env.CLERK_SECRET_KEY) {w++;} if (!process.env.GEMINI_API_KEY) {w++;} return lg("env_vars","operations",c>0?"fail":w>0?"warn":"pass",Date.now()-s,c,w,`${c} crit, ${w} opt`,r); }
export function checkRequiredScripts(): LaunchGateResult { const s=Date.now(); let w=0; const r: string[]=[]; for (const f of ["scripts/golden-brokerage-run.ts","scripts/brokerage-integrity-sweep.ts","scripts/brokerage-race-harness.ts","scripts/brokerage-security-audit.ts","scripts/brokerage-business-readiness.ts","scripts/brokerage-compliance-check.ts","scripts/brokerage-revenue-check.ts","scripts/brokerage-launch-gate.ts"]) if (!fe(f)) {w++;r.push(`Create ${f}`);} return lg("required_scripts","operations",w>0?"warn":"pass",Date.now()-s,0,w,w===0?"All present":`${w} missing`,r); }
export function checkBuildPresence(opts?:{skip?:boolean}): LaunchGateResult { const s=Date.now(); if (opts?.skip) return lg("production_build","production_build","skip",0,0,0,"Skipped",[]); try { const pkg=JSON.parse(readFileSync(resolve(process.cwd(),"package.json"),"utf-8")); const w: string[]=[]; if (!pkg.scripts?.build) w.push("No build"); if (!pkg.scripts?.typecheck) w.push("No typecheck"); return lg("production_build","production_build",w.length>0?"warn":"pass",Date.now()-s,0,w.length,w.join("; ")||"Present",w); } catch { return lg("production_build","production_build","fail",Date.now()-s,1,0,"package.json missing",[]); } }
export function checkMigrations(): LaunchGateResult { const s=Date.now(); const dir=resolve(process.cwd(),"supabase/migrations"); if (!existsSync(dir)) return lg("migrations","operations","fail",Date.now()-s,1,0,"Dir missing",[]); const files=readdirSync(dir) as string[]; let w=0; const r: string[]=[]; for (const p of ["sealing_and_listings","brokerage_tenant_model","brokerage_singleton_assert","brk_10e_compliance_package","brk_10h_closing_coordination","brk_10i_revenue_ops"]) if (!files.some(f=>f.includes(p))) {w++;r.push(`Missing ${p}`);} return lg("migrations","operations",w>0?"warn":"pass",Date.now()-s,0,w,w===0?"All present":`${w} missing`,r); }

export async function runLaunchGate(opts?: LaunchOptions): Promise<LaunchResult> {
  const s=Date.now(); const gates: LaunchGateResult[]=[]; const filter=opts?.gate?new Set([opts.gate]):null;
  function inc(n: string) { return !filter||filter.has(n); }
  if (inc("golden_run")) gates.push(checkGoldenRunPresence()); if (inc("integrity_sweep")) gates.push(checkIntegritySweepPresence()); if (inc("race_harness")) gates.push(checkRaceHarnessPresence());
  if (inc("security_audit")) gates.push(runSecurityGate(opts?.dbData)); if (inc("closing_coordination")) gates.push(checkClosingPresence()); if (inc("ops_modules")) gates.push(checkOpsPresence());
  if (inc("env_vars")) gates.push(checkEnvVars()); if (inc("required_scripts")) gates.push(checkRequiredScripts()); if (inc("migrations")) gates.push(checkMigrations());
  if (inc("production_build")) gates.push(checkBuildPresence({skip:opts?.skipBuild}));
  const tc=gates.reduce((s,g)=>s+g.critical,0); const tw=gates.reduce((s,g)=>s+g.warning,0);
  let overall: "LAUNCH_READY"|"NOT_LAUNCH_READY" = tc>0?"NOT_LAUNCH_READY":"LAUNCH_READY"; if (opts?.strict&&tw>0) overall="NOT_LAUNCH_READY";
  return { overall, gates, critical:tc, warning:tw, elapsed:Date.now()-s, firstRepair:gates.filter(g=>g.critical>0).flatMap(g=>g.repairs)[0]??null };
}
