/**
 * BRK-10B Race & Retry Harness — concurrency/double-click/retry scenarios.
 */
export type ScenarioResult = { name: string; ok: boolean; elapsed: number; details: string; rowCounts: Record<string, number>; auditEventCount: number; unexpectedMutations: string[] };
export type RaceHarnessResult = { ok: boolean; total: number; passed: number; failed: number; warnings: number; scenarios: ScenarioResult[]; elapsed: number };
type Row = Record<string, any>;
export class RaceSupabaseStub {
  tables: Record<string, Row[]>;
  constructor(init?: Partial<Record<string, Row[]>>) { this.tables = { banks: [], lender_marketplace_agreements: [], marketplace_listings: [], marketplace_claims: [], marketplace_picks: [], marketplace_package_access: [], marketplace_audit_log: [], buddy_sealed_packages: [], deal_documents: [], deal_document_slots: [], ...init }; }
  rpc(name: string, params: Record<string, any>) { if (name === "claim_marketplace_listing") return Promise.resolve({ data: this._claimRpc(params), error: null }); return Promise.resolve({ data: null, error: { message: "unknown_rpc" } }); }
  private _claimRpc(p: Record<string, any>): Record<string, any> {
    const lid = p.p_listing_id, lbid = p.p_lender_bank_id;
    const l = this.tables.marketplace_listings.find(r => r.id === lid);
    if (!l) { this._audit(lid, null, lbid, "claim_failed", { reason: "listing_not_found" }); return { ok: false, error: "listing_not_found" }; }
    if (!["claiming","awaiting_borrower_pick"].includes(l.status)) { this._audit(lid, l.deal_id, lbid, "claim_failed", { reason: "listing_not_claimable" }); return { ok: false, error: "listing_not_claimable" }; }
    const now = new Date();
    if (l.claim_opens_at && now < new Date(l.claim_opens_at)) { this._audit(lid, l.deal_id, lbid, "claim_failed", { reason: "claim_window_not_open" }); return { ok: false, error: "claim_window_not_open" }; }
    if (l.claim_closes_at && now > new Date(l.claim_closes_at)) { this._audit(lid, l.deal_id, lbid, "claim_failed", { reason: "claim_window_closed" }); return { ok: false, error: "claim_window_closed" }; }
    if (!Array.isArray(l.matched_lender_bank_ids) || !l.matched_lender_bank_ids.includes(lbid)) { this._audit(lid, l.deal_id, lbid, "claim_failed", { reason: "lender_not_matched" }); return { ok: false, error: "lender_not_matched" }; }
    if (!this.tables.lender_marketplace_agreements.find(a => a.lender_bank_id === lbid && a.status === "active" && (!a.expires_at || new Date(a.expires_at) > now))) { this._audit(lid, l.deal_id, lbid, "claim_failed", { reason: "no_active_agreement" }); return { ok: false, error: "no_active_agreement" }; }
    if (this.tables.marketplace_claims.filter(c => c.listing_id === lid && c.status === "active").length >= 3) { this._audit(lid, l.deal_id, lbid, "claim_failed", { reason: "max_claims_reached" }); return { ok: false, error: "max_claims_reached" }; }
    const ex = this.tables.marketplace_claims.find(c => c.listing_id === lid && c.lender_bank_id === lbid && c.status === "active");
    if (ex) { this._audit(lid, l.deal_id, lbid, "claim_idempotent", {}); return { ok: true, claim_id: ex.id, idempotent: true }; }
    const cid = `claim-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
    this.tables.marketplace_claims.push({ id: cid, listing_id: lid, deal_id: l.deal_id, lender_bank_id: lbid, status: "active", claimed_at: now.toISOString(), committed_rate_bps: l.published_rate_bps });
    if (l.status === "claiming") l.status = "awaiting_borrower_pick";
    this._audit(lid, l.deal_id, lbid, "claim_succeeded", { claim_id: cid });
    return { ok: true, claim_id: cid, idempotent: false };
  }
  private _audit(lid: string, did: string|null, bid: string|null, action: string, meta: any) { this.tables.marketplace_audit_log.push({ id: `a-${Date.now()}-${Math.random().toString(36).slice(2,6)}`, listing_id: lid, deal_id: did, actor_bank_id: bid, actor_scope: "lender", action, metadata: meta, created_at: new Date().toISOString() }); }
  from(table: string) { return new RQB(this, table); }
}
class RQB {
  db: RaceSupabaseStub; table: string; filters: Array<{t:string;k:string;v:any}>; _upd: Row|null; _ins: Row[]|null;
  constructor(db: RaceSupabaseStub, t: string) { this.db = db; this.table = t; this.filters = []; this._upd = null; this._ins = null; }
  select(_?: string) { return this; } order(_k: string, _o?: any) { return this; } limit(_n: number) { return this; }
  eq(k: string, v: any) { this.filters.push({t:"eq",k,v}); return this; }
  neq(k: string, v: any) { this.filters.push({t:"neq",k,v}); return this; }
  in(k: string, v: any[]) { this.filters.push({t:"in",k,v}); return this; }
  is(k: string, v: any) { this.filters.push({t:"is",k,v}); return this; }
  insert(p: Row|Row[]) { const rows = Array.isArray(p)?p:[p]; const wi = rows.map(r => ({id:r.id??`id-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,...r})); this.db.tables[this.table]??=[]; this.db.tables[this.table].push(...wi); this._ins = wi; return this; }
  update(u: Row) { this._upd = u; return this; }
  single(): Promise<{data:any;error:any}> { if (this._ins) return Promise.resolve({data:this._ins[0]??null,error:null}); return Promise.resolve({data:this.rows()[0]??null,error:null}); }
  maybeSingle(): Promise<{data:any;error:any}> { if (this._upd) { this.doUpd(); return Promise.resolve({data:this.rows()[0],error:null}); } return Promise.resolve({data:this.rows()[0]??null,error:null}); }
  then(f:any, r?:any) { if (this._upd) { this.doUpd(); return Promise.resolve({data:this.rows(),error:null}).then(f,r); } if (this._ins) return Promise.resolve({data:this._ins,error:null}).then(f,r); return Promise.resolve({data:this.rows(),error:null}).then(f,r); }
  private doUpd() { for (const row of this.rows()) Object.assign(row, this._upd); }
  private rows() { let rows = [...(this.db.tables[this.table]??[])]; for (const f of this.filters) { if (f.t==="eq") rows=rows.filter(r=>r[f.k]===f.v); else if (f.t==="neq") rows=rows.filter(r=>r[f.k]!==f.v); else if (f.t==="in") rows=rows.filter(r=>(f.v as any[]).includes(r[f.k])); else if (f.t==="is") rows=rows.filter(r=>{const v=r[f.k]; return f.v===null?v===null||v===undefined:v===f.v;}); } return rows; }
}
function makeDb(n: number): RaceSupabaseStub { const ids = Array.from({length:n},(_,i)=>`lender-${i+1}`); return new RaceSupabaseStub({ banks: ids.map(id=>({id,bank_kind:"commercial_bank"})), lender_marketplace_agreements: ids.map(id=>({id:`agr-${id}`,lender_bank_id:id,status:"active",expires_at:null})), marketplace_listings: [{id:"listing-race",deal_id:"deal-race",sealed_package_id:"sp-race",status:"claiming",claim_opens_at:"2020-01-01T00:00:00Z",claim_closes_at:"2099-01-01T00:00:00Z",matched_lender_bank_ids:ids,published_rate_bps:300}], buddy_sealed_packages: [{id:"sp-race",deal_id:"deal-race",unsealed_at:null}] }); }
function counts(db: RaceSupabaseStub) { return { claims: db.tables.marketplace_claims.length, activeClaims: db.tables.marketplace_claims.filter(c=>c.status==="active").length, picks: db.tables.marketplace_picks.length, accesses: db.tables.marketplace_package_access.length, auditEvents: db.tables.marketplace_audit_log.length }; }
async function claim(db: RaceSupabaseStub, lid: string, lbid: string) { return db.rpc("claim_marketplace_listing", { p_listing_id: lid, p_lender_bank_id: lbid }); }
async function pick(db: RaceSupabaseStub, claimId: string, dealId: string) {
  const { data: cl } = await db.from("marketplace_claims").select("*").eq("id",claimId).maybeSingle();
  if (!cl || String(cl.deal_id) !== dealId) return { ok: false, error: "claim_deal_mismatch" };
  if (String(cl.status) !== "active") { if (String(cl.status) === "picked") { const { data: ep } = await db.from("marketplace_picks").select("id").eq("claim_id",claimId).eq("deal_id",dealId).in("status",["pending","picked"]).maybeSingle(); if (ep) return { ok: true, pickId: String(ep.id) }; } return { ok: false, error: "claim_not_active" }; }
  const lid = String(cl.listing_id); const { data: ep2 } = await db.from("marketplace_picks").select("id, claim_id").eq("listing_id",lid).eq("deal_id",dealId).in("status",["pending","picked"]).maybeSingle();
  if (ep2) { if (String(ep2.claim_id) === claimId) return { ok: true, pickId: String(ep2.id) }; return { ok: false, error: "different_claim_already_picked" }; }
  const ts = new Date().toISOString(); const pid = `pick-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
  db.tables.marketplace_picks.push({ id: pid, listing_id: lid, deal_id: dealId, claim_id: claimId, picked_lender_bank_id: cl.lender_bank_id, status: "picked", borrower_selected_at: ts });
  await db.from("marketplace_claims").update({ status: "picked", updated_at: ts }).eq("id", claimId);
  await db.from("marketplace_claims").update({ status: "rejected", expired_at: ts, updated_at: ts }).eq("listing_id", lid).eq("status", "active").neq("id", claimId);
  await db.from("marketplace_listings").update({ status: "picked", picked_at: ts, updated_at: ts }).eq("id", lid);
  db.tables.marketplace_audit_log.push({ id: `a-${Date.now()}`, listing_id: lid, deal_id: dealId, actor_scope: "borrower", action: "borrower_pick", metadata: { claim_id: claimId, pick_id: pid } });
  return { ok: true, pickId: pid };
}
async function unlock(db: RaceSupabaseStub, claimId: string, dealId: string) {
  const { data: cl } = await db.from("marketplace_claims").select("*").eq("id",claimId).maybeSingle();
  if (!cl || String(cl.deal_id) !== dealId) return { ok: false, error: "claim_deal_mismatch" };
  if (String(cl.status) !== "picked") return { ok: false, error: "claim_not_picked" };
  const lid = String(cl.listing_id); const { data: listing } = await db.from("marketplace_listings").select("sealed_package_id, status").eq("id",lid).maybeSingle();
  if (!listing || String(listing.status) !== "picked") return { ok: false, error: "listing_not_picked" };
  const spid = String(listing.sealed_package_id); const { data: sp } = await db.from("buddy_sealed_packages").select("id").eq("id",spid).is("unsealed_at",null).maybeSingle();
  if (!sp) return { ok: false, error: "sealed_package_not_found" };
  const { data: ex } = await db.from("marketplace_package_access").select("id").eq("claim_id",claimId).is("revoked_at",null).maybeSingle();
  if (ex) return { ok: true, accessId: String(ex.id), idempotent: true };
  const aid = `access-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
  db.tables.marketplace_package_access.push({ id: aid, listing_id: lid, claim_id: claimId, deal_id: dealId, lender_bank_id: cl.lender_bank_id, sealed_package_id: spid, access_level: "full" });
  db.tables.marketplace_audit_log.push({ id: `a-${Date.now()}`, listing_id: lid, deal_id: dealId, actor_scope: "system", action: "package_unlocked", metadata: { claim_id: claimId, access_id: aid } });
  return { ok: true, accessId: aid, idempotent: false };
}
async function s1(): Promise<ScenarioResult> { const start=Date.now(); const db=makeDb(5); const um: string[]=[]; const results=await Promise.all(["lender-1","lender-2","lender-3","lender-4","lender-5"].map(id=>claim(db,"listing-race",id))); const ok=results.filter(r=>(r.data as any)?.ok); const fail=results.filter(r=>!(r.data as any)?.ok); const c=counts(db); if (c.activeClaims>3) um.push(`active ${c.activeClaims}>3`); if (ok.length>3) um.push(`ok ${ok.length}>3`); const als=db.tables.marketplace_claims.filter(c=>c.status==="active").map(c=>c.lender_bank_id); if (new Set(als).size!==als.length) um.push("dup lender"); return { name:"concurrent_claims_5_lenders", ok:um.length===0, elapsed:Date.now()-start, details:`${ok.length} ok, ${fail.length} fail`, rowCounts:c, auditEventCount:c.auditEvents, unexpectedMutations:um }; }
async function s2(): Promise<ScenarioResult> { const start=Date.now(); const db=makeDb(1); const um: string[]=[]; const results=await Promise.all(Array.from({length:5},()=>claim(db,"listing-race","lender-1"))); const c=counts(db); if (c.activeClaims!==1) um.push(`active ${c.activeClaims}!=1`); const fresh=results.filter(r=>(r.data as any)?.ok&&!(r.data as any)?.idempotent).length; const idemp=results.filter(r=>(r.data as any)?.ok&&(r.data as any)?.idempotent).length; if (fresh!==1) um.push(`fresh ${fresh}!=1`); if (idemp!==4) um.push(`idemp ${idemp}!=4`); const ids=new Set(results.filter(r=>(r.data as any)?.ok).map(r=>(r.data as any).claim_id)); if (ids.size!==1) um.push(`${ids.size} ids`); return { name:"double_click_claim", ok:um.length===0, elapsed:Date.now()-start, details:`${fresh} fresh, ${idemp} idemp`, rowCounts:c, auditEventCount:c.auditEvents, unexpectedMutations:um }; }
async function s3(): Promise<ScenarioResult> { const start=Date.now(); const db=makeDb(1); const um: string[]=[]; await claim(db,"listing-race","lender-1"); const cid=db.tables.marketplace_claims[0].id; for (let i=0;i<5;i++) await pick(db,cid,"deal-race"); const c=counts(db); if (c.picks!==1) um.push(`picks ${c.picks}!=1`); const picked=db.tables.marketplace_claims.filter(x=>x.status==="picked"); if (picked.length!==1) um.push(`picked claims ${picked.length}!=1`); for (let i=0;i<3;i++) await unlock(db,cid,"deal-race"); const ac=db.tables.marketplace_package_access.filter(a=>a.revoked_at===undefined||a.revoked_at===null).length; if (ac!==1) um.push(`access ${ac}!=1`); return { name:"double_click_pick", ok:um.length===0, elapsed:Date.now()-start, details:`${c.picks} picks, ${ac} access`, rowCounts:{...c,accesses:ac}, auditEventCount:db.tables.marketplace_audit_log.length, unexpectedMutations:um }; }
async function s4(): Promise<ScenarioResult> { const start=Date.now(); const db=makeDb(2); const um: string[]=[]; await claim(db,"listing-race","lender-1"); await claim(db,"listing-race","lender-2"); const c1=db.tables.marketplace_claims.find(c=>c.lender_bank_id==="lender-1")!; const c2=db.tables.marketplace_claims.find(c=>c.lender_bank_id==="lender-2")!; const r1=await pick(db,c1.id,"deal-race"); const r2=await pick(db,c2.id,"deal-race"); const c=counts(db); if (c.picks>1) um.push(`picks ${c.picks}>1`); if (r1.ok&&r2.ok) um.push("both picks succeeded"); return { name:"concurrent_picks_two_claims", ok:um.length===0, elapsed:Date.now()-start, details:`r1=${r1.ok},r2=${r2.ok}`, rowCounts:c, auditEventCount:db.tables.marketplace_audit_log.length, unexpectedMutations:um }; }
async function s5(): Promise<ScenarioResult> { const start=Date.now(); const db=makeDb(1); const um: string[]=[]; await claim(db,"listing-race","lender-1"); const cid=db.tables.marketplace_claims[0].id; await pick(db,cid,"deal-race"); const results: any[]=[]; for (let i=0;i<5;i++) results.push(await unlock(db,cid,"deal-race")); const ac=db.tables.marketplace_package_access.filter(a=>a.revoked_at===undefined||a.revoked_at===null).length; if (ac!==1) um.push(`access ${ac}!=1`); if (results.filter(r=>r.ok).length!==5) um.push(`not all ok`); const ids=new Set(results.filter(r=>r.ok).map(r=>r.accessId)); if (ids.size!==1) um.push(`${ids.size} ids`); const idemp=results.filter(r=>r.ok&&r.idempotent).length; if (idemp<4) um.push(`idemp ${idemp}<4`); return { name:"unlock_retry", ok:um.length===0, elapsed:Date.now()-start, details:`${results.filter(r=>r.ok).length}/5 ok, ${idemp} idemp`, rowCounts:counts(db), auditEventCount:db.tables.marketplace_audit_log.length, unexpectedMutations:um }; }
async function s6(): Promise<ScenarioResult> { const start=Date.now(); const db=new RaceSupabaseStub({deal_document_slots:[{id:"slot-1",deal_id:"deal-race",required_doc_type:"BTR"}]}); const um: string[]=[]; for (let i=0;i<5;i++) { if (db.tables.deal_documents.find(d=>d.deal_id==="deal-race"&&d.slot_id==="slot-1"&&d.finalized_at)) continue; db.tables.deal_documents.push({id:`doc-${i}`,deal_id:"deal-race",slot_id:"slot-1",finalized_at:new Date().toISOString()}); } const attached=db.tables.deal_documents.filter(d=>d.deal_id==="deal-race"&&d.slot_id==="slot-1").length; if (attached!==1) um.push(`${attached} docs`); return { name:"upload_retry", ok:um.length===0, elapsed:Date.now()-start, details:`${attached} doc(s)`, rowCounts:{documents:db.tables.deal_documents.length}, auditEventCount:0, unexpectedMutations:um }; }
async function s7(): Promise<ScenarioResult> { const start=Date.now(); const closesAt=new Date(Date.now()+100); const db=new RaceSupabaseStub({banks:[{id:"lender-1",bank_kind:"commercial_bank"},{id:"lender-2",bank_kind:"commercial_bank"}],lender_marketplace_agreements:[{id:"a1",lender_bank_id:"lender-1",status:"active",expires_at:null},{id:"a2",lender_bank_id:"lender-2",status:"active",expires_at:null}],marketplace_listings:[{id:"listing-w",deal_id:"deal-race",status:"claiming",claim_opens_at:"2020-01-01T00:00:00Z",claim_closes_at:closesAt.toISOString(),matched_lender_bank_ids:["lender-1","lender-2"],published_rate_bps:300}]}); const um: string[]=[]; const r1=await claim(db,"listing-w","lender-1"); if (!(r1.data as any)?.ok) um.push("before-close should succeed"); await new Promise(resolve=>setTimeout(resolve,150)); const r2=await claim(db,"listing-w","lender-2"); if ((r2.data as any)?.ok) um.push("after-close should fail"); return { name:"claim_window_boundary", ok:um.length===0, elapsed:Date.now()-start, details:`before=${(r1.data as any)?.ok},after=${(r2.data as any)?.ok}`, rowCounts:{activeClaims:db.tables.marketplace_claims.filter(c=>c.status==="active").length}, auditEventCount:db.tables.marketplace_audit_log.length, unexpectedMutations:um }; }
async function s8(): Promise<ScenarioResult> { const start=Date.now(); const db=makeDb(1); const um: string[]=[]; await claim(db,"listing-race","lender-1"); const cid=db.tables.marketplace_claims[0].id; const r=await pick(db,cid,"deal-WRONG"); if (r.ok) um.push("wrong deal should fail"); if (db.tables.marketplace_picks.length!==0) um.push("no picks"); if (db.tables.marketplace_listings[0].status==="picked") um.push("listing not picked"); return { name:"wrong_session_pick", ok:um.length===0, elapsed:Date.now()-start, details:`ok=${r.ok},error=${(r as any).error}`, rowCounts:counts(db), auditEventCount:db.tables.marketplace_audit_log.length, unexpectedMutations:um }; }
async function s9(): Promise<ScenarioResult> { const start=Date.now(); const db=makeDb(1); const um: string[]=[]; await claim(db,"listing-race","lender-1"); const cid=db.tables.marketplace_claims[0].id; const r=await unlock(db,cid,"deal-race"); if (r.ok) um.push("pre-pick unlock should fail"); if (r.ok===false && r.error!=="claim_not_picked") um.push(`expected claim_not_picked got ${r.error}`); if (db.tables.marketplace_package_access.length!==0) um.push("no access"); return { name:"pre_pick_access_denied", ok:um.length===0, elapsed:Date.now()-start, details:`ok=${r.ok}`, rowCounts:counts(db), auditEventCount:db.tables.marketplace_audit_log.length, unexpectedMutations:um }; }
async function s10(): Promise<ScenarioResult> { const start=Date.now(); const db=makeDb(2); const um: string[]=[]; await claim(db,"listing-race","lender-1"); await claim(db,"listing-race","lender-2"); const c1=db.tables.marketplace_claims.find(c=>c.lender_bank_id==="lender-1")!; const c2=db.tables.marketplace_claims.find(c=>c.lender_bank_id==="lender-2")!; await pick(db,c1.id,"deal-race"); const r1=await unlock(db,c1.id,"deal-race"); if (!r1.ok) um.push("picked unlock should succeed"); const r2=await unlock(db,c2.id,"deal-race"); if (r2.ok) um.push("non-picked should fail"); const ac=db.tables.marketplace_package_access.filter(a=>a.revoked_at===undefined||a.revoked_at===null).length; if (ac!==1) um.push(`access ${ac}!=1`); return { name:"non_picked_lender_access", ok:um.length===0, elapsed:Date.now()-start, details:`picked=${r1.ok},non=${r2.ok}`, rowCounts:counts(db), auditEventCount:db.tables.marketplace_audit_log.length, unexpectedMutations:um }; }
export const ALL_SCENARIOS: Array<{name:string;fn:()=>Promise<ScenarioResult>}> = [{name:"concurrent_claims_5_lenders",fn:s1},{name:"double_click_claim",fn:s2},{name:"double_click_pick",fn:s3},{name:"concurrent_picks_two_claims",fn:s4},{name:"unlock_retry",fn:s5},{name:"upload_retry",fn:s6},{name:"claim_window_boundary",fn:s7},{name:"wrong_session_pick",fn:s8},{name:"pre_pick_access_denied",fn:s9},{name:"non_picked_lender_access",fn:s10}];
export async function runRaceHarness(opts?:{scenario?:string}): Promise<RaceHarnessResult> { const start=Date.now(); const scenarios=opts?.scenario?ALL_SCENARIOS.filter(s=>s.name===opts.scenario):ALL_SCENARIOS; const results: ScenarioResult[]=[]; for (const s of scenarios) results.push(await s.fn()); const passed=results.filter(r=>r.ok).length; const failed=results.filter(r=>!r.ok).length; return { ok:failed===0, total:results.length, passed, failed, warnings:results.reduce((s,r)=>s+r.unexpectedMutations.length,0), scenarios:results, elapsed:Date.now()-start }; }
